### ISSUE TITLE
xoops update

### ISSUE THREAD

**Issue by mambax7** [turnkeylinux/tracker#1009]
https://hub.docker.com/r/turnkeylinux/xoops-14.2/ still has XOOPS 2.5.8
Any chance to update it to XOOPS 2.5.9 ? 

Also, it might be easier to link the downloads to GitHub releases: 
https://github.com/XOOPS/XoopsCore25/releases

Thank you!

**Comment by JedMeister** [comment]
Hi @mambax7 thanks for the feedback. We're currently in the depths of pushing out our v15.0 release. This one is taking much longer than I'd ideally hoped, but seeing as it's a major OS jump (Debian Jessie -> Stretch) there's a fair bit more work involved. 

We've already pushed our changes for v15.0 to the [Xoops repo](https://github.com/turnkeylinux-apps/xoops), so it will now include the latest version of Xoops (2.5.9). FWIW it will also include PHP 7.0 (finally). However, seeing as we haven't yet released v15.0 and there are a few changes, it won't still build for v14.x. So until we release v15.0 Core, it won't build with the current code.

If you are interested, I can assist you to rebuild v14.2 with the latest version of Xoops if you wish. Otherwise, we'll hopefully have an updated Xoops appliance within the next month or so.

**Comment by JedMeister** [comment]
@OnGle - please note, nothing needs doing by you here, I just wanted to assign someone so no one accidentally starts working on it (seeing as you've done it already).

**Comment by mambax7** [comment]
@JedMeister , if you have somewhere written instructions on how to rebuild the 14.2 version, I might take a look, if I find some time and if my skills level will allow me to do it. 
Of course, if v15.0 is coming very soon, it might not make any sense to do it, but at least I might learn something from reading the instructions...

**Comment by JedMeister** [comment]
@mambax7 - we're really close to releasing v15.0RC of our base appliance, [Core](https://www.turnkeylinux.org/core). Once that is released and we have had a bit of feedback (perhaps a week +/-?!) then we'll make any changes or adjustments and start building the whole library.

As my colleague is currently blocking me (and I can't do the release until I'm unblocked) I can't say for sure how far away that will be, but I'm hoping a matter of days before we release the RC, and a few weeks before we have the whole library updated to v15.0. Having said that, my powers of premonition are very poor!

In the meantime, if you want to rebuild v14.2 with an updated version, you'll need to download a copy of [TKLDev](https://www.turnkeylinux.org/tkldev) and install it into a VM. Then you'll need to clone the Xoops buildcode repo and make some minor modifications (this is OTTOMH so may contain mistakes):
```
cd products
git clone https://github.com/turnkeylinux-apps/xoops.git
cd xoops
git checkout 34a3036 # don't use the v15.0 changelog
sed -i "s|php-|php5-|" plans/main # revert changes to package names for Debian Stretch
```
Then when you're ready to make the appliance, you can run `make` and when it's done, you should find your shiny new ISO in `build/product.iso`.

If you'd rather do one of the other build targets (e.g. LXC container, OVF, etc), we'll need to build the ISO first, but we use a slightly different method.
```
cd buildtasks
./bt-iso xoops
./bt-BUILDTYPE xoops-14.2-jessie-amd64
```
Then you'll find ISOs in `/mnt/isos` and other builds in `/mnt/builds/BUILDTYPE`

**Comment by OnGle** [comment]
It appears this issue has already been solved (here https://github.com/turnkeylinux-apps/xoops/commit/9edd3635c655b2defcf5c05cbf230e7ffc88b7f9). I'll still rebase the download on github but I'm going to close this issue since it's primary purpose has been addressed.
