### ISSUE TITLE
Drop foodsoft-adam support

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#1012]
Foodsoft-adam fork hasn't been updated in a long time, latest release was on Jun 11, 2016

In Stretch i get deprecated gems warnings and database migrations error. After all this fork is still on Rails 3

@wvengen your input on this would be greatly appreciated e. g. ETA on https://github.com/foodcoop-adam/foodsoft/tree/beta branch release, in case there is one. Thanks!

**Comment by JedMeister** [comment]
Unless we hear back sometime soon, my inclination would be to ship it with just the default install (i.e. drop support for adam fork). 

Even if we do hear back, unless an update is nearly ready, I'm not sure we should include it. Let's wait and see if @wvengen has any input.

**Comment by wvengen** [comment]
Sounds good, it's outdated (even though still used in places), and will fully transition to the main fork in the long term

**Comment by JedMeister** [comment]
Great thanks for the feedback @wvengen - we'll drop adam's fork for the v15.0 Foodsoft appliance.

Also as an aside, once we have v15.0 finalised, we'll have facility to do individual appliance updates (until v14.2 all appliances needed to have the same version number). So that will mean it'll be possible to update individual appliances as much as we/you like. 

So moving forward, once we have v15.0 released, please feel free to give us a ping anytime you think we should update the appliance. Obviously we'll do that ourselves from time to time, but more than happy for your input on that. :smile:
