### ISSUE TITLE
Appliances including Samba should possibly also include (optional) OpenVPN site-to-site setup

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1021]
Seeing as it's not recommended to use Samba on the open internet, we should really consider including an (optional) OpenVPN site-to-site setup?! Perhaps it could be included as a confconsole option at least? I.e. install OpenVPN and provide initial site-to-site setup.

IMO at least the cloud builds should include that, perhaps even pre-configured/pre-installed? Regardless, it should at least be optional!

**Comment by MPTMG** [comment]
As a turnkey solution OpenVPN site to site would be useful, but if someone is setting up OpenVPN site to site for samba over geographically separated LANs they probably have the technical expertise and requirements to setup something specific to their network infrastructure and will be handling interconnecting LANs through network security appliances.

Something simple to implement and probably more targeted at the user base for preconfigured appliances would be integrating something like Zero Tier One https://www.zerotier.com. My personal opinion is it would allow the greatest flexibility and accessibility for users interested in preconfigured appliances.

Zero Tier One has Debian packages and command line configuration is dead simple. 

I was thinking about using Zero Tier One for my Remote Apple Time Machine Appliance instead of L2TP ipsec with Raccoon.

My .02

**Comment by JedMeister** [comment]
Awesome suggestion @MPTMG - thanks for that. I've never heard of it before, but it looks awesome! I'll have a bit more of a read!

**Comment by MPTMG** [comment]
@JedMeister I took the liberty of creating everything necessary for integrating ZeroTier One into an appliance. Essentially the overlay with repo, gpg, confconsole plugins etc. All that anyone would need to add would be in conf.d/main apt-get -y install zerotier-one and it would allow confconsole configuration of ZeroTier One vpn networks. I figure this might take care of the issue with TVheadend and the htsp proxy issues as we could make it a non-internet accessible port and only accessible via vpn/private networks.

Ideally we can make it is as simple to include as zerotier in the makefile overlays by having a zerotier option that would also include the apt-get -y install zerotier-one. So a one line inclusion for everything necessary to set it up. Not sure how you guys handle those things otherwise I would have done it already.

Repo: https://github.com/MPTMG/TKL-ZeroTierOne

**Comment by MPTMG** [comment]
Edited this to make it such that install and remove are part of confconsole so users can choose to add it or remove it from confconsole eliminating need for install at build time. This way users who want it can install and configure it easily and those that don't can ignore it and won't have any unnecessary packages installed.

**Comment by MPTMG** [comment]
On a side not one could just block ports for smb, afp, htsp, etc for all connections other than those from private IP addresses.(One UFW command for every port/port range) For the TimeCapsule appliance I am working on I just made it such that afp is only listening on a the vpn IP eliminating the need for the firewall rules. This would make it such that the open internet would not be able to access those services and facilitate easy local access without additional configuration.

Private IP Ranges to Allow Block Everything Else.
24-bit block | 10.0.0.0 – 10.255.255.255 | 8 bits
20-bit block | 172.16.0.0 – 172.31.255.255 | 12 bits
16-bit block | 192.168.0.0 – 192.168.255.255 | 16 bits

Then include vpn connection options via confconsole.

**Comment by JedMeister** [comment]
This looks really awesome man. I love it that you've done it as a plugin. I think it would be a brilliant addition.

**Comment by JedMeister** [comment]
Unfortunately it looks like @MPTMG has closed his account?! :cry: So we no longer have access to him or his proposed code.

**Comment by JedMeister** [comment]
I'm just going to close this for now...
