### ISSUE TITLE
TKLBAM webmin module not repoducible

### ISSUE THREAD

**Issue by lamby** [turnkeylinux/tracker#1028]
Splitting from #876:

Hey @lamby - I just tested our [TKLBAM Webmin module](https://github.com/turnkeylinux/webmin-tklbam) and it doesn't seem to be reproducible?! For good measure, I built it 3 times (I know, no good reason and no real advantage...).
```
root@da-shiz pools/stretch# shasum build-1/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
95f92d31a8ff43f97e8b71de41bd9503976da100  build-1/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
root@da-shiz pools/stretch# shasum build-2/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
6c37463df4b58b8c7ab671149244ba450b3b7357  build-2/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
root@da-shiz pools/stretch# shasum build-3/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
756f69a12b665778f57522f55e685b180242bb15  build-3/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
```
Admittedly I have made [some tweaks](https://github.com/turnkeylinux/webmin-tklbam/commit/7bbf82f563932e75491ba9b80e159c4f1b60cd95) since you worked on it, so maybe it's something I broke? But after having a [look via diffoscope](https://try.diffoscope.org/gtbgaurdctfz.html) I'm pretty sure it's nothing to do with me.

Could you please have a look?

**Comment by lamby** [comment]
> What distribution are building under?

Building on Jessie still. Would that be the cause?

FWIW, it's the same system that I built turnkey-version on previously which was reproducible.

**Comment by lamby** [comment]
@JedMeister I can't reproduce this even when building under `jessie`. Can you pastebin your entire build logs of each build? I think it might be something to do with `SOURCE_DATE_EPOCH` or simply you are using an old debhelper? (indeed, the `.buildinfo` file will canonically state which debhelper version you are using...)

**Comment by JedMeister** [comment]
@lamby 

> I can't reproduce this even when building under jessie

Hmmm... Maybe it's something to do with the TurnKey package building setup then? TBH, I have no idea how to build Debian packages. I just register the source with [pool](https://github.com/turnkeylinux/pool) and run:
```
pool-get . webmin-tklbam
```
and out pops a package...

I can't find a `.buildinfo` file anywhere, all I have is `/turnkey/fab/pools/stretch/.pool/build/logs/webmin-tklbam_1.0+26+g7bbf82f.build`. But that suggests, you are totally on the money re `SOURCE_DATE_EPOCH`!:
```
root@da-shiz pools/stretch# diff .pool/build/logs/webmin-tklbam_1.0+26+g7bbf82f.build build-1/webmin-tklbam_1.0+26+g7bbf82f.build
30c30
< 	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521169778}"
---
> 	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521093396}"
```

So it looks to me that the issue is our package building tool(s)!

Following your suggestion re `debhelper`, I checked and was using `9.20150101+deb8u2`. So I upgraded to the package in `jessie-backports`; `10.2.5~bpo8+1`. But that didn't seem to make any difference:

Build#5 excerpt: `xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521174085}"`

Build#6 excerpt: `xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521174116}"`

Full output for Build#5 & Build#6 are here: https://pastebin.com/BpZUUy6H Build#6 starts at line 89.

Unfortunately, I don't know enough about it all to know where to start looking next. I initially did a recursive grep of `/usr` in the hope that might turn it up there, but no joy. So I've got a recursive grep of `/` running now to see if I can find out where that's coming from, but it's been running ages already and I've got nothing yet...

I'll reassign this to myself for now and liaise with @alonswartz on fixing it. Unless of course, if you have any further suggestions or input, please share...

**Comment by JedMeister** [comment]
@lamby 

I found it! It's in the [`Makefile`](https://github.com/turnkeylinux/webmin-tklbam/blob/master/Makefile#L7).

Obviously I know nothing about reproducable builds, but makes me wonder how you could be getting a reproducible build with that in the Makefile?!

**Comment by lamby** [comment]
> makes me wonder how you could be getting a reproducible build with that in the Makefile?

'Fraid I don't follow that, sorry. That's actually written like that to be reproducible...

And I should have clarified re `SOURCE_DATE_EPOCH` - I already knew of that reference in the aforementioned `Makefile`, the problem is that the environment variable is either not being exported correctly (it is read from the most recent entry in `debian/changelog`) **or** because you are artificially generating a `debian/changelog` file each time you run the build (because you don't have them in the packages...) you are getting a new value each time.

Indeed, have a look here where — I think — we set the value:

  https://github.com/turnkeylinux/verseek/blob/master/pylib/verseek.py#L223

This is likely to be the culprit tbh.

**Comment by JedMeister** [comment]
@lamby 

Now I'm really confused... :confused: 

I just set a [static timestamp in the Makefile](https://github.com/JedMeister/webmin-tklbam/commit/3ef465bf97fbdea6e5e81d787d86584614ef029f) (just trying to make it reproducible as PoC before we work out the way to properly fix it) and it's still not reproducible?!
```
root@da-shiz pools/stretch# shasum build7/webmin-tklbam_1.0+27+g3ef465b_amd64.deb 
17ac0191c1d631c57186941060b608397d1e4937  build7/webmin-tklbam_1.0+27+g3ef465b_amd64.deb
root@da-shiz pools/stretch# shasum build8/webmin-tklbam_1.0+27+g3ef465b_amd64.deb 
8fc37983a784180809be30ade88a7c2e4ec581a2  build8/webmin-tklbam_1.0+27+g3ef465b_amd64.deb
```

Full log of build7: https://pastebin.com/SnZvcLGA

Full log of build8: https://pastebin.com/YEMzArUW

As you can see, the logs now appear to be identical!?!

**Comment by JedMeister** [comment]
Oops, missed your response... 

> Indeed, have a look here where — I think — we set the value:
>
> https://github.com/turnkeylinux/verseek/blob/master/pylib/verseek.py#L223
>
> This is likely to be the culprit tbh.

Ahhhh! I think you're right...

**Comment by JedMeister** [comment]
@lamby - any suggestions on fixing that?

**Comment by lamby** [comment]
@JedMeister Before we "fix" anything the next thing to do would be to confirm that this is actually the problem, surely? :)  Can you add to your Makefile something like `cat debian/changelog` and perhaps even `echo $(SOURCE_DATE_EPOCH)`? That way we can see whether the changelog date is changing and what effect, if any, that has on `SOURce_DATE_EPOCH`.

**Comment by JedMeister** [comment]
@lamby 

> Before we "fix" anything the next thing to do would be to confirm that this is actually the problem, surely? :)

Oh ok, I suppose you're right... :wink: 

I'll let you know how it goes.

**Comment by JedMeister** [comment]
Ok @lamby - following your very sage advice, I have now confirmed that is the issue!

To test, I added the below to the Makefile:
```
       cat debian/changelog
       ls -l debian/changelog
       echo $(SOURCE_DATE_EPOCH)
```

And here's what I got:
```
cat debian/changelog
webmin-tklbam (1.0+27+g423242c) UNRELEASED; urgency=low

  * undocumented

 --  Liraz Siri <liraz@turnkeylinux.org>  Mon, 19 Mar 2018 17:39:36 +0000
ls -l debian/changelog
-rw-r--r-- 1 build build 149 Mar 19 06:49 debian/changelog
echo 1521481176
1521481176
```

FWIW: `date +%s --date="19 Mar 2018 17:39:36 +0000"` = `1521481176` 

I'm guessing that the timestamp of the file `Mar 19 06:49` is due to the adjustments you made to the `Makefile` right? Although it doesn't seem to quite match from my calculations.

Also apologies on my silly statement previously re 
> makes me wonder how you could be getting a reproducible build with that in the Makefile?

Jumping to wild conclusions again...

**Comment by lamby** [comment]
> > Can you add to your Makefile something like cat debian/changelog and perhaps even echo $(SOURCE_DATE_EPOCH)?

Please can you run *two* builds and pastebin the output? The idea here was to see whether the contents vary across builds, not necessarily to know the contents (I can pretty much guess the outline from reading the `verseek` code as [mentioned previously]( https://github.com/turnkeylinux/tracker/issues/1028#issuecomment-373603706)).

**Comment by JedMeister** [comment]
Hmmm, ok... Here's the diff:
```
user@ninjux turnkey/reproducible$ diff A/log B/log
52c52
< -rw-r--r-- 1 build build 149 Mar 19 06:49 debian/changelog
---
> -rw-r--r-- 1 build build 149 Mar 19 19:54 debian/changelog
56c56
< 	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521442195}"
---
> 	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521489273}"
```
And the full logs are here:

A: https://pastebin.com/JTVB6phA
B: https://pastebin.com/v8gq59YF

And finally the diffoscope:
https://try.diffoscope.org/gzdgkexhufaf.html

**Comment by lamby** [comment]
Hey @JedMeister, thanks for that. Indeed, not jumping to conclusions and being skeptical is often the best way to deeply understand and fix the issue in my experience, but that could just be me!

Okay, can you:

a) Run this again and add a call to `env` by the `cat debian/changelog` and pastebin the two builds. I think we aren't actually getting `SOURCE_DATE_EPOCH` exported….

b) .. which is likely due to to a missing `include /usr/share/dpkg/pkg-info.mk` in the `debian/rules`. Can you run it (seperately to **a)**) and pastebin the result? (This might actually be reproducible, we'll see..)

ps. Oh just FYI, I would use `diff -urNad` instead of plain `diff` :)  In particular, that's to specify the `-u` (unified) option; the "old style" diffs aren't that great!

**Comment by JedMeister** [comment]
> Indeed, not jumping to conclusions and being skeptical is often the best way to deeply understand and fix the issue in my experience, but that could just be me!

It's good advice! And I'm sure @lirazsiri would agree with you! :wink: [Ages ago when I first started with TurnKey he was coaching me asynchronously on the inner workings of TKL. The poor guy was often pulling his hair out due to the silly conclusions I'd jump to and the ensuing rabbit holes I'd end up wasting time going down].

It's certainly something I'm often guilty of. At times, it's served me quite well and saved lots of time, especially as I've come to learn about common SysAdmin issues users hit with TurnKey. I have been lucky enough to often short circuit issues, even when users rarely provide enough info to make a proper diagnosis. But with more detailed and less common software development issues (especially when I don't really understand what is going on under the hood), well, not so much...! :smile: 

So it's good to be reminded to step back a bit and just take a few deep breaths! Thank you for your patience with me. Whilst I'm cognitively aware of this particular shortcoming, it's such a deeply entrenched habit, I often forget. Especially when I'm in the thick of it and just want to get stuff completed (this is the final piece of the puzzle before we build and release the v15.0RC of Core).

----
Anyway, back on topic:
**a)** 

changes to code: https://github.com/JedMeister/webmin-tklbam/commit/7106f17ec45127c2cb0357765a71023ccf453d83
```
user@ninjux turnkey/reproducible$ diff -urNad a1/log a2/log
--- a1/log	2018-03-20 13:55:33.950111465 +1100
+++ a2/log	2018-03-20 13:57:00.888043665 +1100
@@ -110,7 +110,7 @@
 echo 1521553360
 1521553360
 find tklbam -print0 | \
-	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521513995}"
+	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521514575}"
 find tklbam -print0 | LC_ALL=C sort -z | \
 	GZIP=-9n tar --no-recursion --null --files-from=- -czf tklbam.wbm.gz
 make[1]: Leaving directory '/home/build/webmin-tklbam-1.0+28+g7106f17'
```
Full logs:
a1: https://pastebin.com/r3Jtc3at
a2: https://pastebin.com/efDYSyxz

diffoscope (probably not required or useful): https://try.diffoscope.org/ahhkkyaptvey.html

----
**b)**

changes to code (reverted above changes first as requested): https://github.com/JedMeister/webmin-tklbam/commit/73b8d4b3abd8dc8f9cf1fb22b46b4ec118f2e412
```
user@ninjux turnkey/reproducible$ diff -urNad b1/log b2/log
--- b1/log	2018-03-20 14:57:55.424225502 +1100
+++ b2/log	2018-03-20 15:14:40.886845274 +1100
@@ -49,11 +49,11 @@
 
  --  Liraz Siri <liraz@turnkeylinux.org>  Tue, 20 Mar 2018 14:01:00 +0000
 ls -la debian/changelog
--rw-r--r-- 1 build build 149 Mar 20 03:42 debian/changelog
+-rw-r--r-- 1 build build 149 Mar 20 03:51 debian/changelog
 echo 1521554460
 1521554460
 find tklbam -print0 | \
-	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521517348}"
+	xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH:-1521517898}"
 find tklbam -print0 | LC_ALL=C sort -z | \
 	GZIP=-9n tar --no-recursion --null --files-from=- -czf tklbam.wbm.gz
 make[1]: Leaving directory '/home/build/webmin-tklbam-1.0+30+g73b8d4b'
```
Full logs:
b1: https://pastebin.com/0qDsKR9y
b2: https://pastebin.com/L5aZH4SJ (sorry about the first few chars of the first line missing, but it shouldn't matter I wouldn't think?!)

diffoscope: https://try.diffoscope.org/qyxfatcrgsxx.html

----

I think that's all you asked for...

**Comment by JedMeister** [comment]
@lamby Forgot to mention you in the above post and I don't think adding a mention to an edit will work...

**Comment by lamby** [comment]
> rabbit holes I'd end up wasting time going down

I think that's what could be considered frustrating - as in, I can see you are obviously keen yet from a distance it feels a tragedy to unecessarily waste this time and attention!

re. adding `env` — it shows that `SOURCE_DATE_EPOCH` envvar is indeed being exported. (The varying part of the log is just the fallback code running).

re. the second commit, you removed the `env` so we wouldn't have been able to see the difference! No matter, as the first diff showed it was being exported correctly.  My bad re "separately" being a bit ambiguous :)

So the question now is why is the call to `find | touch` not working. Can add `find -ls` here: https://github.com/JedMeister/webmin-tklbam/blob/master/Makefile#L10 (line 10)

You could also probably try replacing the `$(CONTENTS)` in the *first* `find` call with `.`...

**Comment by JedMeister** [comment]
Apologies on slow response. I had day surgery yesterday and spent what was left of the day in bed. I'm going ok this morning, but a little bit wobbly so I'll probably just get this done and head back to bed...

> My bad re "separately" being a bit ambiguous :)

I perhaps interpreted it a little too literally! :smile: 
----

I'm not really sure what is going on, but this morning it seems to be reproducible?! The only thing I can think is that I must have uploaded the wrong packages to diffoscope (despite being sure that I also did an `shasum` on them?!).  It appears that the addition to `debian/rules` did the trick! 

FWIW:

First up I followed your instructions re adding `find -ls` (plus reinstated the `env` for good measure - see [here](https://github.com/JedMeister/webmin-tklbam/commit/f030ccd3c349a8209f84c7c55baf0131e3732c78)) and it was reproducible:

```
root@da-shiz pools/stretch# shasum a1/webmin-tklbam_1.0+31+gf030ccd_amd64.deb a2/webmin-tklbam_1.0+31+gf030ccd_amd64.deb 
b39de0ffdb7ce8a7d7b64ecb635c1f45b0ff49de  a1/webmin-tklbam_1.0+31+gf030ccd_amd64.deb
b39de0ffdb7ce8a7d7b64ecb635c1f45b0ff49de  a2/webmin-tklbam_1.0+31+gf030ccd_amd64.deb
```

A bit weirded out, I then rebranched off master and reapplied the tweak to `debian/rules` (i.e. [this](https://github.com/JedMeister/webmin-tklbam/commit/afb234691e3c2f8e51277edfd5e6432fbb85eb14)) and yep, that did it...:

```
root@da-shiz pools/stretch# shasum b1/webmin-tklbam_1.0+27+gafb2346_amd64.deb b2/webmin-tklbam_1.0+27+gafb2346_amd64.deb 
fc16cd5b2de4f0512a106aa3795de6fcd842333b  b1/webmin-tklbam_1.0+27+gafb2346_amd64.deb
fc16cd5b2de4f0512a106aa3795de6fcd842333b  b2/webmin-tklbam_1.0+27+gafb2346_amd64.deb
```

So I think we're done... I still have the packages and logs if you want any additional info just to be sure,  spo let me know if you want that posted. But otherwise, I think we're done here... 

It seems I just needed a local aesthetic and some pharmaceutical painkillers to make it work... :roll_eyes: 

Thanks again for your guidance and patience. Closing...

**Comment by lamby** [comment]
I fear you might be being to hasty again. :) You claim that we need the `pkg-info.mk` export to make it 
reproducible, but if we fix the build process (perhaps in `verseek`) we would not need such hacks which were mostly suggested as debugging aids. Also, I suspect that `verseek` is not reproducible with respect to timezones. eg. try building the **b** build with, say, TZ=UTC in front of it. (Also, perhaps I'm misreading but you also say that. adding `find -ls` made it reproducible too? But that's surely debugging code..?)

**Comment by JedMeister** [comment]
> I fear you might be being to hasty again. :)

not again... :roll_eyes: 

> You claim that we need the pkg-info.mk export to make it
reproducible, but if we fix the build process (perhaps in verseek) we would not need such hacks which were mostly suggested as debugging aids. 

Again, due to my lack of understanding of what is going on... I mistakenly thought that it was required (i.e. an oversight on your behalf that it hadn't been previously included). I missed the point that it was a debugging aid...

So, I'll now slow right down and completely defer to your expertise... Have we sufficiently debugged the issue to the point that we can now patch `verseek`? If so, do you have a suggestion on what we should do with it? 

Reopening...

**Comment by JedMeister** [comment]
PS
> Also, perhaps I'm misreading but you also say that. adding find -ls made it reproducible too? But that's surely debugging code..?

Sorry if I didn't explain myself sufficiently or clearly enough. It was the tweak (hack?) to `debian/rules` that made it reproducible. I'm fairly sure that the reason it wasn't reeproducible when I first implemented that was due to my error (uploading the wrong packages?). I'm not 100% sure on that, but it seems the only realistic conclusion as once I had removed all the other code and just included `pkg-info.mk` in the Makefile, it was reproducible. 

If nothing else, this somewhat painful endeavour makes it clear to me that I need to learn more about makefiles and Debian packaging...

**Comment by lamby** [comment]
> So, I'll now slow right down and completely defer to your expertise... Have we sufficiently debugged the issue to the point that we can now patch verseek? If so, do you have a suggestion on what we should do with it?

The reason why including `pkg-info.mk` works is because that file deliberately and explicitly exports `SOURCE_DATE_EPOCH`. It was essentially the same as a "test" that did `export SOURCE_DATE_EPOCH=42` :)  However, this shouldn't really be necessary and is a little tedious to do in every package. Regarding where we should do it.. perhaps not `verseek` per se, but it seems sensible that as we are using `verseek` to generate the `debian/changelog` file (which still might not be reproducible with respect to timezones; IIRC it was using a naive `datetime.datetime` with `%a` or similar...) then it is reasonable to do somethig globally.. perhaps the `pool-get` should be exporting this? I can't really say as I've regrettably not had to use this yet :)

> If nothing else, this somewhat painful endeavour makes it clear to me that I need to learn more about makefiles and Debian packaging...

Not *necessarily* I mean, this is really "in the weeds" with respect to exporting variables that are quite new, and some of the toolchain doesn't so it, etc. It's not "general" (and thus more useful) knowledge. Still, a basic understanding of **Make** is always useful! :)

**Comment by JedMeister** [comment]
Hmm, ok. Thanks for the additional info. I did actually start a "normal" (i.e. waffley) reponse late last week, but I obviously didn't click "Comment". Oh well, nothing significant lost I'm sure...

I know this is a dirty hack, but what about just adding that env var (i.e. `SOURCE_DATE_EPOCH=42`) it to the buildroot `/etc/profile`? It should be enough to get us over the line. Obviously it's not a proper fix, but it does workaround the issue, without requiring any significant work right now (and no additions to any of the individual package code). So long as it's included in our official stretch buildroot and all our packages are built against that, then it should give consistent results (not withstanding your note about TZ - although that could be worked around in a similarly hacky way I'd assume).

I'll speak about it with @alonswartz (I'll be speaking with him later tonight my time) but would also be interested in your thoughts. Even if we just do that for the moment so that we can build the packages and upload them, then so long as we always set `SOURCE_DATE_EPOCH=42` in some way, shape or form then it should give the same results right?

FWIW I just did a test build (from `webmin-tklbam` - `master`) and it works fine (I already did the initial clean up, checkout etc prior to this to avoid having to be too verbose):
```
root@tkldev buildroots/stretch# echo "export SOURCE_DATE_EPOCH=42" > etc/profile.d/reproducible-hack
root@tkldev buildroots/stretch# chmod +x etc/profile.d/reproducible-hack
root@tkldev buildroots/stretch# cd /turnkey/public/webmin-tklbam
root@tkldev public/webmin-tklbam# gb -av | grep master -m1
* master                                  7bbf82f Merge branch 'bugfix' - make webmin-tklbam compatible with Webmin v1.880
root@tkldev public/webmin-tklbam# cd pools/stretch/
root@tkldev pools/stretch# mkdir a1 a2
root@tkldev pools/stretch# pool-get a1 webmin-tklbam
### BUILDING PACKAGE: webmin-tklbam=1.0+26+g7bbf82f
[...]
root@tkldev pools/stretch# rm .pool/pkgcache/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
root@tkldev pools/stretch# pool-get a2 webmin-tklbam
### BUILDING PACKAGE: webmin-tklbam=1.0+26+g7bbf82f
[...]
root@tkldev pools/stretch# shasum a1/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb a2/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
3380db9b30a0e917b0e27b550b172b5cd28e53cb  a1/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
3380db9b30a0e917b0e27b550b172b5cd28e53cb  a2/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
```

**Comment by JedMeister** [comment]
@lamby one little bit more on this...

> which still might not be reproducible with respect to timezones; IIRC it was using a naive datetime.datetime with %a or similar...

FWIW, it looks like the buildroot TZ is `UTC` (as I was expecting):
```
root@tkldev ~# fab-chroot /turnkey/fab/buildroots/stretch date +%Z 
UTC
```

Would that ensure that the timezone wasn't an issue (so long as it remains unset)? Or is it passed through from the host?
```
root@tkldev ~# date +%Z 
AEDT
```
I guess I could run some tests and find out myself, but I've got other stuff that I really need to get onto and I'm assuming you'd know OTTOYH, if not, no worries.

**Comment by lamby** [comment]
> what about just adding that env var (i.e. SOURCE_DATE_EPOCH=42) it to the buildroot /etc/profile?

Sorry I'm really confused now. There is absolutely zero need to do this and it is unspeakably ugly... :(  As mentioned, we can surely correctly and set `SOURCE_DATE_EPOCH` from the `debian/changelog` entry; I mean, we are already parsing the value from the Git repository in `verseek` so that's clearly the way to get a canonical date for the source, so we can modify the build process to do `export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)`. Or just import `pkg-info.mk` everywhere we don't already to do it further down the chain.

> FWIW, it looks like the buildroot TZ is UTC (as I was expecting):

.. then that somewhat papers over the problem, but it's at least already in the chroot; in other words, nobody will be able to reproduce your packages unless they also build with `TZ=UTC` — I just checked `verseek` and given its usage of `datetime.fromtimestamp` instead of `utcfromtimestamp` etc. this would be required)

**Comment by JedMeister** [comment]
@lamby - thanks for your patience with me on this issue (and in general... :smile:). I apologise for my (ongoing) jumping to conclusions and other sub-optimal responses. In case you haven't noticed, it's doing my head in a bit too. I feel that my ongoing frustrations are compounding the issue.

So I'm going to step aside a little as it seems that I'm just muddying the waters and not getting us any closer to a solution. I'm pulling @OnGle in to look into this further (FWIW he's a "proper" programmer so hopefully will make some more sense to you! :wink: ) and once we have some more info one of us will post back.

**Comment by lamby** [comment]
@JedMeister  Oh.. I'm sorry to hear you're giving up :(  Do let me know if I could have been clearer anywhere, but I don't understand why we don't just add pkg-info.mk for this to get the environment export or we patch the build system (eg. something like https://gist.github.com/lamby/7d051f2a8e64cef1aba4631f95696e82/raw, utterly untested). I was just very very confused by your `/etc/profile` idea when we already had solutions...

**Comment by JedMeister** [comment]
@lamby I guess I am "giving up", although it doesn't really feel that way. TBH I'm just not convinced that I'm the best person to push on with this (and I have a ton of other unrelated stuff that I also need to take care of). Besides, Alon is always encouraging me to push anything I can off to others. So this choice is consistent with his desire for me to focus on what only I can do, and the areas where I excel (clearly not "bug-hunting reproducible package issues"! :stuck_out_tongue:).

FWIW the piece of info which I didn't share in my earlier post this morning (and was a significant part of me deciding I needed to hand over), was that after having reverted to master of webmin-tklbam (and removing the `/etc/profile` hack from the buildroot) the package continued to be reproducible!?! (WTF eh?!?) In fact the checksums, still matched the ones from yesterday (produced with the `/etc/profile` hack). So I'm not even sure that was the issue! 

TBH, If I didn't have a record of mismatched shasums (particularly the [OP](https://github.com/turnkeylinux/tracker/issues/1028#issue-305768760)), I'd be wondering if I had been dreaming it all along!

I'm completely flummoxed by this latest scenario. It makes no sense at all to me. Perhaps my TKLDev instance (which is running as a KVM VM) was suffering from time drift or similar? Perhaps some intermittent bug (which is not currently occurring)? Or perhaps just plain old human error (I'd like to think not considering my persistently inconsistent outcomes, but who knows?).

Having said that, to make the packages reproducible across systems (i.e. on @OnGle's TKLDev machine) I did have to set my host timezone to UTC (from AEDT; his was UTC). He has since done further testing and confirmed that the timezone of the host system affects the shasum of the package being built. We haven't tested the TZ of the buildroot; we both have the default UTC but will test further to be certain. So we have at least confirmed that is a bug in our build system, which needs addressing anyway.

The other advantage of getting him to work on it, is that as I noted, he's a programmer. He is less familiar with TKL tools than I am, but probably more so than you. Armed with this thread, especially the info/suggestions you've shared, plus real-time access to my knowledge, I suspect it'll be much quicker and easier for him.

Regardless, I really appreciate your input and assistance with this and apologise for this latest weird update to the saga that is "making `webmin-tklbam` reproducible"!

**Comment by OnGle** [comment]
Alright for the moment I'm going to focus entirely on the timezone issue as it's the only one I've been able to reproduce. This may of already been mentioned but I'll reiterated. Verseek contains the code to generate the changelog and parse timestamps from git however both the changelog generating code and the timestamp parsing are done without specifying any timezone as such it defaults to using the host timezone.

It appears to me there are 2 specific timezone issues preventing reproducible builds.
 - when parsing the git commit information it grabs the timestamp but not the offset (and git may specify it's timestamps at any valid offset)
 - git commit information seems to only contain offset and not TZ information. If this is the case then that makes accurate conversions impossible (accounting for daylight saving time for example)
 - when parsing the git commit timestamp it doesn't specify a timezone making the datetime object naive (unable to perform tz conversions)

**Comment by OnGle** [comment]
1 dirty fix is to pretend the date read from git is always in UTC even though it isn't and never apply any modifications to it (as I believe @lamby  mentioned earlier with `utcfromtimestamp`). This will provide an incorrect but reproducible date.

Barely worth a PR, but with this change I no longer experience unreproducible builds in different timezones https://github.com/turnkeylinux/verseek/pull/3. 

You could even change the `_get_commit_datetime` function to match the offset aswell as the timestamp and then pass that to `_create_changelog` so it gets written in the `strftime` line instead of the static `+0000` afaik that should make it the correct time.

Any thoughts @lamby?

**Comment by JedMeister** [comment]
The underlying issue causing TurnKey infrastructure to build non-reproducible packages, should now be resolved - as of the merge of https://github.com/turnkeylinux/verseek/pull/3.

Big thanks to:
- @lamby - for your guidance and patience as much as anything else...!
- and @OnGle - for jumping in and doing the work.

Great work guys! :clinking_glasses:
