### ISSUE TITLE
pre-seeding LXD (LXC2) containers with systemd (15.0-stretch)

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#1035]
Pre-seeding 14.x-jessie containers works as expected.
```
lxc init {image} {container}
lxc push inithooks.custom {container}/etc/inithooks.conf
lxc start {container}
```
wait for container to initialize ...
On version 15.0-stretch containers, however, the container never initializes and I have to manually run turnkey-init
```
lxc exec {container} -- turnkey-init
```
I think it has something to do with the way systemd is being configured in the container. 
How does turnkey-init get started during firstboot when systemd is installed?

**Comment by JedMeister** [comment]
I've tagged `container (build type)` as I suspect this may also effect our LXC builds as well as LXD (if you suspicions regarding SystemD are correct, it almost certainly will). I've also tagged `core` (rather than tag all appliances).

I haven't fully checked in a running appliance (I haven't built anything other than ISOs for v15.0) but the Stretch version of the inithooks package provides both a [init.d script](https://github.com/turnkeylinux/inithooks/blob/master/debian/inithooks.init) and a [SystemD service file](https://github.com/turnkeylinux/inithooks/blob/master/debian/inithooks.service).

Are you building v15.0 containers with buildtasks? If so, then unless you've updated it, it would still be be removing SystemD and installing SysvInit. So perhaps it will "just work" when we switch back to using SystemD? (I.e. remove the code that removes SystemD). We only did that to work around a SystemD bug that was present in Jessie. I'm almost certain that that issue no longer exists in Stretch.

AFAIK SystemD allows much more granular control of what runs when, so hopefully we should be able to tweak that to work as required?!

At this point, my intention is to look at all the "alternate"/"optimised" builds once we have a v15.0RC Core ISO released, so I can have a closer look at this then. In the meantime, if you'd like to have a look at the [`bt-container`](https://github.com/turnkeylinux/buildtasks/blob/master/bt-container) script in [buildtasks](https://github.com/turnkeylinux/buildtasks) then that'd be awesome. Also if there will be significant changes to that code to provide LXD builds, then perhaps we should create a new buildtasks script `bt-lxd` script?!

As something of an aside, we should probably rename that current buildtasks script to either `bt-lxc` or perhaps `bt-proxmox` (seeing as that is technically what it's targeted at, and would bring the script name into line with the download directory: http://mirror.turnkeylinux.org/turnkeylinux/images/proxmox/). But that's not a huge priority.

All thoughts and feedback are welcome! :smile:

**Comment by JedMeister** [comment]
Apologies that I haven't explicitly responded to this sooner @Dude4Linux. I'm pretty sure I've now noted most (if not all) of this elsewhere, but for completeness, I'll respond here too.

As you'd be aware, since you posted, `stretch-dev` has now been merged into master. Ideally I would have liked to keep working in a dev branch until v15.0 was ready, but the current limitations of our build infrastructure demand building from the master branch only. As such, please note that there are a number of commits prefixed with `TEMP:` which will be cleaned up prior to the final v15.0 release.

Since digging into the `container` build (testing on Proxmox v4.x), I think that there are actually a few separate issues related to your initial experience. You may not have hit all the ones I'm seeing as you are working with a newer version of LXC, plus I'm also not 100% sure whether you are also apply the headless patch (as we do in buildtasks)? Regardless, it seems that they can be resolved without affecting other builds, so I intend to resolve them at their source.

As they are separate issues, I'll break them out into their own individual issues here on the tracker. For reference, the issues I've hit are:

1. the systemd `service` file failing. As already discussed in #1071 (no new issue required).
2. a weird edge case inithook bug in `10regen-sshkeys`. New issue #1085
3. another edge case inithook bug in `29preseed` (added by the [`headless` patch](https://github.com/turnkeylinux/buildtasks/blob/master/patches/headless) in [`buildtasks`](https://github.com/turnkeylinux/buildtasks)). New issue #1086
4. initfence not starting (or perhaps just really slow starting) - already noted #1079

I'll close this issue now. Anything else contained here and not covered/addressed elsewhere is ripe for it's own individual issue. Please feel free to open new specific issues for anything I've missed.
