### ISSUE TITLE
Drupal 8.4.x requires Drush 9.x; Drush9.x no longer supports global install (must be site specific)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1036]
Argh, this has been doing my head in all afternoon...

It appears that in the 8.4.x update of Drupal, some new dependencies (that break earlier versions of Drush) are required... Namely a new version of Symfony...

And Drush 9.x no longer supports a global install, and now instead needs to be installed per site (from what I can gather anyway...). 

So it looks like we need to change the way that the Drupal8 appliance is built... :cry: 

From my (far from expert) eye, it seems that the new suggested way to [install Drush](http://docs.drush.org/en/master/install/) is to [install Drupal via Composer](https://github.com/drupal-composer/drupal-project) and simply make Drush one of the Drupal site's dependencies...

To allow global use of Drush, it is recommended to install [drush-launcher](https://github.com/drush-ops/drush-launcher). 

@spaghettimaster - are you able to have a look at this ASAP?

**Comment by JedMeister** [comment]
Hey @spaghettimaster - thanks for adding this to your backlog. I just realised that 8.4.x is EOL and the current release is 8.5.1. You probably already worked that out, but just in case, thought I'd note it...

**Comment by bormanst** [comment]
Modern editors ;)

The module list is supposed to have the line continuation char "\" at the end of each line

DRUPAL_MODULE_LIST="\\
drupal/advagg \\
drupal/advanced_help \\
...
...
drupal/zen \\
"

**Comment by JedMeister** [comment]
Awesome thanks @bormanst !

Out of interest, have you come across any good tutorials (or do you have any documentation) for upgrading a v14.2 Drupal8 appliance to Drupal 8.5.x? I'm currently writing up a security related blog post on the Drupal7/8 security issue and would really love to include instructions for upgrading Drupal8. Drupal7 is easy, but upgrading Drupal 8.3.x; not so much...

**Comment by bormanst** [comment]
I have not done such an upgrade, but the pain and ecstasy of moving to composer is that this is supposedly easily done:

https://www.drupal.org/docs/8/update/update-core-via-composer
https://www.drupal.org/docs/develop/using-composer/using-composer-with-drupal

Since the above conf.d method uses composer to install the base directory, a pristine composer.json is generated and can be easily upgraded by bash composer commands.

The file is not intimidating. If the original installation was not created with composer then I'm guessing that it is probably possible to manually alter or generate a composer.json file that is specifically tailored to the desired configurations/versions and then perform the bash composer commands using the tailored file. A lock file may be present that prevents manually altering the target json file which means the bash composer commands should be used for modifications.

If you have the time to burn then try the above conf.d partials and do a build:

1) DRUPAL_SPEC=^8.0 >> DRUPAL_SPEC=8.3.x or any existing designated version. The ^8.0 means any version 8.0 up to but not including 9.0 whereas setting it only = forces the desired version.
2) The DRUSH_SPEC=^8.0 may have to be modified accordingly as well.
3) Then modify DRUPAL_MODULE_LIST to existing modules. Don't forget that version 8 has some modules already built into the core.
4)  Do a build.

You will get your desired base composer.json file in the base drupal8 directory which can be manually modified accordingly and presented to users as a use case example.

FWIW

**Comment by JedMeister** [comment]
@bormanst - Awesome, thanks for the pointers. I will include a link to your comment in the blog post. I'm quite close to publishing it, so your timing is impeccable! Thanks again! :smile:
