### ISSUE TITLE
Etherpad should be dropped (or atleast shelved)

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1132]
**[Update by @jedmeister]** Things have been progressing substantially for Etherpad. I suggest that we should release a v15.0 Etherpad applaince, including [Etherpad 1.7.0](https://github.com/ether/etherpad-lite/releases/tag/1.7.0).

----

The etherpad-lite project no longer has a project leader and many of it's listed dependencies have security vulnerabilities, some of which cannot be resolved due to breaking changes in the fixes and/or prior updates.

**Comment by JedMeister** [comment]
Thanks for this @OnGle - I was planning to drop it for v15.0 and also do an announcement and pull all copies of it from the mirror and AWS etc. 

However, I just noticed that there appears to be a flurry of activity on the repo! Lots of dependencies have been updated in the dev branch by the looks: https://github.com/ether/etherpad-lite/commits/develop Also, there have been a few recent releases: https://github.com/ether/etherpad-lite/releases

Perhaps we should reconsider/re-evaluate?

**Comment by OnGle** [comment]
From my cursery look things look like they're in flux and there's quite a few open issues at this point in time. I think we should maintain the buildcode at least through 15.1 although I'm leaning towards not releasing a 15.0 version of this appliance. Thoughts @JedMeister?

**Comment by JedMeister** [comment]
Hmm, yeah it seems like the activity has not continued (at least not regarding commits). As you say, there are still plenty of open issues... Now that the appliances don't all need to be the same version, we can simply hold off on a v15.0 release of Etherpad...

**Comment by muxator** [comment]
Hi,
I acknowledge the problem. A solution will take time.

For the upcoming Etherpad release (**1.7**), we cannot do much more than improve the documentation, suggesting using `ep_hash_auth` (https://github.com/ether/etherpad-lite/issues/3444, commit https://github.com/ether/etherpad-lite/commit/10f0cb325304c15808015dba97dbf35a790898a8).

On the other side, ep_hash_auth has [its usability issues](https://github.com/LaKing/ep_hash_auth/issues/2), and I do not feel it would be wise integrating it in its current form.

A definitive solution is scheduled for [version 1.8](https://github.com/ether/etherpad-lite/milestone/11) (no ETA yet).

**Comment by JedMeister** [comment]
Hi @muxator - Thanks tons for dropping in. I really appreciate it. Perhaps I should have reached out directly previously? Anyway...

Are you effectively the Etherpad project lead now? Or a super active community member leading by example? Or ...?

Regardless, assuming inclusion of `ep_hash_auth`; do you consider Etherpad "production ready"? (Thanks to for the link re install difficulties - just in case we have any troubles).

Bottom line is that I'd really love it if we could continue to offer a TurnKey Etherpad appliance. It's super cool software and there currently isn't really anything like it (at least not in the open source self-hosted space that I'm aware of). OTOH, our users have an expectation that our appliances are secure and that they "just work". So I'm not super keen if we can't meet both of those aims.

**Comment by muxator** [comment]
Hi, @JedMeister.

> Are you effectively the Etherpad project lead now?

yours truly :)

I have started taking care of the project since **1.6.5**, and there are a lot of community members that have been doing a very good work for years now. Release **1.7** is currently being prepared.

> do you consider Etherpad "production ready"?

Bugs keep getting discovered, but recently there were a lot of improvements:
[**1.6.4**](https://github.com/ether/etherpad-lite/releases/tag/1.6.4) and [**1.6.5**](https://github.com/ether/etherpad-lite/releases/tag/1.6.5) fixed a lot of security issues (thanks to @nashe and @JohnMcLear), **1.7** will bump a lots of dependencies (https://github.com/ether/etherpad-lite/issues/3397, https://github.com/ether/etherpad-lite/issues/3429) and [deprecate old Node versions](https://github.com/ether/etherpad-lite/issues?q=is%3Aissue+is%3Aopen+label%3Asecurity). Some difficult functional bugs were fixed (thanks @ilmartyrk and @lpagliari, respectively for [this](https://github.com/ether/etherpad-lite/pull/3268) and [this](https://github.com/ether/etherpad-lite/pull/3420)), including [one about robustness](https://github.com/ether/etherpad-lite/pull/3318) in [**1.6.6**](https://github.com/ether/etherpad-lite/releases/tag/1.6.6) (thanks @anugu-chegg).

I see a lot of points open:
- password hashes need to be integrated in the Etherpad core
- there are still some bugs, particularly in [import/export](https://github.com/ether/etherpad-lite/issues?q=is%3Aissue+is%3Aopen+label%3AExport%2FImport)
- some stale dependencies, like socket.io, will be difficult to update
- [packaging](https://github.com/ether/etherpad-lite/issues?q=is%3Aissue+is%3Aopen+label%3Apackaging) should be definitely facilitated

I think a conscientious sysadmin can put Etherpad in production, but some compensating work will be required on his side. And probably he will have upgrade to new versions as new problems are discovered.

To help you taking your decision, here is the [list of current tickets categorized under "security"](https://github.com/ether/etherpad-lite/issues?q=is%3Aissue+is%3Aopen+label%3Asecurity).




Usual final note for OSS projects: everyone works in his spare time, the community is not big, lots of work in different areas means we could use help from all kind of figures.

**Comment by muxator** [comment]
Hi @JedMeister.

In my opinion, there is a single change that could potentially cause some problems for users in 1.8-dev, but I think this does not apply to your users.

Etherpad 1.8 is going to replace the mechanism used for customizing its appearance with a parametric one (https://github.com/ether/etherpad-lite/issues/3471): if a user had put some files in `/src/static/custom`, a git update to the latest version could cause conflicts.
Since you ship a pre-made appliance, I think this is hardly your case.

The other changes currently queued are:
- an update to socket.io (https://github.com/ether/etherpad-lite/issues/3462) which solves the last remaining high impact vulnerability, as promised. The implications of the change are discussed in the link
- an improvement to PDF export via LibreOffice (https://github.com/ether/etherpad-lite/pull/3473)
- the initial steps of an effort to get rid of the necessity of chdir-ing into the Etherpad directory before starting it (it used to pollute the filesystem when CWD != <etherpad_dir>)
- tedious refactorings that try to reduce code nesting, hoping to make easier to spot coding errors & duplicate code

I hope this helps you to make your decision. Personally, I would be happy if the project had a bigger test base.

**Comment by muxator** [comment]
BTW, how old is the Turnkey Linux project?

Back in the day (circa ~2006), I remember having used a Turnkey LAMP appliance that was very useful for me. Is it the same project?

**Comment by JedMeister** [comment]
@muxator - as per always, thanks so much for taking the time to share your thoughts and give some clarity on the remaining work.

Given your input, I think we may go with 1.8-dev in our v15.0 Etherpad appliance. I'll be sure to note that it's using the 1.8-dev branch (and the specific commit we build from) plus document how to move back to the stable (master) branch for users who wish to do that once 1.8-stable is released (moving back to 1.7 stable is probably possible, but doubt I'll bother documenting that).

> Personally, I would be happy if the project had a bigger test base.

I can't provide any promises on how much value we might actually add but hopefully some... :smile: 

> BTW, how old is the Turnkey Linux project?
>
> Back in the day (circa ~2006), I remember having used a Turnkey LAMP appliance that was very useful for me. Is it the same project?

Yep, that'd be us I reckon. I've been involved since circa 2008 (as a community volunteer initially) and IIRC TurnKey hadn't been going for more than a year when I first started helping out, but what's a year or 2 between friends?! :smile: 

FWIW I quit my day job and joined TurnKey full time 3-4 years ago now.

**Comment by OnGle** [comment]
I'm closing this issue, the state of the etherpad project has changed considerably since I opened this issue and I find it highly unlikely we will be dropping etherpad now.

**Comment by JohnMcLear** [comment]
Thanks for handling @muxator & @JedMeister
