### ISSUE TITLE
Symfony appliance: ACLs activated by default to support best practice for Symfony's cache/log dir permissions issue

### ISSUE THREAD

**Issue by headrevision** [turnkeylinux/tracker#114]
The best practice (by Symfony) to avoid the file permissions issue for directories `app/cache/` and `app/logs/` is to use utility `setfacl` in Ubuntu (see http://symfony.com/doc/current/book/installation.html#configuration-and-setup section "2. Using Acl on a system that does not support chmod +a" in the box "Setting up Permissions")

For that you have to install the `acl` utilities and adapt your `/etc/fstab` (see https://gist.github.com/headrevision/6687065). Can we do that for the Symfony appliance?
##

**Comment by DocCyblade** [comment]
I am testing Symfony build, is there any reason why this has not been implemented in v14? Did some good reading here (https://wiki.debian.org/Permissions) I think this could be added by adding acl package during the build, then modify the /etc/fstab on first boot. However not sure with the new systemd change with jessie how that effects /etc/fstab. 

We would also on first boot need to somehow change the fstab, then remount the filesystem so acl is active. Maybe have some kind of console app that you can run in order to setup acl for the web/cache.

The other option is to just use su and change to the when running console commands.

Thoughts from anyone else?

**Comment by JedMeister** [comment]
TBH I have no idea about this. But on face value it seems like an ok idea. And obviously upstream recommend it.

Maybe there's merit to it being applied further? 

Bottom line is that if you can get it working nicely then we'd certainly add it.

**Comment by DocCyblade** [comment]
Ok,I will test the current build and if time permits I'll see if I can wrestle this in

**Comment by JedMeister** [comment]
Cool. See how you go... :smile:

**Comment by JedMeister** [comment]
I'm repinning this to v14.2 for now, but @DocCyblade (or anyone else) if you get time and want to have a look at this for v14.1 please post and I can change it back...

**Comment by JedMeister** [comment]
Because of our different build targets (which may or may not support acls) we can't implement it everywhere, so perhaps a confconsole plugin to enable this? That could really easily be disabled in the irrelevant builds. Another idea is an inithook. Either way I'm shifting this to v15.0.

**Comment by JedMeister** [comment]
Any thoughts on this @spaghettimaster?

**Comment by JedMeister** [comment]
Moving this to v15.1 for now.

**Comment by JedMeister** [comment]
Ok, so I've just had a closer look at this. Sorry it's taken so long...

It seems that the reason why Symfony notes the use of ACLs (FWIW, the [location of the doc has moved here](https://symfony.com/doc/current/setup/file_permissions.html)) are to work around an issue where the webserver user and the logged in user may be different (as they almost always would be on TurnKey).

So this is essentially this is addressing a larger problem that affects TurnKey generally.

The [recommendations from Symfony](https://symfony.com/doc/current/setup/file_permissions.html) are:

1. ACLs - Unfortunately ACLs aren't an option that we can apply across the library as some builds (e.g. LXC/Proxmox) do not support file system ACLs so an alternate option makes sense.
2. Same CLI user as web server - This is not really an option on TurnKey. Although it can be possible to run commands as `www-data` - which is sort of what we recommend currently and/or changing ownership after making changes. What we might do initially, is create a wrapper script to run commands as the `www-data` user?!
3. Leverage umask - this is not an option for us due to security concerns (setting umask is a user setting; not a filesystem setting).

So, as there is not an ideal fix to the issue that Symfony is trying to resolve via use of ACLs. And it's an issue that is common to all/most TurnKey appliances - i.e. the logged in user (generally `root`) is different to the webserver user (`www-data`). So I'm going to just close this and we'll consider how we might resolve this more broadly.
