### ISSUE TITLE
v 15.1 Gitlab is not updated to 11.5

### ISSUE THREAD

**Issue by sytkosa** [turnkeylinux/tracker#1276]
When updating according to the instructions
https://docs.gitlab.com/ee/update/11.1-to-11.2.html

When executing code

> cd /home/git/gitlab
> 
> sudo -u git -H git checkout 11-2-stable

Erroor
> error: pathspec '11-2-stable' did not match any file(s) known to git.

How to upgrade?
How to upgrade gitlab to version 11.5?

**Comment by JedMeister** [comment]
Apologies on such a slow response. I will address this shortly via documentation. I will also update the appliance so new users will have v11.5 OOTB.

**Comment by JedMeister** [comment]
Ok, I've just added a doc to the GitLab appliance build code so you should be good to go now.

You can find the full doc [here](https://github.com/turnkeylinux-apps/gitlab/blob/master/docs/gitlab-upgrade.rst#id1). It's quite extensive, but worth a read IMO.

I've documented jumping straight to v11.5 (from v11.1). Please note that I tested on a vanilla v15.1 GitLab applaince. I didn't encounter any issues and all seemed to be working well. However, I can't 100% vouch for it with user data involved. So please ensure that you have a tested backup, or better still run it on a test server which includes your data (as noted in the docs).

The specific question you asked re checking out the newer version is covered [here](https://github.com/turnkeylinux-apps/gitlab/blob/master/docs/gitlab-upgrade.rst#adjust-repo).

**Comment by sytkosa** [comment]
When and where can I download version 15.2?

**Comment by JedMeister** [comment]
It hasn't been released yet. I'm still testing, but hopefully should be done by today.

Assuming all goes well I hope to hand off the updated builds to my colleague Alon this afternoon/evening. He's responsible for publishing to the mirror.

Unfortunately though, it's my last day before taking about a week and a half off. So even if the updated appliance gets pushed to our mirror, the website won't provide the link to the new appliance until I get back (and update it).

In the meantime, you could [build the ISO yourself](https://www.turnkeylinux.org/docs/howto-build-isos-with-tkldev) if you want? GitLab is a bit of a monster though and I reckon you'll need at least 2GB RAM in your VM to build it (more is better - FWIW I use 4GB when I build it) - also at least 10GB free space (although I'd go more to be on the safe side).

**Comment by sytkosa** [comment]
Unfortunately, when building an application through tkldev compilation error. Therefore, we are looking forward to when the ready iso image will appear.

**Comment by JedMeister** [comment]
Hi there @sytkosa 

Apologies on the delays with this. Unfortunately the delays will continue a little longer as we've decided to change tack a bit.

We're moving the install to use the GitLab Omnibus package (rather than source). If you'd like to be involved is testing and/or feedback/discussion, please feel free to join us on the forums [here](https://www.turnkeylinux.org/forum/general/fri-20190125-1345/moving-gitlab-appliance-upstream-omnibus-package). (I only just started that thread, but anticipate that there will be at least 2 other TurnKey users involved; Tim and Royce).

**Comment by JedMeister** [comment]
I'm closing this issue now as an updated GitLab appliance has been produced. We now install GitLab via the Omnibus installer. Please note though that the current (v15.3) release does have an outstanding "500 error" bug - see #1315. As noted there, the issue has been resolved but v15.4; the latest (fixed) release is not yet published. It should be available this week. Otherwise, please follow the workaround steps noted on the issue.
