### ISSUE TITLE
TurnKey apt archive down

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1333]
The TurnKey apt repo archive is currently offline (the server is still running; but not serving any of the required files).

We aim to resolve this ASAP but it may take a few hours.

Short term workaround posted in [this forum comment](https://www.turnkeylinux.org/forum/support/thu-20190530-1643/turnkey-core-150-new-install-failed-fetch-archiveturnkeylinuxorg#comment-37686)

**Comment by JedMeister** [comment]
issue resolved and apt archive now working as expected.

**Comment by danhunsaker** [comment]
Looks like this has happened again:

```
Err:1 http://archive.turnkeylinux.org/debian stretch-security InRelease
  Could not connect to archive.turnkeylinux.org:80 (54.83.15.172). - connect (111: Connection refused)
Err:2 http://archive.turnkeylinux.org/debian stretch InRelease
  Unable to connect to archive.turnkeylinux.org:http:
Hit:3 http://security.debian.org stretch/updates InRelease
Ign:4 http://deb.debian.org/debian stretch InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/stretch-security/InRelease  Could not connect to archive.turnkeylinux.org:80 (54.83.15.172). - connect (111: Connection refused)
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/stretch/InRelease  Unable to connect to archive.turnkeylinux.org:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by JedMeister** [comment]
Thanks for reporting @danhunsaker - it should have been back up as of about 24 hours ago.

**Comment by mvp-arena** [comment]
Hi,

The problem is still present:

Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease                            
Hit:3 http://deb.debian.org/debian stretch Release                                                         
Err:4 http://archive.turnkeylinux.org/debian stretch-security InRelease                                    
  Could not connect to archive.turnkeylinux.org:80 (54.83.15.172). - connect (111: Connection refused)
Err:5 http://archive.turnkeylinux.org/debian stretch InRelease                       
  Unable to connect to archive.turnkeylinux.org:http:
Hit:6 https://packages.sury.org/php stretch InRelease
Reading package lists... Done
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/stretch-security/InRelease  Could not connect to archive.turnkeylinux.org:80 (54.83.15.172). - connect (111: Connection refused)
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/stretch/InRelease  Unable to connect to archive.turnkeylinux.org:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.

is there information on the solution?

Thanks

Best regards
MVP-Arena Team

**Comment by JedMeister** [comment]
Hi @mvp-arena. Sorry I missed this post earlier. You must have just missed me when I was checking GH and I didn't see your post until now. Unfortunately, this is a new instance of this same issue. Please see https://github.com/turnkeylinux/tracker/issues/1407#issuecomment-578965580

**Comment by JedMeister** [comment]
Please see https://github.com/turnkeylinux/tracker/issues/1407#issuecomment-579148820
