### ISSUE TITLE
Update transmission to 2.94

### ISSUE THREAD

**Issue by impo** [turnkeylinux/tracker#1376]
Certain trackers blacklist 2.92.

**Comment by JedMeister** [comment]
Thanks for the heads up @impo.

Currently we install transmission from the Debian repos, so while we stay with Debian 9/Stretch base, unfortunately we're stuck with 2.92.

However, we're currently in the process of transitioning to a Debian 10/Buster base (for our v16.0 release). Buster has [2.94](https://packages.debian.org/buster/transmission) - which I note is the current stable.

I'm not sure how long it will be before we have an updated torrent-server appliance, but hopefully not too long...

If you'd like to upgrade before we get there, you can do an "in place" Debian upgrade. Unfortunately, you won't get the new TurnKey packages just yet though as we haven't built them and pushed them to our repo yet (but any day now :crossed_fingers: )

**Comment by JedMeister** [comment]
@impo - apologies on slow turnaround on this, but we've finally released the updated TurnKey Torrentserver appliance](https://www.turnkeylinux.org/web2py).

**Comment by Yur-ok** [comment]
I update transmission from github and now it's version is 4.0.7.

But after this it's not starting.
Can anyone help with some advice?

```log
root@torr ~# service transmission-daemon status
* transmission-daemon.service - Transmission BitTorrent Daemon
     Loaded: loaded (/usr/local/lib/systemd/system/transmission-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-11-14 20:46:41 UTC; 4min 2s ago
       Docs: man:transmission-daemon(1)
    Process: 255 ExecStart=/usr/bin/transmission-daemon -f --log-level=error (code=exited, status=217/USER)
   Main PID: 255 (code=exited, status=217/USER)
        CPU: 3ms

Nov 14 20:46:41 torr systemd[1]: Starting Transmission BitTorrent Daemon...
Nov 14 20:46:41 torr systemd[255]: transmission-daemon.service: Failed to determine user credentials: No such process
Nov 14 20:46:41 torr systemd[255]: transmission-daemon.service: Failed at step USER spawning /usr/bin/transmission-daemon: No such process
Nov 14 20:46:41 torr systemd[1]: transmission-daemon.service: Main process exited, code=exited, status=217/USER
Nov 14 20:46:41 torr systemd[1]: transmission-daemon.service: Failed with result 'exit-code'.
Nov 14 20:46:41 torr systemd[1]: Failed to start Transmission BitTorrent Daemon.
```

```
root@torr ~# journalctl -xe
-- Subject: A start job for unit phpsessionclean.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit phpsessionclean.service has finished successfully.
-- 
-- The job identifier is 209.
Nov 14 21:10:18 torr systemd[1120]: transmission-daemon.service: Failed to determine user credentials: No such process
Nov 14 21:10:18 torr systemd[1120]: transmission-daemon.service: Failed at step USER spawning /usr/bin/transmission-daemon: No such process
-- Subject: Process /usr/bin/transmission-daemon could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The process /usr/bin/transmission-daemon could not be executed and failed.
-- 
-- The error number returned by this process is ERRNO.
Nov 14 21:10:18 torr systemd[1]: Starting Transmission BitTorrent Daemon...
-- Subject: A start job for unit transmission-daemon.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit transmission-daemon.service has begun execution.
-- 
-- The job identifier is 261.
Nov 14 21:10:18 torr systemd[1]: transmission-daemon.service: Main process exited, code=exited, status=217/USER
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit transmission-daemon.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 217.
Nov 14 21:10:18 torr systemd[1]: transmission-daemon.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit transmission-daemon.service has entered the 'failed' state with result 'exit-code'.
Nov 14 21:10:18 torr systemd[1]: Failed to start Transmission BitTorrent Daemon.
-- Subject: A start job for unit transmission-daemon.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit transmission-daemon.service has finished with a failure.
-- 
-- The job identifier is 261 and the job result is failed.
lines 5316-5361/5361 (END)
```

**Comment by JedMeister** [comment]
FWIW we generally try to keep this issue tracker for bugs and feature requests and do support over on our <a href="https://www.turnkeylinux.org/forum/support/">community forums</a> (requires sign up and manual account approval). But seeing as we're here...

> I update transmission from github and now it's version is 4.0.7.

I use transmission myself, but I've always just used the version that ships with Debian.

From what you've shared, the `transmission-daemon` is crashing. My guess is that these are the relevant error lines:
```
Failed to determine user credentials: No such process
Failed at step USER spawning /usr/bin/transmission-daemon: No such process
```
So perhaps something related to the user that transmission is running as? Or something else related to the environment? Another thing that's possibly worth trying is using the service file that ships with the Debian transmission package. The one you're using seems to be from some third party - or perhaps upstream? Maybe there is some compatibility problem with the service file you are using and the underlying Debian system? (Under the hood TurnKey is Debian).

Beyond that, I'm only guessing. If you shared a fair bit more info, then perhaps I could help, but I'm not sure... FWIW the sort of info I'd need to even begin to try to help out:
- What platform is your server running on? Hardware, VM, LXC/Proxmox?
- Which version of TurnKey is it?
- How did you install this newer version of transmission?
- What - if any - other changes did you make?
- What are the contents of the service file you are using?
- Anything else that might seem relevant...

Regardless, considering the fact that you're trying to run an unstable version from upstream (installed from self compiled source code?) then the transmission devs are likely the most qualified to help you. FWIW it looks like the latest stable is [v4.0.6](https://github.com/transmission/transmission/releases) - so perhaps it's worth trying that instead of the bleeding edge?

**Comment by JedMeister** [comment]
@Yur-ok - did you end up resolving your issue?

If so, it might be nice to post back with the fix. Or if not, share the info I asked for above and if/when I get a chance, I'll try to recreate it and see if I can fix it.

**Comment by Yur-ok** [comment]
@JedMeister hi!
Thx for you detailed answer!

I have fixed the error! 
I checked the related services, and there was a problem mentioned by a non-existent user. When I fixed it, everything works fine.
