### ISSUE TITLE
Odoo 15.2 TKLBAM Backup Profile appears to be missing

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1384]
I just went to run a backup on a new install of Odoo (TKL 15.2 build) and get the following error:

> TurnKey Hub Error:  Backup profile archive not found:  turnkey-odoo-15.2-stretch-amd64

I'll test on a 14.1 build for comparison.  (Update - 14.1 (or 14.2 not sure) did have TKLBAM Profile)  15.2 ODOO was an alternative install which did not have the TKLBAM profile.

**Comment by JedMeister** [comment]
Hey @l-arnold - That because we never actually built it.

There was a bug which we fixed in the build code (about 4 months ago) but we never actually built it. TBH, it slipped of the radar and when I remembered it, we decided to focus all our attention on v16.0 rather than releasing an updated Odoo.

If you want to build a TKLBAM profile for it, so long as you still have the ISO, you can do that really easily. The tool that does it, is in buildtasks.

So do this:

```
cd /turnkey/fab
git clone https://github.com/turnkeylinux/tklbam-profiles.git
mkdir -p ~/tklbam-generated-profiles/odoo
cd buildtasks
bin/generate-tklbam-profile --profiles-conf=/turnkey/fab/tklbam-profiles /path/to/iso ~/tklbam-generated-profiles/odoo
```
Then upload the resulting file to your server, unpack it and when you initialise TKLBAM, use the `--profile /path/to/your/new/profile` switch.

I hope that helps.

**Comment by l-arnold** [comment]
Thanks Jeremy,
I will try that.

Landis
