### ISSUE TITLE
TKLBAM restore overwrites WebMin with Prior versions

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1386]
I just did a quick install of TKL Joomla3  (reads TKL 15.3).  Then ran a TKLBAM Restore from a either 14.0 or 14.1 Joomla3 Install.

Everything went very well Except  -  the Momentary Showing of new WEBMIN flashed away and WEBMIN became the OLD Webmin when I logged in on port 12321.

Everything else moved well.  Data,  Certificates etc.

I would expect the WEBMIN and Foundation of TKL 15.x to remain intact and not revert to 14.x.

**Comment by JedMeister** [comment]
Hi @l-arnold - I'm not sure, but my suspicion is that it's not actually installing an old version of Webmin, just re-enabling the old theme (so it looks like the old Webmin). The theme that Webmin uses is set in the Webmin config and a complete TKLBAM restore will default to using the original (i.e. backed up) config files.

Assuming that I'm right, then I'm not really sure how we could automatically work around that in a sensible way. Although explicitly excluding the webmin config when restoring is pretty straight forward. E.g.:
```
tklbam-restore --limits="-/etc/webmin"
```

**Comment by l-arnold** [comment]
That makes sense as shell was showing 15.3 afterwards.  I will look at changing the limit line or perhaps just the template file (once I find it) in the TKLBAM profile.  Perhaps I can just throw a switch in or related to webmin.
It does make sense as I saw a moment of the new login screen before the old one took over.
From a user perspective I think the concept of an in situ upgrade/restore is complicated.  You usually want your old data with the new interface (which emotionally indicates) a new kernel etc.

**Comment by l-arnold** [comment]
So,  just proceeding down that path...  I just ran a TKLBAM restore from a restored TKL Joomla3 15.3.

This time, when I went into Webmin, I got a 1996 style interface and got a prompt to update my "detected" Operating System.  I accepted that, it seemed to take, but the interface stayed in 1996.

I am fishing around for a way to update the UI, but I am not finding, at least yet, within the Webmin interface.  I may start again with the *upgrade* from 14.x backup set.  I deleted the new machine image last time as I landed on the wrong IP anyway.

**Comment by l-arnold** [comment]
OK,  I found it.
Webmin Theme under Webmin Config
  It was set after restore to:
"Old Webmin Theme"    (but it was older than we know).
I changed it to "Authentic Theme"

I'll stick with this and move forward.  I missed getting a screen shot.  It was 1996 for sure.

**Comment by l-arnold** [comment]
Just running my first backup on that server.  I did it this time from within webmin rather than Shell.
I thought in the past you would get the TKLBAM console in Webmin as you do in Shell.  I am only seeing an "activity" indicator at the top of the screen.  Would be nice to watch the actual progress.

A bit off subject.  Sorry.  Lets close this one.

**Comment by JedMeister** [comment]
Hey @l-arnold 

Glad to hear that you worked out the Webmin theme stuff. It's a bit sucky that it doesn't "just work", but I suspect that your experience was because that the old default "Stressfree" theme is not installed by default on v15.x. So I guess when the restored system couldn't use the Webmin theme that it was configured to use, it feel back to some funky old 90s theme (that is possibly bundled by default). Still thanks for noting it here as it's great to be aware of that sort of issue.

Re lack of feedback from TKLBAM in Webmin, as you discovered, the output of Webmin should be the same, regardless of whether it's running in Webmin or the terminal. So perhaps there was just some change in how long it takes before it provides the first feedback in v15.x?

Anyway, I'll close this now as you noted.
