### ISSUE TITLE
Notification email when a backup fails

### ISSUE THREAD

**Issue by cipixul** [turnkeylinux/tracker#1391]
The title says it all.

I would like to be notified by email when a backup fails because it happened several times for the backup process to hang and not work for maybe several days(even weeks) and we were expecting everything to work smoothly and we thought we had backups but it wasn't the case.

I consider this to be of the highest priority because knowing when the backup fails is very important for the peace of mind and normal functioning of the whole backup process.

**Comment by JedMeister** [comment]
Hi @cipixul

First up, assuming you are using a v15.x appliance and have either configured an SMTP relay (or other efforts to ensure reliable email deliverability) then it should already do that!

So I have a few questions to help me understand whether there's a bug, or whether you just need to do a little more config to get it to work.

- What TurnKey appliance and version are you using? If unsure, please share the output of `turnkey-version`. (Please note so long as you are using a v15.x appliance, the basic setup should be consistent regardless of which particular appliance or version, but it's good to have as much detail as possible so that I can try to reproduce the issue).
- Where is your server running? (e.g. from the [Hub](https://hub.turnkeylinux.org/), some other hosting platform, self hosted VM, etc). If self hosted, it's also worth knowing whether you are behind a proxy or firewall (which might be blocking emails from being sent).
- What (if any) efforts have you taken to ensure general email deliverability from your server? E.g. have you configured a systemwide SMTP relay (e.g. via [Confconsole](https://www.turnkeylinux.org/docs/confconsole/mail_relay))? Alternatively, do you have a static IP and have PTR DNS records configured?
- Does your server successfully deliver other emails? If so which ones?

**Comment by JedMeister** [comment]
As I haven't heard back from you @cipixul I'm going to shut this for now. If you continue to have issues, please post back with further info as requested above. Thanks.
