### ISSUE TITLE
Server crushes daily at around 6am PST

### ISSUE THREAD

**Issue by ronpeled** [turnkeylinux/tracker#1397]
Any idea why the server is crushing daily? this started happening in the last week or two. We had the server running for several months now and it was working ok. Please help us troubleshoot this issue.

**Comment by JedMeister** [comment]
Hi @ronpeled 

First up, this is our "issue tracker", specifically for bugs and feature requests. Generally we prefer to do support over on our [forums](https://www.turnkeylinux.org/forum) (requires a separate and free website user account). Then if we confirm that there is a bug, then opening an issue here is appropriate. If you have problems posting, please let me know (along with the email address you're signed up with) via support AT turnkeylinux.org.

Regardless, seeing as we're here now already, let's continue...

---

Can you please provide a bit more context and explanation of the issue?

Firstly, which appliance and what version is this? If you are unsure, please give me the output of:
```
turnkey-version
```
It'd also be useful to understand where your server is running (e.g. local VM running in VirtualBox, AWS instance via the [Hub](https://hub.turnkeylinux.org/), etc).

And when you say that it crashes, do you mean the whole server? Or just the webserver? Or just the website/application that the server is serving? I.e. can you still access the server via a web browser but it's showing an error? Or is the browser connection timing out but you can still connect to your server via SSH/Webmin/etc? Or is it completely unreachable?

Regardless, on face value, seeing as it appears to happen at a regular time, it seems likely that it's being caused by a cron job (i.e. a regular task that runs at 6am PST). So it'd be good to also know what regular services you may have configured to run (e.g. daily TKLBAM backups, Let's Encrypt certificates, etc).</p>

**Comment by JedMeister** [comment]
@ronpeled - bump...

**Comment by JedMeister** [comment]
@ronpeled - ping...

Due to lack of activity and response/feedback, I'm closing this for now...

If this remains an issue for you and you would like some further assistance troubleshooting, please provide additional info as requested, either here or on our [forums](https://www.turnkeylinux.org/forum) and I'll try to assist ASAP.
