### ISSUE TITLE
dehydrated-wrapper fails to call add-water

### ISSUE THREAD

**Issue by nerdoc** [turnkeylinux/tracker#1421]
I am Using an up-to-date TK 15/Nextcloud, and it suddenly stopped working when the Let'sEncrypt key couldn't be retrieved any more automatically. It was the known problem with the LetsEncrypt API, snd should be gone with the confconsole 1.1.1/1.1.2 fix.
I installed https://github.com/turnkeylinux/confconsole/releases/tag/v1.1.2, but now another error message bugs me. Running dehydrated-wrapper breaks because it tries to run add-water, which was already disabled it seems. So worse, during this run, apache is stopped, and the whole site goes down.

```bash
~# /usr/lib/confconsole/plugins.d/Lets_Encrypt/dehydrated-wrapper --force
[2020-02-25 16:45:46] dehydrated-wrapper: INFO: started
[2020-02-25 16:45:46] dehydrated-wrapper: INFO: found apache2 listening on port 80
[2020-02-25 16:45:46] dehydrated-wrapper: INFO: stopping apache2
Failed to start add-water.service: Unit add-water.service is masked.
```

Is there another problem? Why is add-water deactivated/masked, and still used by dehydrated-wrapper?

Using 

* confconsole 1.1.2
* Dehydrated version: 0.6.2

**Comment by JedMeister** [comment]
Hi @nerdoc - Sorry to see that you've experienced so much pain trying to get Let's Encrypt certs on TurnKey.  :disappointed: The whole point of including it was to try toi make users life's easier. But that really blew up when Let's Encrypt changed their set up, followed closely by a whole chain of events which compounded the issue (some new, some old, some introduce by us, some outside our control).

FWIW if you're at all interested in the history and the seemingly unending issues that kept coming up, there are a number issues covering it all here on GH (namely #1359 #1360 & #1387), as well as a few threads on our forums ([here](https://www.turnkeylinux.org/forum/support/tue-20191001-0911/renewing-le-cert-i-get-jws-has-no-anti-replay-nonce) and [here](https://www.turnkeylinux.org/forum/support/mon-20191028-1204/cant-get-any-dehydrated-solutions-work)).

Regardless, when installed as per the [release notes](https://github.com/turnkeylinux/confconsole/releases/tag/v1.1.2), Confconsole v1.1.2 _**should**_ "just work"!?

`add-water.service` **_should_** be `disabled` (so it doesn't run at boot - which it did in v1.1.1), but it _**should not**_  be `masked` (otherwise it can't run at all). TBH, I have no idea how it got to be in that state - a clean install of Confconsole v1.1.2 should leave it in the desired state?!

Regardless, hopefully this should do the trick to get it in the correct state?:

```
systemctl unmask add-water.service
```

If not, please post the output of the following:
```
systemctl status add-water.service
ls -l /etc/systemd/system/add-water.service*
ls -l /lib/systemd/system/add-water.service
cat /lib/systemd/system/add-water.service
```

And hopefully that might give me some insight into what is going on here?!

**Comment by JedMeister** [comment]
bump @nerdoc ?!

**Comment by nerdoc** [comment]
Oh, sorry.
`systemctl unmask add-water.service` did the trick. Thank you. I don't know why it was masked in the first place... Maybe a layer 8 problem ;)
