### ISSUE TITLE
dehydrated-wrapper generates output, which is sent by cron/mail

### ISSUE THREAD

**Issue by nerdoc** [turnkeylinux/tracker#1423]
Per default errors that occur on cron are sent by mail. In case of the let's encrypt wrapper this is bad because I get a mail each day when my turnkeylinux checks for a new certificate:

```
/etc/cron.daily/confconsole-dehydrated:
Certificate will not expire
```
This output is generated by `dehydrated-wrapper`, more special, by openssl, see [here](https://github.com/turnkeylinux/confconsole/blob/0902d7e69fcd46be4ef8cc6a2f44dbf5ddcea71b/share/letsencrypt/dehydrated-confconsole.cron#L17)

It would be good to add a `>/dev/null` to this command, or even a `2>&1>/dev/null`. It shouldn't output anything which is not explicitly meant.

If you want I can make a PR.

**Comment by JedMeister** [comment]
Hmm ok, I found what I was thinking of before.

The issue was bought up in a pull request [here](https://github.com/turnkeylinux/confconsole/pull/24). That was when I refactored things to default to not logging unless renewal was attempted (in [this PR](https://github.com/turnkeylinux/confconsole/pull/30)).

However, either I didn't test sufficiently, or the behaviour of `-noout` changed at some point after I merged that code...

**Comment by nerdoc** [comment]
Yes, I think that's the case. even calling openssl *with* -noout produces the result seen above...

**Comment by JedMeister** [comment]
I've just looked into this a bit closer, and it seems that the latest cron job **does** work as expected (mostly), but by default, unless you remove the existing one, it won't be replaced with the updated one...! Hence why my testing did not show up this issue.

If you're interested, full info is detailed below. But so long as you have [Confconsole v1.1.2](https://github.com/turnkeylinux/confconsole/releases/tag/v1.1.2), you can apply the fix like this (including a bug fix for a bug I discovered whilst testing all this):
```
cp /usr/share/confconsole/letsencrypt/dehydrated-confconsole.cron /etc/cron.daily/confconsole-dehydrated
sed -i "s|echo -ne|echo -n|" /etc/cron.daily/confconsole-dehydrated
echo > /var/log/confconsole/letsencrypt.log
chmod +x /etc/cron.daily/confconsole-dehydrated
```

Now test:

```
root@core ~# /etc/cron.daily/confconsole-dehydrated
root@core ~#
```
:smile: 

----

**Full details**

With the old cron job:
```
root@core ~# chmod +x /etc/cron.daily/confconsole-dehydrated
root@core ~# /etc/cron.daily/confconsole-dehydrated
Certificate will not expire
root@core ~# cat /var/log/confconsole/letsencrypt.log
[2020-03-30 11:20:03] cron: /etc/ssl/private/cert.pem does not require renewal. Nothing to do.
```

Now check that I have the latest Confconsole:
```
root@core ~# apt policy confconsole
confconsole:
  Installed: 1.1.2
  Candidate: 1.1.2
  Version table:
 *** 1.1.2 100
        100 /var/lib/dpkg/status
     1.1.0+2+g6c2aad9 999
        999 http://archive.turnkeylinux.org/debian stretch/main amd64 Packages
```

Yes I do (v1.1.2)! If you don't please make sure that you install the latest release for v15.x; [Confconsole v1.1.2](https://github.com/turnkeylinux/confconsole/releases/tag/v1.1.2).

Now copy in new cron job and clear the log file:
```
root@core ~# cp /usr/share/confconsole/letsencrypt/dehydrated-confconsole.cron /etc/cron.daily/confconsole-dehydrated
root@core ~# echo > /var/log/confconsole/letsencrypt.log
```

Now re-run the cron job (and check the log):
```
root@core ~# chmod +x /etc/cron.daily/confconsole-dehydrated
root@core ~# /etc/cron.daily/confconsole-dehydrated
root@core ~# cat /var/log/confconsole/letsencrypt.log

root@core ~#
```
Note, no output from running cron job, nothing in the log either. If you want to log every attempt (cron still won't email) then set `LOG_INFO` (i.e. edit the cron job and set `LOG_INFO=y`), e.g.:
```
root@core ~# grep "LOG_INFO=y" /etc/cron.daily/confconsole-dehydrated.fixed
LOG_INFO=y  # set to always log certificate expiry check
root@core ~# /etc/cron.daily/confconsole-dehydrated
root@core ~# cat /var/log/confconsole/letsencrypt.log
-ne [2020-03-30 11:26:00] cron: /etc/ssl/private/cert.pem: Certificate will not expire within 30 days. Nothing to do.
```

Oops, looks like there is a bug! It appears that under cron, `echo` doesn't like the `-e` switch?! But essentially it works as expected...

FWIW, a little research has lead me to understand the bug. There are actually 3 (or more) `echo` commands:

1. The shell (`/bin/sh`) builtin `echo`
2. The bash (`/bin/bash`) builtin `echo` (what you get when your run it from the commandline on TurnKey).
3. The external (to any shell) command `/bin/echo`.

And whilst 2 & 3 both support the `-e` switch, 1 (as used by default in cron) **does not**! Oops...

So to fix the bug, in the `log()` function, either change `echo -ne` to `echo -n` or use the full path to echo (`/bin/echo`). Here I'm just going to remove the `-e` as it's not actually required:
```
sed -i "s|echo -ne|echo -n|" /etc/cron.daily/confconsole-dehydrated
```

FWIW I've just fixed it in the confconsole package ([here](https://github.com/turnkeylinux/confconsole/commit/659135d753cd0bbd86711333669396061a826bab)), but I won't be rebuilding for v15.x as I hope to be releasing v16.0 ASAP.

Also, at some point within the lifetime of v16.x I hope to refactor the confconsole package, so all the config files are put in place by the package, rather than requiring manual removal/replacement.
