### ISSUE TITLE
Set Nextcloud data folder outside webroot

### ISSUE THREAD

**Issue by dienteperro** [turnkeylinux/tracker#1436]
[update by @JedMeister]
The Nextcloud data dir should be outside the Nextcloud webroot. IMO `/var/www/nextcloud-data` is a good candidate.

It can be done by adding `--data-dir /var/www/nextcloud-data` switch to the `occ maintenance:install` line in the [Nextcloud conf script](https://github.com/turnkeylinux-apps/nextcloud/blob/master/conf.d/main) (as of current HEAD: [here](https://github.com/turnkeylinux-apps/nextcloud/blob/377b5caa6b80de6db0103d4999e1d5424d0cc765/conf.d/main#L44-L46)).

I assume that we'll need to manually create the dir and ensure that `www-data` has write access (ownership?) too.

**Original post:**

----

Please give the chance to the user to declare the path for Nextcloud's data folder. The path declared by user could be passed to nextcloud occ maintenance:install --data-dir option.

**Comment by JedMeister** [comment]
Hi there.

What is the rationale for that?

Does that work after install? Or only at install?

I.e. can you update an existing install? If so, does it copy the existing data to the new location?

**Comment by dienteperro** [comment]
Hi, the rationale is to have the option to have the data directory in a custom location outside of the public folder, also outside of folders modified by the updates to the nextcloud folder.

Is better at install. In the case of need of change of the data folder, the process is not just to move it, it implies (as stated in https://help.nextcloud.com/t/howto-change-move-data-directory-after-installation/17170) even changes at the database level. They also present the alternative of the use of a soft link, which I think is ready in the turnkey app; but that alternative implies a lower security level. I think is better to bring the option at install, with a reasonable default and have the soft link alternative disabled.

**Comment by JedMeister** [comment]
Ok thanks! Sounds like a great idea and a fairly easy one to implement! :smile:

**Comment by JedMeister** [comment]
Although actually, considering that we pre-install Nextcloud and it's not advisable to change the dir after install (although looks like it can be done), I think the best path would be to preconfigure a default location outside of the webroot for data files.

I suggest `/var/www/nextcloud-data` (the webroot is `/var/www/nextcloud` with the default data dir being `/var/www/nextcloud/data`). Does that sound ok to you?

**Comment by dienteperro** [comment]
Sounds good. Rethinking it, I'd rather opt to `/nextcloud-data` ot `/mnt/nextcloud-data`. In case anyone needs to plug in an external device, bind mount, folder or anything else can use that path in a more natural fashion. I'm seeing this from a Proxmox CT perspective.

**Comment by JedMeister** [comment]
Ok.

I get your point, although so long as it's documented, it shouldn't really matter should it?

I have a few reasons for my resistance to either of your suggestions.

One is my desire to generally be compliant with the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). I know that on some appliances (e.g. TKLDev), some applications (e.g. TKLBAM) and some platforms (e.g. Hub/AWS) there are a few instances where TurnKey breaks that already, but they were implemented long before my involvement as a core TurnKey developer. So making it a root level dir (i.e. `/nextcloud-data`) is not something I'd be happy with at all and I don't think a sub dir of `/mnt` (i.e. `/mnt/nextcloud-data`) is really acceptable either.

My main rationale for wanting to use `/var/www/nextcloud-data` is two-fold:
1. to keep it consistent with other TurnKey apps that store data outside the webroot (a few others already use `/var/www/APP_NAME-data`).
2. I imagine that most people familiar with Linux (especially Debian/Ubuntu) would start looking within `/var/www` if the `data` dir was missing from the webroot (i.e. `/var/www/nextcloud`).

Another part of my rationale is to make things easier with our built in backup tool (tklbam). I'd much prefer it if we're storing the Nextcloud data in a path that will be automatically included in backups (rather than having to explicitly add it). `/var/www` is a default included path - see the [Core tklbam profile](https://github.com/turnkeylinux/tklbam-profiles/blob/master/core) for full detail of default paths).

So as I say, my preference is to use `/var/www/nextcloud-data`. Although if you feel strongly, I'm open to a compromise and/or further discussion. But I'd like it to be compliant with the FHS & ideally be a path already included in the default TKLBAM profile.

So if you're adamant you rather it not be `/var/www/nextcloud-data`, hte only other path that seem logical to me would be a sub dir of `/srv`. E.g.:
- `/srv/storage/nextcloud`
- `/srv/storage/nextcloud-data`
- `/srv/storage/nextcloud/data`
- `/srv/nextcloud-data`
- `/srv/nextcloud/data`

IMO none of the other paths ok by the FHS and/or included in TKLBAM backups by default would really be a good fit. I guess a sub dir of `/usr/local` would be ok, but I imagine that would probably be the last place most users would look... Probably much less obvious than `/var/www/nextcloud-data`!

Thoughts?

**Comment by dienteperro** [comment]
Let it be `/var/www/nextcloud-data` then.
