### ISSUE TITLE
Gitlab will not fetch packages anymore on update - GPG key outdated - process should be clearly documented

### ISSUE THREAD

**Issue by markusdd** [turnkeylinux/tracker#1441]
Hi,

was receiving NO_PUBKEY messages form cron-apt and when running apt update manually.

I followed these instructions as gitlab has changed their repo key:
https://docs.gitlab.com/omnibus/update/package_signatures.html#fetching-new-keys-after-2020-04-06

In short:
```
# Download the new key
curl https://packages.gitlab.com/gpg.key -o /tmp/omnibus_gitlab_gpg.key

# Import the key
## Debian/Ubuntu/Raspbian
$ sudo apt-key add /tmp/omnibus_gitlab_gpg.key
```

But then I discovered that in the sources.list file for gitlab the gpg key is hardcoded to a path.

I threw out these options and now it works.

I recommend for turnkey to switch to the 'standard apt-key add' procedure for GPG keys and provide a notification and proper update for existing installations.
This will affect all users of the gitlab instance I presume.

**Comment by JedMeister** [comment]
Hi @markusdd 

Thanks for your note and feedback.

FYI we configure third party repos to use specific hardcoded keyring paths as per [Debian best practice third party apt repository management](https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry) (also see Debian bugs [861695](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861695) & [877012](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877012)).

Allowing all apt repositories to share a common keyring is a potential security risk. Especially if their previous key were compromised (by default simply adding a new key, won't remove the old key or it's "trusted" status). IMO the whole point of key rotation is defeated if the old key is still trusted and saved in the keyring!

FWIW we also pin packages for additional security as well.

Assuming that the GitLab GPG keyring is formatted correctly, this one line should have done the trick:

```
curl https://packages.gitlab.com/gpg.key -o /usr/share/keyrings/gitlab-ce.gpg
```

So IMO a much better idea would be if GitLab documented the best practice way of doing things rather than the "easy" way. At the very least they should be documenting removal of the old key from the common keyring.

Having said that, we should definitely document this better so that users have a good chance of finding it via a search. As I hinted above, we do this for all 3rd party apt repos we use, so it's not just the GitLab appliance that this applies to.

As such, rather than closing this issue as "won't fix", I'm going to repurpose it as a documentation issue. I hope you're cool with that.

**Comment by markusdd** [comment]
Certainly. Makes Sense. I'm more of a redhat/RPM Guy and Not really into the details of apt repo Management. ( I did not even know this Key Option existed) I do not think they will be changing their keys constantly, so an update for the appliance should be good for a while.But improving Docs is never a bad idea.Am 15.04.2020 04:33 schrieb Jeremy Davis <notifications@github.com>:
Hi @markusdd
Thanks for your note and feedback.
FYI we configure third party repos to use specific hardcoded keyring paths as per Debian best practice third party apt repository management (also see Debian bugs 861695 & 877012).
Allowing all apt repositories to share a common keyring is a potential security risk. Especially if their previous key were compromised (by default simply adding a new key, won't remove the old key or it's "trusted" status). IMO the whole point of key rotation is defeated if the old key is still trusted and saved in the keyring!
FWIW we also pin packages for additional security as well.
Assuming that the GitLab GPG keyring is formatted correctly, this one line should have done the trick:
curl https://packages.gitlab.com/gpg.key -o /usr/share/keyrings/gitlab-ce.gpg

So IMO a much better idea would be if GitLab documented the best practice way of doing things rather than the "easy" way. At the very least they should be documenting removal of the old key from the common keyring.
Having said that, we should definitely document this better so that users have a good chance of finding it via a search. As I hinted above, we do this for all 3rd party apt repos we use, so it's not just the GitLab appliance that this applies to.
As such, rather than closing this issue as "won't fix", I'm going to repurpose it as a documentation issue. I hope you're cool with that.
