### ISSUE TITLE
OpenStack download failed

### ISSUE THREAD

**Issue by ywptr** [turnkeylinux/tracker#1449]
OpenStack download failed with this error message:

Error: not a legal filename 'turnkey-moodle-15.3-stretch-amd64-openstack.qcow2'

**Comment by JedMeister** [comment]
Hi there,

Apologies on slow response. As per the tags I've just added, this is a known issue. See #1239.

Regardless, you bringing it up again prompted me to have another quick look. And with a fresh set of eyes, I realised that the code that needed to adjusted was in the DB, not in the php files... Doh! So it should now be working...

Also I hope to build v16.0 Core appliance as OpenStack shortly and will be looking for users to confirm that it works ok before I publish the others as OpenStack builds. If you'd like to help out, that'd be awesome! :)

**Comment by ywptr** [comment]
Hi, sorry for late response and thanks a lot for fixing this, it will 
greatly help to deploy Turnkeylinux in OpenStack-compatible VM hosting 
e.g. Digital Ocean. (will not need to download and upload through desktop)

Sure for the helping out request, just let me know how to help and when, 
and we will work out the time.

**Comment by JedMeister** [comment]
Sorry for my slow response.

I'm pretty sure that our images aren't compatible with Digital Ocean, because they explicitly require `cloud-init` (which our images do not include and installation would likely cause conflicts with our inithooks initialisation system). We hope to look into resolving this at some point, but until then...

Re testing, fantastic, thanks. I'll hopefully build core v16.0 to Openstack sometime soon and upload it to the mirror. You can then test at your convenience. I'll try to remember to post back here when that's been done...

**Comment by vondrt4** [comment]
Yes, TurnKey Linux on OpenStack does not use OpenStack's native metadata, but the EC2 compatible version. I'm not familiar with Digital Ocean. If they don't have the EC2 format, it won't work.
But I had a hybrid Inithooks/cloud-init system before. I believe I just disabled the inithooks that deal with metadata and had cloud-init run before inithooks. That was back in version 14.0 and I don't have the experiment any more.
