### ISSUE TITLE
 gomail: could not send email 1: address localhost: missing port in address

### ISSUE THREAD

**Issue by rejuce** [turnkeylinux/tracker#1501]
as per description, as I understood, the mail server should be already setup in the image?

whenever I try to send an email from turnkey i get the error:

 gomail: could not send email 1: address localhost: missing port in address

I am not sure which port and where it is missing. Anyone an idea?

**Comment by JedMeister** [comment]
Thanks for the bug report. Could you please confirm which appliance this is and ideally the version. I.e. the output of `turnkey-version` will tell me all I need to know! :smile:

**Comment by rejuce** [comment]
turnkey-gitea-15.2-stretch-amd64

**Comment by JedMeister** [comment]
FWIW the current release is v16.0 but looking at the config file, I suspect that that has this same issue.

Browsing the [Gitea docs](https://docs.gitea.io/en-us/config-cheat-sheet/#mailer-mailer) suggests that there are probably 2 ways around this. One would be to provide the port for postfix, and the other is to just use sendmail. Using sendmail is probably easier and should "just work".

The config file is at `/etc/gitea/app.ini`. Look for the `[mailer]` section . It should look like this:
```
[mailer]
ENABLED = true
HOST    = localhost
FROM    = admin@YOUR_DOMAIN
USER    = 
PASSWD  = 
```
Add the following lines:
```
MAILER_TYPE = sendmail
SENDMAIL_PATH = /usr/sbin/sendmail
SENDMAIL_TIMEOUT = 5m
```
Then restart Gitea with `systemctl restart gitea.service`.

Mail should now send. Note that sending mail via Postfix should in theory "just work" but often sending from servers running with a dynamic IP (e.g. ISP allocated IP, AWS IP, etc) can be problematic (often because spammers have abused the IP by sending spam and got the IP blacklisted).

So you may instead choose to configure a remote SMTP relay. You could do that within Gitea (instead of doing the above) although I would recommend the above and configure the host to forward to a SMTP relay (that way you'll get all system emails too). There is a [Confconsole](https://www.turnkeylinux.org/docs/confconsole) plugin to configure [system wide SMTP relay](https://www.turnkeylinux.org/docs/confconsole/mail_relay).

**Comment by rejuce** [comment]
unfortunately did not solve it ...
ist fehlgeschlagen: gomail: could not send email 1: address localhost: missing port in address

i tried to privide default sendmail port 25 to localhost:25 , but that gives me:

ist fehlgeschlagen: gomail: could not send email 1: StartTLS: x509: certificate is valid for tkldev, not localhost

**Comment by rejuce** [comment]
ahh I got it to work:

i added 
HOST = localhost:25
SKIP_VERIFY = true

**Comment by rejuce** [comment]
same config also works without adding
MAILER_TYPE = sendmail
SENDMAIL_PATH = /usr/sbin/sendmail
SENDMAIL_TIMEOUT = 5m

but somehow the mail reaches my gmail but not my company adress...have to investigate

**Comment by JedMeister** [comment]
Apologies on my slow response. Great to hear you got it to work and thanks tons for posting back with the solution.

My guess re it not getting to your company address is spam filtering. Perhaps the IP address of your server has been blacklisted with one of the spam blacklisters?

**Comment by OnGle** [comment]
Afaik the initial issue here is that it's sending data over TLS, but the TLS cert's host doesn't match the hostname used under `HOST` which (correctly) will fail verification (and thus `SKIP_VERIFY` solves the 'issue'). On a standard turnkey install you'll be using your local postfix server for sending mail, as such the security damage done by adding in `SKIP_VERIFY` is probably low to none. So we *could* include this fix.

Thoughts? @JedMeister

**Comment by JedMeister** [comment]
@OnGle - I'm fine with your suggestion, although TBH, I'd be inclined to go with the sendmail conf (as noted in https://github.com/turnkeylinux/tracker/issues/1501#issuecomment-671891828)?!

**Comment by OnGle** [comment]
I could be wrong but I believe that's *WITHOUT* the config changes you suggested, but *WITH* the `NO_VERIFY` option set.

**Comment by JedMeister** [comment]
Ah ok, thanks @OnGle - as discussed, have a quick look at using sendmail directly if possible (IMO that's the preferable option). If not, then using postfix via `localhost:25` is certainly an acceptable fallback.
