### ISSUE TITLE
Odoo  wkhtmltopdf download site moved to github

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1581]
In Odoo conf.d/main

in the past 

 DEB='wkhtmltox_0.12.5-1.stretch_amd64.deb'
 URL='https://downloads.wkhtmltopdf.org/0.12/0.12.5'
 wget $URL/$DEB
 dpkg -i $DEB
 rm $DEB

Was called.  It made it into the current mirror build however it fails now in TKLDEV.
Now being hosted on github, per this "issue" dated July 30, 2020
 https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4787
 
 Expect this can be changed relatively easily.

**Comment by l-arnold** [comment]
For now I commented those lines out of my tkldev build package.  Will see how to insert the correct "git clone" command, and specifially "where" to put it in the Odoo build.

**Comment by l-arnold** [comment]
Actually it appears that the bundles can be downloaded from here with minimal change to the odoo build:
https://wkhtmltopdf.org/downloads.html

**Comment by JedMeister** [comment]
Thanks for the note @l-arnold. And actually, it looks like we're installing the 'stretch' version for v16.0, where we should be installing the 'buster' version. So that's a bug (even if it's not actually causing any immediate issues).

To gather than same version (but for 'buster'), hopefully the URL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb link should work for us and give us the same version?!

**Comment by l-arnold** [comment]
Let me know and I'll test it.  (I'll test it manually soon - removed it manually yesterday).  
Landis

**Comment by JedMeister** [comment]
Closed via https://github.com/turnkeylinux-apps/odoo/pull/18/commits/c1e773fed8c9c6fc361848768faf15e3eb417aa1

(I won't actually close this issue until the PR is merged into master).
