### ISSUE TITLE
https://www.turnkeylinux.org/wordpress PHP error in wordpress PHP (7.3.27-1~deb10u1)

### ISSUE THREAD

**Issue by sanderlv** [turnkeylinux/tracker#1585]
Hi, How can I "update" to PHP7.4. My WordPress linux container is saying PHP is outdated and should be updated.

WordPress advises me to update...

https://wordpress.org/support/update-php/

I must be up to date...
```
root@server ~# apt-get update
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                                                                 
Ign:3 http://archive.turnkeylinux.org/debian buster-security InRelease                                              
Ign:4 http://archive.turnkeylinux.org/debian buster InRelease
Hit:5 http://archive.turnkeylinux.org/debian buster-security Release
Hit:7 http://archive.turnkeylinux.org/debian buster Release
Reading package lists... Done                             
root@server ~# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@server ~# apt-get upgrade     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by JedMeister** [comment]
Firstly, hi! :wave: 

Next, this is our "issue tracker" so intended for bugs and/or feature requests, rather than general support queries. Support is best done in our [forums](https://www.turnkeylinux.org/forum/support) (free website user account required). But seeing as we're here now, I'll respond here...

----
*sigh* I wish they wouldn't do that... Or at least be a bit more transparent about it. Anyway...

Do you really need to update PHP? I.e. are there PHP errors because one of your plugins needs PHP7.4?

If the answer to either of those questions is no, then there is no need to do anything (you can still if you want, but it's up to you).

Despite what WordPress notes, if you are using the latest major version of TurnKey Linux (currently v16.x - what you're using given the output you posted), there is no significant advantage to update PHP. Upgrading PHP will just result in more maintenance work for you and arguably greater risk of security issues.

**Some background on Debian GNU/Linux - the basis of TurnKey GNU/Linux**

To explain; TurnKey GNU/Linux is based on Debian GNU/Linux. The current version of Debian is always known as 'stable' but has a unique codename. Debian 'stable' is currently version 10 and is codenamed "Buster". 

Debian is an ideal Linux distro for servers because of it's combined focus on stability and security. During it's testing phase, the interactions between software are tested, as well as the software itself. So once "testing" (Debian's pre-release channel) moves to "stable" the versions of software are frozen (technically they're frozen during the final stages of "testing"). So with a few exceptions (mostly relevant to desktop users, not so much servers) no new versions of any software will be included for the lifetime of the release.

Any security bugs (and some general bugs occasionally too) in any of the included software are addressed by carefully crafted patches that resolve the issue with the minimum possible changes. Because of their minimal changes and careful testing, these security updates are almost always bug-free so TurnKey pre-configures our servers to auto install these nightly.

**PHP**

As you've noticed, Debian Buster (the basis of TurnKey v16.x) is packaged with PHP7.3.

Debian will be providing security support for Buster (and therefore PHP7.3) at least until [June, 2024](https://wiki.debian.org/LTS), even though the PHP support for v7.3 ends [Nov, 2022](https://www.php.net/supported-versions.php).

So unless you actually need to upgrade PHP, then I would leave it as is. Later this year we will be releasing a TurnKey v17.x (based on Debian 11/Bullseye - which is currently in the last stages of "testing").

**But what if I do need to update (or just really want the latest)?!**

If for whatever reason you still want to update PHP, firstly be aware that you will no longer get auto security updates for PHP packages. So you'll need to regularly (ideally daily, but you may get away with less often) install updates to ensure that there aren't any security issues with your site.

As to actually installing the newer version, one of the Debian (and Ubuntu) PHP maintainers; [Ondrej Sury builds new PHP version packages](https://deb.sury.org/). He maintains his own 3rd party Debian repo and is known to address security issues in a timely fashion (although you'll still need to manually install them). There is a simple [script](https://packages.sury.org/php/README.txt) for the initial repo setup. And there is also a [wiki](https://github.com/oerdnj/deb.sury.org/wiki) that may be of some value.

We also have a (somewhat dated) [tutorial on the forums](https://www.turnkeylinux.org/forum/support/tue-20190820-2132/php-73). Note that covers upgrading PHP to v7.3 on TurnKey v15.x (based on Debian 9/Stretch). So it's a different version of PHP on a different version of TurnKey (Debian). With that knowledge in mind, the rest of the instructions should still be relevant (obviously make some adjustments for different versions though).

If that's still not enough to get you going, then you may find further (more detailed, perhaps more specifically relevant) information online. You should find that any instructions for Debian Buster/10 should apply equally to TurnKey v16.x. Often instructions for Ubuntu will also apply, but be careful not to add Ubuntu software repositories, or install software specifically built for Ubuntu (unless it also explictly says that it's for Debian too). That is because whilst Ubuntu is also based on Debian, it is not binary compatible with Debian (TurnKey **is** binary compatible with Debian).

I hope that helps.

**Comment by sanderlv** [comment]
Thank you an "sorry" for opening this up here. I will sign up on the forum. Since I could not find find any related questions about this topic I decided to ask here. Also the fact that I was confronted with "the white screen of dead" I was thinking more in the "issue" direction than support.

I had the white screen of death... (for admin area)

tried everything form https://www.wpbeginner.com/wp-tutorials/how-to-fix-the-wordpress-white-screen-of-death/

No luck. So I decided to restore backups and only the one going back 5 days solved my issue... So I thought I must have been "hacked/broken" by something... (No proof). Only thing worrying me was that php version thing...

Thank you for pointing me out all of the above. I understand all that you are saying... I come from a  synology setup and there php7.4 was used. I decided to split the webhosting part off and decided to use turnkey linux worpress (wow!) so I wondered if and why an older version of php could have been debet to my downing and the white screen of death.
