### ISSUE TITLE
Etherpad on Proxmox - start update or install Plugin - 502 error and NPM process running 100% CPU 

### ISSUE THREAD

**Issue by BoscoLAB** [turnkeylinux/tracker#1612]
New installation, Etherpad runs normally.

Start update plugin or install a plugin, NPM then runs every 30 seconds on 100% CPU. Web server says 502 BadGateway.
After a restart the same error.

**Comment by JedMeister** [comment]
I've booted an instance up and it appears that there are 2 "issues" here.

The first is that `npm` chewing up tons of CPU while it's trying to download and install updates is expected behaviour.

The other is that it appears that one of the updates has a new/updated dependency and it doesn't appear that Etherpad handles that properly. That's what causes the extended 504 (on low resource machines, it's not unexpected to get a brief period of getting 504 while the dependencies are installing and Etherpad restarting).

To diagnose that, here's what I did (via an SSH session):

```
systemctl stop etherpad
cd /opt/etherpad
runuser node -c /opt/etherpad-lite/bin/run.sh
```
Eventually, that gave this output:

```
[2021-05-21 06:08:36.633] [ERROR] runCmd|npm - npm ERR! missing: ep_align@0.3.33, required by etherpad-lite
[2021-05-21 06:08:36.673] [ERROR] server - Error occurred while starting Etherpad
[2021-05-21 06:08:36.675] [ERROR] server - Metrics at time of fatal error:
{
  "httpStartTime": 0,
  "memoryUsage": 59944960,
  "memoryUsageHeap": 13416664,
  "ueberdb_lockAwaits": 0,
  "ueberdb_lockAcquires": 0,
  "ueberdb_lockReleases": 0,
  "ueberdb_reads": 0,
  "ueberdb_readsFailed": 0,
  "ueberdb_readsFinished": 0,
  "ueberdb_readsFromCache": 0,
  "ueberdb_readsFromDb": 0,
  "ueberdb_readsFromDbFailed": 0,
  "ueberdb_readsFromDbFinished": 0,
  "ueberdb_writes": 0,
  "ueberdb_writesFailed": 0,
  "ueberdb_writesFinished": 0,
  "ueberdb_writesObsoleted": 0,
  "ueberdb_writesToDb": 0,
  "ueberdb_writesToDbFailed": 0,
  "ueberdb_writesToDbFinished": 0
}
[2021-05-21 06:08:36.676] [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
    at exports (/opt/etherpad-lite/src/node/utils/run_cmd.js:119:25)
    at Object.exports.getPackages (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:125:48)
    at Object.exports.update (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:99:34)
    at Object.exports.start (/opt/etherpad-lite/src/node/server.js:139:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
It eventually then exited. Noting the first line of the error, I guessed that it was a missing dependency; `ep_align@0.3.33`

To install the missing dependency (that I hit):
```
cd /opt/etherpad
runuser node -c 'npm install ep_align@0.3.33'
```
After that, I retested in my SSH session (and it worked), but that's optional. When you're done, restart Etherpad service:
```
systemctl start etherpad
```

You should now be good to go...

**Comment by BoscoLAB** [comment]
Thanks for your workaround! It works. But I can only install the updates and plugins via the console. Not through the GUI, then I get the errors again.

**Comment by JedMeister** [comment]
Hmm, ok. We might need to push this back upstream and see if they have any thoughts?!

FWIW, I've had a look at [their tracker](https://github.com/ether/etherpad-lite/issues) and whilst this specific issue isn't noted, it seems that the plugin system is a bit problematic, especially with newer versions fo Node/NPM. And FWIW, we're using the latest stable Node (v14.x) so perhaps rolling back to Node v12.x might help?

**Comment by mrchaosbude** [comment]
after one year the problem seems to persist

**Comment by JedMeister** [comment]
> after one year the problem seems to persist

We finally did get it worked out, the issue appears to be related to mismatched versions of npm internally and on the system. Etherpad upstream really needs to update the version of npm internally to properly fix this.

However, I did discover that it can be worked around by exactly matching the system npm version with the one included in Etherpad.

The updated appliance was published a week or so ago. Please give it a spin and see how it goes. I haven't tested exhaustively, but it definitely appeared to work fine for installing plugins when I tested it.

As such, I'll close this issue now, but please feel free to post back here and reopen this issue (or open a new one if you'd rather) if needed.
