### ISSUE TITLE
Webmin not working

### ISSUE THREAD

**Issue by noppel** [turnkeylinux/tracker#1625]
Using proxmox, privileged container, nested=1
There are various misconfigurations that should be fixed:
- systemctl start webmin
- systemctl enable webmin
- in "/etc/stunnel/webmin.conf", output must be changed to "output = /webmin.log"
- in "/etc/stunnel/webmin.conf", debug should be uncommented as you wont see the errors otherwise
- in /var/lib/stunnel4 I have created the directory var/lib/stunnel4/
- in /var/lib/stunnel4/var/lib/stunnel4 I have created a link from webmin.pid to ../../../webmin.pid

**Comment by JedMeister** [comment]
> systemctl start webmin
> systemctl enable webmin

Webmin is already enabled and should auto start on first boot. If that's not the case, then it sounds like thee is something wrong with your environment.

You should only need to manually (re)start Webmin (or alternatively reboot) if you update the Webmin package (the package upgrade will stop the service, but not restart it).

What you describe sounds very much like the expected behaviour of a privileged container without nesting enabled (multiple services will not start and/or run cleanly)?! Perhaps nesting isn't t working as it's meant to on your system for some reason?

> in "/etc/stunnel/webmin.conf", output must be changed to "output = /webmin.log"
> in "/etc/stunnel/webmin.conf", debug should be uncommented as you wont see the errors otherwise
> in /var/lib/stunnel4 I have created the directory var/lib/stunnel4/
> in /var/lib/stunnel4/var/lib/stunnel4 I have created a link from webmin.pid to ../../../webmin.pid

These are optional settings useful for debugging issues, but are intentionally not configured by default. As per most Debian packages that we use, we follow Debian's 'sane defaults" unless we have specific reason not to. In the case of stunnel, we did consider enabling them some time ago, but decided against it as stunnel is pretty straight forward and it would just be additional noise for most users. If debugging was required, then the (built in Debian) docs and the config file is fairly verbose on what is required. 

Having said that, perhaps we could add a doc page for stunnel and spell out the setup for debugging issues? Please feel free to do that in our [documentation](https://www.turnkeylinux.org/docs), probably in the [tutorial/How to section](https://www.turnkeylinux.org/docs/howto) (it's a wiki and can be edited by logged in users).
