### ISSUE TITLE
fatal: Squid CA cert not found.

### ISSUE THREAD

**Issue by nizq** [turnkeylinux/tracker#1684]
turnkey-tkldev-16.1-buster-amd64

```
deck -D build/bootstrap
deck /turnkey/fab/bootstraps/buster build/bootstrap
fab-apply-overlay /turnkey/fab/common/overlays/bootstrap_apt build/bootstrap;
fab-chroot build/bootstrap "echo nameserver 8.8.8.8 > /etc/resolv.conf";
fab-chroot build/bootstrap "echo nameserver 8.8.4.4 >> /etc/resolv.conf";
mkdir -p build/bootstrap/usr/local/share/ca-certificates/;
# temporarily allow cert to not exist
cp /usr/local/share/ca-certificates/squid_proxyCA.crt build/bootstrap/usr/local/share/ca-certificates/ || true;
cp: cannot stat '/usr/local/share/ca-certificates/squid_proxyCA.crt': No such file or directory
fab-chroot build/bootstrap --script /turnkey/fab/common/conf/bootstrap_apt;
fatal: Squid CA cert not found.
make: *** [/usr/share/fab/product.mk:541: build/stamps/bootstrap] Error 1
```

**Comment by JedMeister** [comment]
Hi @nizq - sorry that I missed this post. I've had my head down working on v17.0, then had a bit of time off...

So this issue comes from the fact that we're in the process of a new major release (v17.0) and we've needed to change the caching mechanism (see #1560).

So I suggest that you check out the v17.0rc1 (1st release candidate) of TKLDev. Download links are in the [blog post announcement](https://www.turnkeylinux.org/blog/v17.0rc1-core-and-tkldev).

I'm going to close this now, but if you continue to have issues, please post in our [forums](https://www.turnkeylinux.org/forum) (you need to be logged in via a (free) website user account to start a new thread - recommended). Or alternatively, you can just post back here, but I monitor the forums much more closely so you'll likely get a quicker response there.

**Comment by derMart** [comment]
same error here trying to build https://github.com/kdunn926/bitkey-ng on https://www.turnkeylinux.org/download?file=turnkey-tkldev-17.2-bullseye-amd64.iso
make output is:
```
$ make
deck -D build/bootstrap
deck /turnkey/fab/bootstraps/bullseye build/bootstrap
fab-apply-overlay /turnkey/fab/common/overlays/bootstrap_apt /bootstrap
fab-chroot build/bootstrap "echo nameserver 8.8.8.8 > /etc/resolv.conf";
fab-chroot build/bootstrap "echo nameserver 8.8.4.4 >> /etc/resolv.conf";
fab-chroot build/bootstrap --script /turnkey/fab/common/conf/bootstrap_apt;
fatal: Squid CA cert not found.
make: *** [/usr/share/fab/product.mk:570: build/stamps/bootstrap] Error 1
```

EDIT: Not sure if this is important but I am running tkldev inside virtualbox and while installing there was not inet access. I turned on network access and then manually ran `turnkey-init` again which did not result in any error.
EDIT2: I made a fresh install of tlkdev with network access, problem remains, so that can't be the offender...

**Comment by JedMeister** [comment]
Hi @derMart 

Firstly, thanks for bringing [kdunn926/bitkey-ng](https://github.com/kdunn926/bitkey-ng) to my attention. I've been wanting to revive Bitkey for ages and I did make a start earlier in the year, but didn't get very far before I had to divert my attention back to TurnKey. If I'd know that this fork (that isn't a GitHub fork) existed, I may have been able to get there (basically I've done some of what has been done in bitkey-ng - but nowhere near all - the only improvement of mine over this one is that mine successfully builds an ISO on v17.x - admittedly an ISO that doesn't work).

FWIW Bitkey has always been a side project and beyond it's initial release has never really got the love it deserves. The [original repo](https://github.com/bitkey/bitkey) is pretty broken these days. From a quick glance at the bitkey-ng code, it looks like it should be pretty close to working, although I suspect that even once you fix this particular issue, that you'll hit more issues.

I say that as the bitkey-ng buildcode appears to predate TKLDev v17.x (so sort of like this issue, but the opposite).

Unfortunately, @kdunn926 didn't fork the original bitkey code and hasn't maintained any of the original bitkey git history, so pulling their changes back into bitkey "proper" will be a bit of work. It appears that they were trying to keep their code changes all in the one repo, but it still depends on [TKLDev common](https://github.com/turnkeylinux/common) code. Whilst it does provide an updated standalone [`turnkey-desktop.mk`](https://github.com/kdunn926/bitkey-ng/blob/main/turnkey-desktop.mk) (an updated copy of [`turnkey-desktop.mk`](https://github.com/turnkeylinux/common/blob/master/mk/turnkey-desktop.mk) in common) - it's not accounting for all the changes that were made in v17.x.


FWIW, the lines that you'll need to add to `turnkey-desktop` to ensure that the squid cert (the missing file it's complaining about) is in place are [these ones](https://github.com/turnkeylinux/common/blob/master/mk/turnkey.mk#L33-L35).

Personally, I'd be inclined to undo some of their changes and recombine it all back into common (some of their changes made in bitkey-ng have been made specifically to keep all the changes in one repo). OTOH our original intention was that we were going to also create TurnKey Desktop isos (i.e. not just servers) but Bitkey was the only one that ever got published. So perhaps until we actually look to revive that plan, perhaps keeping Bitkey in it's own repo might be a good idea?

I'm not sure when or even if I'll have the spare cycles to look closer at reintegrating bitkey-ng changes back into bitkey, but happy to hear how you go. If you want, please feel free to open a new issue to track your Bitkey revival process. I suggest that you fork the bitkey-ng repo and work in that. I can't offer any promises, but I'm happy to put in my 2c worth if you are motivated to get this working. And if you can, I'm willing to do the work to pull your changes back into Bitkey and bring it up to date. Having said that, we'll be looking to start transitioning to

**Comment by JedMeister** [comment]
Hi @derMart 

Firstly, thanks for bringing [kdunn926/bitkey-ng](https://github.com/kdunn926/bitkey-ng) to my attention. I've been wanting to revive Bitkey for ages and I did make a start earlier in the year, but didn't get very far before I had to divert my attention back to TurnKey. If I'd know that this fork (that isn't a GitHub fork) existed, I may have been able to get there (basically I've done some of what has been done in bitkey-ng - but nowhere near all - the only improvement of mine over this one is that mine successfully builds an ISO on v17.x - admittedly an ISO that doesn't work).

FWIW Bitkey has always been a side project and beyond it's initial release has never really got the love it deserves. The [original repo](https://github.com/bitkey/bitkey) is pretty broken these days. From a quick glance at the bitkey-ng code, it looks like it should be pretty close to working, although I suspect that even once you fix this particular issue, that you'll hit more issues.

I say that as the bitkey-ng buildcode appears to predate TKLDev v17.x (so sort of like this issue, but the opposite).

Unfortunately, @kdunn926 didn't fork the original bitkey code and hasn't maintained any of the original bitkey git history, so pulling their changes back into bitkey "proper" will be a bit of work. It appears that they were trying to keep their code changes all in the one repo, but it still depends on [TKLDev common](https://github.com/turnkeylinux/common) code. Whilst it does provide an updated standalone [`turnkey-desktop.mk`](https://github.com/kdunn926/bitkey-ng/blob/main/turnkey-desktop.mk) (an updated copy of [`turnkey-desktop.mk`](https://github.com/turnkeylinux/common/blob/master/mk/turnkey-desktop.mk) in common) - it's not accounting for all the changes that were made in v17.x.

FWIW, the lines that you'll need to add to `turnkey-desktop` to ensure that the squid cert (the missing file it's complaining about) is in place are [these ones](https://github.com/turnkeylinux/common/blob/master/mk/turnkey.mk#L33-L35).

Although perhaps if you start with a v16.x TKLDev and checkout the `16.x` branch of [`common`](https://github.com/turnkeylinux/common/tree/16.x) it might "just work"?

Personally, I'd be inclined to undo some of their changes and recombine it all back into common (some of their changes made in bitkey-ng have been made specifically to keep all the changes in one repo). OTOH our original intention was that we were going to also create TurnKey Desktop isos (i.e. not just servers) but Bitkey was the only one that ever got published. So perhaps until we actually look to revive that plan, perhaps keeping Bitkey in it's own repo might be a good idea?

I'm not sure when or even if I'll have the spare cycles to look closer at reintegrating bitkey-ng changes back into bitkey, but happy to hear how you go. If you want, please feel free to open a new issue to track your Bitkey revival process. I suggest that you fork the bitkey-ng repo and work in that. I can't offer any promises, but I'm happy to put in my 2c worth if you are motivated to get this working.

If you can get it working, then that would provide serious motivation for me to pull the changes back into Bitkey (and common) and bring it all up to date. Having said that, we'll be looking to start transitioning to Debian 12/Bookworm base soon, so there will be new changes of significance coming soon... The sooner Bitkey gets updated to v17.x, the easier (and more likely) it will be to bring it up to date with the (still very early dev stage) update to v18.x (12/Bookworm based).

**Comment by derMart** [comment]
Thanks alot for the great and extensive explanation! I think this is a good kick start which could me get going, and, yes, my intention is to get bitkey(-ng) working on `17.x`, lets see how far I get. After looking at bitkey, I also see in the overlays a lot of physically copied programs. If I got that far, I would also plan to see how much of this I can get by standard apt packages to ease upgrades (thinking about chromium for example). But, OTOH, I only do care about bitcoin, so probably other crypto stuff won't get attention from me ;-)

> Personally, I'd be inclined to undo some of their changes and recombine it all back into common (some of their changes made in bitkey-ng have been made specifically to keep all the changes in one repo). OTOH our original intention was that we were going to also create TurnKey Desktop isos (i.e. not just servers) but Bitkey was the only one that ever got published. So perhaps until we actually look to revive that plan, perhaps keeping Bitkey in it's own repo might be a good idea?

TBH this is my first turnkey project (Btw: you seem to have quite some developer documentation about the internal structure of the build system which I really appreciate), so I am really not qualified for an answer to this question, but my 2c would be that it sounds good to have Bitkey as a case study for a desktop iso, once it is matured one can generalize that part out.

**Comment by JedMeister** [comment]
FYI I just tidied up and push my previous bitkey work to my personal GH:
- https://github.com/JedMeister/bitkey/tree/dev
- https://github.com/JedMeister/common/tree/bitkey-revival

And now I look a bit closer, I think I was wrong and it doesn't actually build an ISO. My suspicion is that bitkey-ng is probably closer to a building a working system.

I have also pulled bitkey-ng into a separate branch of my personal repo:
- https://github.com/JedMeister/bitkey/tree/bitkey-ng

Please note that I just checked out the latest `community` branch of bitkey, then copied the current HEAD of bitkey-ng in on top of it, committed and pushed. So none of the bitkey-ng commit history has been retained. I would rather not do it that way, but because bitkey-ng hasn't retained any of the bitkey commit history it's a real pain to pull the bitkey-ng changes back in as individual commits. And writing this now, I suspect that what I did wasn't quite right either (the repo probably still includes files that are no longer required and deleted in bitkey-ng).

Good luck and please feel free to ask for feedback and/or any questions you might have. I'd be particularly interested to hear about any docs that don't make sense and/or don't work as stated. If you have improvements to add, please feel free to open pull request(s) to the relevant repos. If you keep doc changes separate to any code changes that would be awesome (doc changes are easy to read through and approve - or not - code changes will require testing so may take longer).
