### ISSUE TITLE
Mumble v1.4 Update

### ISSUE THREAD

**Issue by BadCo-NZ** [turnkeylinux/tracker#1698]
Mumble has a new release, yaay!

Unfortunately there is no upgrade path, see issue [#5076](https://github.com/mumble-voip/mumble/issues/5076), and it requires you to uninstall the current version and install the new version.

I will attempt an update in the Mumble TKL and report back.

**Comment by BadCo-NZ** [comment]
Actually, just noticed that `mumble-server` is installed from Debian repos, which don't have the new version yet.

https://packages.debian.org/buster/mumble-server

**Comment by JedMeister** [comment]
It looks like Bullseye (base of upcoming v17.x) only has [1.3.4](https://packages.debian.org/bullseye/mumble-server) (which is somewhat expected - seeing as that's the nature of Debian `stable`).

So even if we change nothing, we'll get an update when we transition. But not to this latest version; unless of course someone backports it and we use the backport (although sid doesn't yet have this new version). 

I'm not a mumble user, but @OnGle is.

Is there significant value in using the newer version?

**Comment by JedMeister** [comment]
FWIW I was a little concerned that the Debian package might be abandoned when I noticed that th v1.4 issue you linked to was mid last year.

But then I just realised that they must have some funky versioning scheme as the first stable release of v1.4.x is [v1.4.230](https://github.com/mumble-voip/mumble/releases/tag/v1.4.230)?!

**Comment by BadCo-NZ** [comment]
> Is there significant value in using the newer version?

Yeah, there are some significant updates, most notably with the plugin system.
 
> But then I just realised that they must have some funky versioning scheme as the first stable release of v1.4.x is [v1.4.230](https://github.com/mumble-voip/mumble/releases/tag/v1.4.230)?!

The versioning is based on *major.minor.build*

https://www.mumble.info/blog/new-versioning-scheme/

**Comment by BadCo-NZ** [comment]
Could it be built manually and put in the TKL repo?

https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md

**Comment by JedMeister** [comment]
@BadCo-NZ - apologies on my slow response...

>Yeah, there are some significant updates, most notably with the plugin system.
>
>https://www.mumble.info/blog/mumble-1.4.230/

Ok, fair enough, although TBH it still isn't clear to me what additional value that brings, especially server side (everything I've read about plugins sounds like it's talking about the client side?!).

I also couldn't find any info on whether or not there is any limitations or issues connecting a v1.4.x client to a v1.3.x server?! I wouldn't be surprised if there are some limitations or perhaps it just doesn't work at all?!

But I'd like to be completely clear on what we're getting if we move from a Debian package to some other install method. An alternate install method means no auto/firstboot security updates (not that there have been any for mumble to date AFAIK). It also means greater maintenance burden for us and users, plus no automated update and/or migration if doing an "in place" Debian upgrade.

>The versioning is based on major.minor.build
>
>https://www.mumble.info/blog/new-versioning-scheme/

Yeah I gathered that, but it still struck me as weird because I'm used to seeing version numbers for new releases that end with zero (e.g. v1.4.0 - even if there is a build number at the end). Anyway, it looks like it's [because of Windows](https://www.mumble.info/blog/new-versioning-scheme/)...

>Could it be built manually and put in the TKL repo?
>
>https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md

It appears that we could, although I'd probably rather not if we can avoid it. Although it only explicitly notes Ubuntu (not Debian - also see my update below for more details...).

Plus it looks like they provide [pre-compiled static binaries](https://dl.mumble.info/stable/) (see mumble_server-1.4.230.x64.linux). Assuming that it "just works", my inclination would be to just use that (along with the [mumur.ini from their source code](https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini) (there is also a [config wiki page](https://wiki.mumble.info/wiki/Murmur.ini)). I also note that there is a [systemd service file](https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.service).

[update] So I probably shouldn't have (I've got lots of other stuff I should be doing...) but I've downloaded the precompiled static binary and tried to run it. It still requires some shared libraries, but they can be installed ok, except for the MySQL shared library (`libmysqlclient.so.21`). That isn't available in Bullseye (or Buster)?! It is in Sid (`libmysqlclient21` package) and I confirmed by installing it like this:
```
wget http://deb.debian.org/debian/pool/main/m/mysql-8.0/libmysqlclient21_8.0.23-3+b1_amd64.deb
apt install -y ./libmysqlclient21_8.0.23-3+b1_amd64.deb  
```
It appears to work, but I don't like that...

FWIW, I posted a fairly detailed "feature request" over on the Mumble issue tracker: https://github.com/mumble-voip/mumble/issues/5522

Even if they won't change their precompiled binaries, perhaps we can assist the existing Debian packager to update to the v1.4.x release? If so, and we can get v1.4.x into testing/Bookworm, then we can get it backported to stable/Bullseye.

**Comment by JedMeister** [comment]
Ok, so it looks like using their static binary isn't an option...

If we want v1.4.x we'll need to build it ourselves...

**Comment by BadCo-NZ** [comment]
Wow, sorry @JedMeister for sending you on such a tangent! I know how busy you must be with v17.

Yeah it is a shame about the static binary, but on the bright side I saw a mention of them building a docker image. It looks like the best way to go will to be migrating to my docker VM when that image is ready.

[docker image comment](https://github.com/mumble-voip/mumble/issues/5510#issuecomment-1019356787)

**Comment by BadCo-NZ** [comment]
Moved to a mumble docker container 

https://github.com/mumble-voip/mumble-docker
