### ISSUE TITLE
Zoneminder The latest release is v1.36.12 build here is v1.34.26

### ISSUE THREAD

**Issue by jimmystewart** [turnkeylinux/tracker#1701]
Would like to upgrade to stable release 1.36.12 but the apt-get Update and apt-get install zoneminder as instructed for updates does not work.  Can we get this in the next build release please?

**Comment by JedMeister** [comment]
Hi @jimmystewart - This is our issue tracker, for tracking bugs and feature requests. Generally support requests are best handled on our [forums](https://www.turnkeylinux.org/forum/support) (requires separate free website user account). I would argue that this is a support request rather than a bug.

Having said that, seeing as you're here now. The upstream Zoneminder apt repositories are version locked. So to get v1.36 you'll need to move to the v1.36 apt repository.

Here's how to do that:
```
sed -i "s|1.34|1.36|" /etc/apt/sources.list.d/zoneminder.list
```
Then the usual 'apt update && apt install zoneminder` will hopefully do the trick!?

Having said that, I'm not sure if just installing the newer 1.36 version package will "just work"?! The fact that they have the repos completely separated makes me wonder if in fact there is some process required to upgrade? I guess you could just try it and see. Although as per always with anything like this, ensure that you a tested backup and/or snapshot so you can roll back easily if things go pear shaped (personally I like to create a snapshot when doing stuff like this, but also have automated backups).

Also, out of interest, what additional value does v1.36 bring? I'm not sure if you are aware, but we are currently working on our v17.0 release (based on Debian Bullseye/11). I note that [Zoneminder docs](https://zoneminder.readthedocs.io/en/latest/installationguide/debian.html#easy-way-debian-11-bullseye) suggest for Bullseye, to install direct from the official Debian repositories. The official Debian repos only have [1.34](https://packages.debian.org/bullseye/zoneminder) (although there is a [backport of 1.36](https://packages.debian.org/bullseye-backports/zoneminder)).

FYI we installed from the Zoneminder repos for v16.x because it missed out on inclusion for Debian Buster/10 (what v16.x was based on). We were planning to move back to the Debian repos, as then we get auto security updates (the upstream repo doesn't differentiate between security update and non-security updates). Having said that, I'm not sure how many security issues Zoneminder has suffered from so not sure how much real value that gives?!

**Comment by JedMeister** [comment]
Also, I'll close this now, but please feel free to comment further. I'll see it and respond ASAP.
