### ISSUE TITLE
New appliance: ProcessWire CMS

### ISSUE THREAD

**Issue by daymickcorr** [turnkeylinux/tracker#1702]
HI, Ive created a new appliance for ProcessWire https://processwire.com/.

the appliance is mostly based off of drupal and wordpress. 

There is one thing i'm uncertain about it's the Non-interactive system initialization. I'm not sure what i need to add for it to be working correctly.

Thanks

**Comment by daymickcorr** [comment]
https://github.com/daymickcorr/tkl-processwire

**Comment by JedMeister** [comment]
Hi @daymickcorr 

Thanks for your contribution. This looks awesome (both the application and the appliance you've built for it). I have only skimmed over your code so far, but it looks good to me.

> There is one thing i'm uncertain about it's the Non-interactive system initialization. I'm not sure what i need to add for it to be working correctly.

So long as you only use the (relevant) default env vars (i.e. `APP_PASS`, `APP_EMAIL` & `APP_DOMAIN`) and ensure that any others you use have a sane default if run non-interactively you're all good. I note that [you are using `APP_PASS` & `APP_EMAIL`](https://github.com/daymickcorr/tkl-processwire/blob/master/overlay/usr/lib/inithooks/firstboot.d/40processwire#L7) so that should be all good.

The only thing is that we are deep in v17.0 development ATM (getting close to a stable release), so there will be a bit of a delay pushing this out (we're not doing any more v16.x releases). So when we do publish this it will be v17.0. From my quick glance over the code though, fingers crossed it should "just work". I'll try to do a test build over the next few days and let you know how that went...

**Comment by daymickcorr** [comment]
Thanks ! 

I appreciate the follow up for the non-interactive, I wasn't sure if I needed to add something from inithook.

I'm happy everything seems fine.

**Comment by daymickcorr** [comment]
@JedMeister Hi I've just realised i've built the appliance on turnkey-tkldev-17.0rc1-bullseye-amd64.iso.

**Comment by JedMeister** [comment]
Hi @daymickcorr - Awesome! That's great. So we know that it works for v17.0 then! :)

**Comment by OnGle** [comment]
I haven't actually tested yet just looking over the code. It's a very minor issue but it's a bit odd having `pwBootstrap.sh` with the `.sh` extension rather than a `.php` extension. Effectively it doesn't matter since it's got the shebang, but I think it'd self-document a little nicer with the relevant extension.

Otherwise I'm happy with the rest, inithooks, conf.d, apache2 conf etc all look good to me.

**Comment by daymickcorr** [comment]
@OnGle  The changes are done, they are in pull request

**Comment by JedMeister** [comment]
Thanks @daymickcorr - sorry that it's taken so long but I hope to add this in the next batch of v17.x apps that we publish. Unfortunately, I'm still bogged down behind the scenes, so I'm not 100% sure when I'll be ble to get back to publishing apps, probably not until next week...

**Comment by daymickcorr** [comment]
@JedMeister 
Thanks for following up, I'm eager to see this app published.

**Comment by JedMeister** [comment]
This should have been closed before v18.0 as it's initial release was v17.1.

TBH, I'm not sure how I missed that it was already released and repinned this issue to v18.0. Regarldess, we've now also done a v18.0 release.

Closing now.

FYI:
https://www.turnkeylinux.org/processwire
https://github.com/turnkeylinux-apps/processwire
