### ISSUE TITLE
Warning! Login failed. Please try again. after setup on the url ip:12321

### ISSUE THREAD

**Issue by rkbest13** [turnkeylinux/tracker#1705]
![image](https://user-images.githubusercontent.com/64113851/152089895-231650a2-c8ab-4c28-b68a-3f52b2133236.png)
I setup fileserver on LXC CT on proxmox and it seems to complete install. But I cant login with the correct samba user password  (root, and password). 
I tried multiple setup wondering if I might have forgot the password or typed wrong but the same error every time on the gui login page above. However, I am able to go the to https://IP/ itself with credentials. but the webpage is different than the screenshot on the LXC information page and I could not find any setup. as 
![image](https://user-images.githubusercontent.com/64113851/152090290-460d93f2-5a26-4187-91f5-a7285449a8e0.png)

**Comment by JedMeister** [comment]
Firstly, this is our issue tracker; for tracking bugs and feature requests. For general support, please use our [forums](http://www.turnkeylinux.org/forum/support/) (requires separate free website user account).

Regardless, while you're here I may as well respond.

So the core issue you are hitting is that the `root` Linux user and the `root` Samba user are NOT the same user account! Whilst they are mapped for the purposes of Samba shared files, the Linux and Samba user DBs are completely independent. Once upon a time Samba devs used to maintain a script which allowed the passwords to be synced, but that has been deprecated some time ago due to security issues.

FYI it is quite common these days for all Samba accounts to be linked to a single Linux `samba` user (and ACLs used to ensure that the relevant Samba user only has access to their own files). As using ACLs in a LXC container can be problematic, we've stuck with the legacy default of 1:1 Linux:Samba users

On a "proper" VM, the password set for the `root` Linux user is also set for the `root` Samba user. However, as the LXC guest `root` Linux user account is set at launch time, there is no way for us to sync them (hence why you need to see the `root` Samba user password on firstboot).

Webmin uses Linux user authentication (not Samba). So you need to login using the `root` user password you set when launching your container. If you used a keypair instead of a password, then ssh in as root and create a password like this:
```
passwd
```

**Comment by rkbest13** [comment]
Thank you!, But the issue is not with the webmin access as I am able to login with LXc root on shell, webmin page Control panel. The pass that was set for SAMBA at the setup time is the one that is not letting me log in. I believe the passwd reset password for the root LXC user and not samba. So maybe its a bug and that why I came here (i am not expert so apologize if I am wrong)
![image](https://user-images.githubusercontent.com/64113851/152650363-6e131268-44c2-4bf8-98a2-5890851b1b08.png)
Both the middle icons take me to webmin as this which probably is for webmin and not samba?
![image](https://user-images.githubusercontent.com/64113851/152650462-d2913641-5e5e-4cb1-a4c3-72525f103020.png)

**Comment by JedMeister** [comment]
@rkbest13

So you expected the "Samba conf via Webmin (requires login first)" to require the Samba root user password? It's just a shortcut to the Samba config section of Webmin. As it's still just Webmin, you still need to log in with the root user password. You noted that Webmin login with root Linux user works, so I would assume that link should work too?!

I had hoped that the text would make it obvious that it's a Webmin link, but clearly not. Do you have any suggestion to make it clearer?
