### ISSUE TITLE
Free Active Directory Server

### ISSUE THREAD

**Issue by fasi747** [turnkeylinux/tracker#1714]
I have a question I was working with this container and thought it to be an active directory server alternative that I can use in my network to centralize user accounts, but after working with it I think it is a file server that can join an AD domain?  am I right ?

Kind Regards
Faisal Gillani

**Comment by JedMeister** [comment]
Hi there,

For general support, please use our [forums](https://www.turnkeylinux.org/forum) (requires separate web site user account). This is our issue tracker for bugs and feature requests.

But seeing as we're here already, I'll answer you.

We have both a [Domain Controller](https://www.turnkeylinux.org/domain-controller) and a [Fileserver](https://www.turnkeylinux.org/fileserver). It is not recommended to use a DC as a fileserver as well, so you could use both. However, please be aware that our Fileserver appliance isn't pre-configured for that usage scenario.

 If you wish to use the Domain Controller, then I encourage you to install to a VM (rather than using it in a container). It can run in a container but requires tweaks so that it will work. The Fileserver should work fine as a container, although IIRC NFS won't work OOTB unless you make some tweaks on the host.
