### ISSUE TITLE
TKLDev install very slow on 2nd or 3rd round at same IP

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1729]
I built a TKlDev 17.1 with an overly small HD.  Crashed it building Core as I ran out of space.

Installed again on the same IP setup (Linode) and the (tkldev-setup) Downloading-bullseye-amd64 was very very slow (I thought it had hung, so I restarted...  Basically would not run core as (assumably bullseye), something anyway, was missing.

On the 3rd go round and again, Very Slow.  Seems to just be sitting there.
I am guessing there is some throttling taking place.  Should have likely used a different IP.

So, 2 things recomended.  
1:  Some sort of a progress indicator on tkldev-setup (series of periods .... for instance)
2:  Recomend not installing on the same IP if indeed this is the issue.

Sorry to top Issue #500 here.

**Comment by l-arnold** [comment]
Quite possibly was true.  Did a second build on a different IP and zoom.  The one that was going "oh so slow" did in the end finish.  It is building a Core now ...  Completed.
Second on is working on one as well.  Probably 30 minutes time difference between the two with the new IP build being faster.  Same memory/ HD space etc.

**Comment by JedMeister** [comment]
Only thing I can think is some sort of network congestion? Or perhaps throttling by Linode for some reason?

On face value I don't see how use of the same IP should make any difference? It seems very strange...

It's sounds like your original server never even completed it's first build?!

Just in case though, it is expected that the first build on a fresh TKLDev server will be notably slower. That's because it caches downloads. So subsequent builds of the same appliance should be much faster (little to nothing needs to be downloaded). Even subsequent builds of different appliances should be faster (as they share lots of the same packages).

But beyond that, if it's the same specs, runing in the same (or very similar) physical location, it should act the same. There will probably always be some difference due to network peculiarities, but generally it should be unperceptible (apparently there needs to be ~10% difference before we notice).

**Comment by l-arnold** [comment]
I was thinking Network throttling by the bullseye.bootstrap (I missed the description).
You are correct that the 2nd install never completed.
The first, not having enough space, is the issue I need to do a few tweaks to Linode (using their SDA drive structure instead of the TKL built sub-images...  Getting there.
I will close this but I recommend noting something to the effect of not to "install in the same ip".
Closing this one.

**Comment by l-arnold** [comment]
I note also that there was some reference to the "bullseye.bootstrap" from Yannick on the forums...  don't think it was called from his repository but perhaps.  Anyway, 2 installs had very different results.  This was "tkldev on tkldev" built.
