### ISSUE TITLE
Docker Swarm mush routing not working, and  port 4789 is blocked by iptables rules

### ISSUE THREAD

**Issue by Elwafi-Elmehdi** [turnkeylinux/tracker#1745]
## Ingress Network not working

I have a **proxmox** cluster and i decided to run **docker** insides **lxc containe**r I choose **turnkey-core** after installing docker on containners and declaring a swarm, I first noticed that the services are not exposed by any node and only when I publish ports via host mode the service in available, I did some networking auditing and I found that port 4789 is blocked by iptables configuration.
and proxmox firewall is down, i run a small homelab and i have no firewalls installed , and also there is no rules on my commercial router.

Proxmox is isntalled with defaults no firewall or network  customization 
The docker swarm is composed of 3 managers and 5 workers

### Configuration 
**Proxmox**         : 7.2.3
**LXC Template** : Turnkey-core Debian 10 6.1-1
**Docker**            : 20.10.17, build 100c701
**Iptables**           : 1.8.2

### Troubleshooting 
```
$ nc -z -v 192.168.1.25 4789
192.168.1.25 4789: Connection refused
$ nc -z -v 192.168.1.26 4789
192.168.1.25 4789: Connection refused
$ nc -z -v 192.168.1.27 4789
192.168.1.25 4789: Connection refused
```

### Iptables
**Manager 1**
```
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A DOCKER -d 172.18.0.4/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 9443 -j ACCEPT
-A DOCKER -d 172.18.0.4/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 9000 -j ACCEPT
-A DOCKER -d 172.18.0.4/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 8000 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker_gwbridge ! -o docker_gwbridge -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN 
```
**Manager 2**
```
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker_gwbridge ! -o docker_gwbridge -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
```
**Manager 3**
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```
**Nodes** 
```
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker_gwbridge ! -o docker_gwbridge -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
```

**Comment by JedMeister** [comment]
My guess is that you are hitting the limitations of nested Linux containerisation and that it has nothing specifically to do with Proxmox or TurnKey (and is more to do with general Debian - the base of both PVE & TKL).

First it's worth noting that whilst the config and context is a bit different, LXC and Docker are more or less the same thing. The only difference of significance is that an LXC container is (mostly) a full OS and acts somewhat like a normal VM (whilst leveraging the host's kernel and low level resource management). Whereas Docker containers only have a minimalist base - usually with only the specific dependencies for a particular application installed. LXC provides an OS, Docker provides a minimalist application environment. I'm guessing that you already knew that, but I wanted to note it to ensure we're on the same page.

TBH, I haven't tried running Docker within LXC, but AFAIK, it should be possible (just as nesting LXC within LXC is possible). However, the devil is in the detail. I suspect that a privileged (LXC guest/Docker host) container would be required to run Docker inside (it is to nest LXC). But because of systemd hardening and the limitations of containerisation, by default, Debian (the base of TurnKey) doesn't really like running unprivileged. You will need to manually adjust some systemd unit files (i.e. remove the hardening) to ensure that all services run cleanly (some will work fine without tweaking, but some will refuse to start with default config).

I have 0 experience with Docker swarm, but my guess is that a required service (the one that should be listening on port 4789) isn't running (has crashed or can't start). 

Personally, I have little interest in Docker, but I do have a [TurnKey Core](https://www.turnkeylinux.org/core) VM (installed to KVM from the Core ISO) with Docker installed. I use that for running any Docker containers I wish to run. On the rare occasion I do wish to use docker, it "just works"...

So what you want should be possible, but will take some time and effort on your part to get it working properly. If you want to just get on with it and get to your end goal, just install a full VM as a Docker host.

**Comment by JedMeister** [comment]
PS if you do get it working, please share the required steps so that we can document it for others.

**Comment by Elwafi-Elmehdi** [comment]
@JedMeister Thanks for your intereset,,I really appreciate your time and efforts, I gave up running docker in LXC after reading and reading,and as you said docker better be ran on VMs, I was able to get rid of LXC's, because I manage Proxmox with Terraform, so now I am planning to run docker on VMs even thought I would shrinking the swarm to 3 nodes (1 manager and 2 nodes), but I guess that will give me enough place to play with docker swarm.

**Comment by JedMeister** [comment]
No worries @Elwafi-Elmehdi. Glad you've got something that works for you.
