### ISSUE TITLE
Plugins do not work at Mediaserver 16.1

### ISSUE THREAD

**Issue by fdfytr** [turnkeylinux/tracker#1749]
Additionally installed plugins from stable Jellyfin rep  do not work
Error message
```
Alert
This plugin has no settings to configure.
```

Proxmox 7.2 privileged container

**Comment by JedMeister** [comment]
Hi @fdfytr - I wonder why that is?

We install Jellyfin from the "official" Jellyfin Debian apt repo so I would expect "officially supported" Jellyfin plugins to "just work".

Perhaps you need a specific Jellyfin version for the plugin to work? Maybe try upgrading Jellyfin first to ensure you have the latest version? I.e. try this:

```
apt update
apt install -y jellyfin
```

If none of that works, could you please explicitly explain how I can reproduce your issue (i.e. which plugin to install, what is the install process). FYI, I personally use a local Mediaserver instance myself but it's a default install with no additional plugins installed.

**Comment by fdfytr** [comment]
> apt install -y jellyfin

```
apt install -y jellyfin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-server (>= 10.8.4-1) but 10.7.2-1 is to be installed
            Depends: jellyfin-web (>= 10.8.4-1) but 10.7.2-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by JedMeister** [comment]
Ok, it appears that there is an issue [upgrading Jellyfin](https://github.com/jellyfin/jellyfin/issues/7742). I've just confirmed a workaround (which I've also [posted over there](https://github.com/jellyfin/jellyfin/issues/7742#issuecomment-1223385609)):
```
apt update
apt install -y jellyfin-ffmpeg5
apt install -y jellyfin-server=10.8.4-1 jellyfin-web=10.8.4-1
apt install -y jellyfin
apt-mark auto jellyfin-web jellyfin-server jellyfin-ffmpeg5
apt autoremove
```
Note: the `apt update`, the `apt-mark` command and the final `apt autoremove` are not required strictly speaking. Obviously if you've recently run `apt update`, you don't need to rerun it. The `apt-mark` command just ensures that the Jellyfin dependencies are marked as "automatically installed" (because we actually manually install them; changing them to auto will mean that they will appear available to "autoremove" if/when the `jellyfin` package is removed). The final `apt autoremove` will remove any "automatically installed" packages (by default should only be `libdrm-intel1` & `libvdpau1`).

After you've done that, double check `apt policy jellyfin*`, the output should look like this:
```
jellyfin-web:
  Installed: 10.8.4-1
  Candidate: 10.8.4-1
  Version table:
 *** 10.8.4-1 100
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
jellyfin-ffmpeg:
  Installed: (none)
  Candidate: 4.4.1-4-buster
  Version table:
     4.4.1-4-buster 10
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
     4.3.2-1-buster -1
        100 /var/lib/dpkg/status
jellyfin-server:
  Installed: 10.8.4-1
  Candidate: 10.8.4-1
  Version table:
 *** 10.8.4-1 100
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
jellyfin-ffmpeg5:
  Installed: 5.1-2-buster
  Candidate: 5.1-2-buster
  Version table:
 *** 5.1-2-buster 100
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
jellyfin:
  Installed: 10.8.4-1
  Candidate: 10.8.4-1
  Version table:
 *** 10.8.4-1 500
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by fdfytr** [comment]
> apt update
> apt install -y jellyfin-ffmpeg5
> apt install -y jellyfin-server=10.8.4-1 jellyfin-web=10.8.4-1
> apt install -y jellyfin
> apt-mark auto jellyfin-web jellyfin-server jellyfin-ffmpeg5
> apt autoremove

I managed to update everything per instructions but now has black screen on jellyfin webpage

**Comment by fdfytr** [comment]
thank you, issue sorted
