### ISSUE TITLE
New installation All lists empty (No matching records found)

### ISSUE THREAD

**Issue by zerofruchtshake** [turnkeylinux/tracker#1781]
Hi, on my fresh install i can not add anything to the inventory / consumeables / .. 
it says " Success: Consumable created successfully. " but nothing is visible in the lists.
![Bildschirmfoto 2022-11-30 um 17 07 19](https://user-images.githubusercontent.com/44063194/204849739-6a7104b8-b2d8-4504-9548-95447d28fdee.jpg)
additionally, categories/tags/... are not loaded in the forms

![Bildschirmfoto 2022-11-30 um 17 08 30](https://user-images.githubusercontent.com/44063194/204849922-1464aebc-21e1-4f07-9990-ae28621c49ef.jpg)

**Comment by zerofruchtshake** [comment]
EDIT: reverse proxy issue, seems to be resolved.
see https://snipe-it.readme.io/docs/reverse-proxies

**Comment by JedMeister** [comment]
@zerofruchtshake - apologies on slow response. Thanks for reporting your issue and even better that it turned out not to be our fault and you worked it out!

Please don't hesitate to open an issue if you hit anymore. Also, please feel free to share any feedback you have, especially if you have ideas for making things better. And/or if you're after support at all, please feel free to post on our [forums](https://www.turnkeylinux.org/forum/support) (new threads require a free website user account). Please note that we've been hammered pretty hard by spammers lately, so please ignore any spam threads and just start a new one (the spam gets cleaned up a couple of times most days).
