### ISSUE TITLE
Website detailed description inconsistent with appliances' respective README files.

### ISSUE THREAD

**Issue by NitrogenUA** [turnkeylinux/tracker#1789]
I was tiding up READMEs for these 3 appliances: [fileserver](https://github.com/turnkeylinux-apps/fileserver/pull/11), [mediaserver](https://github.com/turnkeylinux-apps/mediaserver/pull/25) and [torrentserver](https://github.com/turnkeylinux-apps/torrentserver/pull/16) and noticed that their description pages aren't perfectly consistent with their respective READMEs. I am guessing READMEs are basically used for by-hand copy-pasting onto website. Still might be worth synchronizing the two.

For example the typo I was fixing in README isn't there on [torrentserver](https://www.turnkeylinux.org/torrentserver) page, but still present for the other two. [Fileserver](https://www.turnkeylinux.org/fileserver) and [torrentserver](https://www.turnkeylinux.org/torrentserver) pages still have bullet-point regarding user accounts sync between Samba and PAM, while these points were removed from respective READMEs.
There's also slight discrepancy in fileserver's intro section where it reads "Based on Samba and WebDAV CGI." and "Based on Samba and SambaDAV." in README. ~~No idea which one is correct.~~
Upon [further inspection](https://github.com/turnkeylinux-apps/fileserver/pull/3) website has correct info in this instance.

**Comment by JedMeister** [comment]
Thanks for reporting this. You are absolutely right and it's a bit of an issue TBH. Historically, each website appliance page was built from the relevant README. In fact at one point, there was a cron job on the webserver to sync the readme automagically. I'm not sure what broke and/or why that was disabled/stopped working (it was before my time managing the webserver).

Initially I did manually update the appliance pages semi-automatically (i.e. generated html from the readme.rst) for a while, but there were some bugs, and I didn't have the spare cycles at the time to fix the bugs, so I just manually made the changes. Since then, updates to appliances pages have been very ad hoc. Sometimes that have been semi-automatically generated (when the bug doesn't crop up), sometimes just manual updates... It's pretty sub-optimal and needs to be addressed, but it's mostly felt like a "minor" issue, so has never been properly addressed.

It will need to be addressed when we update the website (as I think I mentioned somewhere else). In the meantime, I'll regenerate the html for the 3 you've updated and bring the readmes and app pages back into line!

**Comment by JedMeister** [comment]
I suspect that there may be bits I've missed and I'm almost certain that there are pages that are still significantly out of sync. Although in an effort to do justice to your efforts, I've merged your PRs and manually made some tweaks to the website pages to bring them back in line (at least close...).

So whilst this issues still exists to some degree, I'm going to close it. If you find any more that are clearly (significantly) out of sync, please do not hesitate to reopen this issue (and add details) or open a new one if you'd rather. Thanks again for all your contributuions!
