### ISSUE TITLE
Just an alert/ archive.turnkeylinux.org is down , forums are being spammed.

### ISSUE THREAD

**Issue by White-Raven** [turnkeylinux/tracker#1790]
Sadly @turnkeylinux on twitter is MIA since 2017, and aside from forums and here, I don't really know where to send of a warning.

- archive.turnkeylinux.org:80 (54.83.15.172) has been down
- the turnkeylinux.org/forum/ has been getting spammed hard by fake airline phone numbers, antivirus norton support, etc, up to the 9th page of support and 8th page of general

for around 6 hours at the time of writing.

Dunno if people behind the scene have been alerted, turnkeylinux.org isn't communicating on it since you have seemingly no socialmedia outlet, so here I am.

**Comment by jberends** [comment]
I have the same problem archive.turnkeylinux.org is down

**Comment by White-Raven** [comment]
I mean... _everyone_ has the same problem. The domain is down, so you can't visit it, and `$apt update` on turnkey containers will just crap out.

**Comment by White-Raven** [comment]
Update I saw just now: 

- archive.turnkeylinux.org:80 seem to be back online, so yeay repos!
- the forum is being cleaned up. General is already done, _Support still to do_ edit scratch that I see it being cleaned before my own eyes

Nice!

**Comment by JedMeister** [comment]
Hi @White-Raven & @jberends , I hope you're having or have had a lovely Christmas.

Apologies on such a slow response. Obviously the apt archive is fixed now. FYI it appears it was either attacked, or at least flooded by a poorly coded bot. The webserver stood up for a while, but eventually crashed.

We do have plans to move the apt archive to an AWS S3 bucket, which should make it more reliable (it's not too bad, but we have had a few outages over the last couple of years). I'll also ensure IPv6 support too (which is so overdue it's not funny). No ETA but it is the backlog (with the other 50 million things...).

Unfortunately, the "fake airline helpline" spam on the forums is a recurring issue for the last month or so. It has been joined by similar looking "fake cypto exchange helpline" spam and others in more recent weeks, although the airline stuff still makes up the bulk. They do seem to be giving us a rest for the last day or so, but my guess is that they're human spammers, so perhaps have a few days off over Christmas?! I suspect they're human because they evade all our anti-spambot measures and post times are pretty fast, but not as fast as a bot would - more like copy/paste speed. I have thought about writing a simple script to run on a cron job, as I reckon the wording of the posts could be easily matched with limited risk of false positives. But I just haven't sat down and written it...

FTR, the forums are probably the best place to report stuff like this. I usually only (batch) respond to posts once every weekday or so, but I check the forums at least once most days. I clean up any spam I see and will at least see the subject of any new (non spam) forum posts - so make your forum thread subject/title count! :)

Possibly the best place to get my attention though is via email: support@turnkeylinux.org.

I do try to check in here (i.e. GH) every few days, but my GH notifications are out of control so I rarely ever notice GH related stuff until I explicitly come here to check.
