### ISSUE TITLE
Zoneminder 1.34 has long been deprecated. Has multiple CVEs.  Upgrade to 1.36 series.

### ISSUE THREAD

**Issue by connortechnology** [turnkeylinux/tracker#1791]

**Comment by JedMeister** [comment]
Hi there. Thanks for your report, but which software are you referring to? We provide ~100 appliances so version numbers don't help me much.

**Comment by connortechnology** [comment]
ZoneMinder.

**Comment by JedMeister** [comment]
Right you are! Thanks for your report. We really do need to do a better job of tracking CVEs in third party software...

On the plus side, until we rel;ease an updated app, upgrading Zoneminder on an existing appliance should be an `apt install -y zoneminder` away...

**Comment by JedMeister** [comment]
Hi @connortechnology 

Apologies, I just realised that I hadn't posted back on this issue. FWIW, the v17.x Zoneminder appliance installs Zoneminder from the [official Debian repos](https://packages.debian.org/bullseye/zoneminder). As per other software from default Debian repos, serious security issues are patched via backported security patches.

Whilst there are still [open CVEs against it](https://security-tracker.debian.org/tracker/source-package/zoneminder), the Debian security team has deemed them "unimportant". Looking a little deeper, it appears that they are either relatively minor, or require authentication first (so can only be exploited by someone who can legitimately log in). So by default (with a single admin user) the current CVEs all appear to be irrelevant.

Having said that, [v1.36.26 is currently available via backports](https://packages.debian.org/bullseye-backports/zoneminder). So if you want a newer version, you can install it like this:

```
mv /etc/apt/sources.list.d/debian-backports.list.disabled /etc/apt/sources.list.d/debian-backports.list
apt update
apt install -t bullseye-backports -y zoneminder
```

I've decided that for now I'm just going to leave it with the default version (v1.34). My rationale is that if a new CVE is discovered which is critical or important and also affects v1.36, then the default version will get a timely security update. The backport may not (technically they should have sec issues fixed, but backports isn't as tightly controlled or monitored like the main repos are).

Thanks again for reporting, but I'm going to close this one for now.

**Comment by connortechnology** [comment]
Okay. I'm gonna blow this up via social media. This is unacceptable.

**Comment by JedMeister** [comment]
Hi @connortechnology 

Thanks for pushing back. Although in future, I'd much prefer something a little more constructive rather than a threat if possible. FYI something like "I don't think that you are taking these security concerns seriously enough, please reconsider your position" would have also worked (and would have made it easier for me to hear).

I also wasn't aware that you were a ZoneMinder dev - that would have also added useful context for me! (And added weight to your opinion).

Whilst your response initially got my back up a bit and part of me wanted to just tell you to f*** off, I pride myself on constantly striving to be more emotionally intelligent. So I took a few deep breaths and took your charged response as fuel to dig in a little deeper.

On closer inspection, I noticed that there was a [`README.Debian.security` file](https://salsa.debian.org/debian/zoneminder/-/blob/master/debian/README.Debian.security) (which I really should have noticed before). That gives the full context of the Debian Security Team's position. In retrospect, it's a real pity that I missed that when I was looking at this issue yesterday. It likely could have saved both of us a little angst.

After reading the `README.Debian.security`, I had a closer look at the actual CVEs.

With the added context that you are a ZoneMinder dev (and clearly have an understanding of the CVEs), and the Debian Security Team's stated limitations, it's clear to me that we need to do one of 2 things:

- warn users more explicitly that it should only be used on a LAN; or
- we need to install a newer version
 
So I'm going to reopen this issue and retag it with security - at least until one of those is done.

Having rethought this, I do think that the best approach is to install a newer version and re-release (as I had originally intended to do yesterday).

In my previous post, I pointed out that there is a newer version of Zoneminder in backports (v1.36.26), but that too has a number of CVEs (and obviously that Debian readme applies there too). I note that the latest version (released by you! :smile:) is [v1.36.32](https://github.com/ZoneMinder/zoneminder/releases/tag/1.36.32).

I'm not a Zoneminder user myself, so I'd really appreciate your input on this one. If possible, I'd prefer to install via an apt repo, as then it's easier for everyone to update. <s>I also note that [install instructions for Debian Bullseye](https://wiki.zoneminder.com/Debian) (linked from the [ZoneMinder downloads page](https://zoneminder.com/downloads/)) do not use the zmrepo apt repo? But it does appear that the zmrepo apt repo does have [Bullseye packages](https://zmrepo.zoneminder.com/debian/release-1.36/bullseye/) for v1.36.x?!

Is there any reason why we shouldn't install from the zmrepo apt repo?

If that's not recommended, what would your recommendation be for install method? Source code install?</s>

[update: apologies for the noise, I just reread the wiki page properly and I can see that it actually does use the repo - Doh! So I'll use that as the install source...]

If you have any other feedback, please feel free to share.

**Comment by connortechnology** [comment]
Hi @JedMeister thanks for being awesome, and sorry I wasn't more awesome.  

I tend to get to these things late at night when perhaps my emotional energy is not at it's best. I get careless.

I'm going to come back to this in the morning, for a fuller response. I'd like to work with you to ensure that anyone running ZoneMinder is getting the best experience, and can trust their install.  Which is why we create ZoneMinder.  To give people a VMS they can trust.

**Comment by JedMeister** [comment]
Thanks for that @connortechnology. TBH this response really made my day! :smile: (And made me extra glad that I took a few deep breaths before responding - I almost certainly would have made a complete dick of myself otherwise...)

Anyway, it sounds like we're ultimately on the same page. I look forward to your further comment.

To perhaps save you a little typing, unless you have good reason not to, I'm planning on using the zmrepo apt repo you provide - and install the latest Zoneminder version from there. Happy to hear any pointers or advice on that.

**Comment by connortechnology** [comment]
I think that's the best plan.  It's why we do it.  Debian's policy choices don't always make for the best user experience.  
Eventually I want to move all packaging to zmrepo, as ubuntu ppa's can be slow to build if they are busy.

Current stable release is 1.36.32, I hope to release 1.36.33 soon, just waiting on one potential issue.

You might consider a choice of installing the development version 1.37.*, but that's up to you.

**Comment by JedMeister** [comment]
Thanks @connortechnology

I'll update the build code of our ZoneMinder appliance accordingly. Once I've got there I'll see where I'm at and if I can, I'll probably wait for the new release before I build it (thanks heaps for the heads up on that too!).

As for the dev version, I'm not sure, but I'll think about that. At the very least, I'll try to make it really easy for users to upgrade to it.

**Comment by jimmystewart** [comment]
I am so glad someone is looking into this.  I asked for this upgrade back in Sept 22 and was pushed back. 
Thank you for fixing the upgrade.  Ver 1.34 will no longer update and it has issues.

**Comment by Christie018** [comment]
> Right you are! Thanks for your report. We really do need to do a better job of tracking CVEs in third party software...
> 
> On the plus side, until we rel;ease an updated app, upgrading Zoneminder on an existing appliance should be an `apt install -y zoneminder` away...

That's on me boss, I have been so sidetracked I didn't prioritize this as it should be. I'll work more on these going forward.

**Comment by JedMeister** [comment]
It's not your fault @Christie018. We don't have a good consolidated way to track CVEs on the software we include, but we should...

**Comment by connortechnology** [comment]
Just a heads up, 1.36.33 finally got released.  Some very serious CVE's were found in a capture-the-flag event.

https://github.com/ZoneMinder/zoneminder/releases/tag/1.36.33

**Comment by JedMeister** [comment]
Thanks @connortechnology - I'll rebuild it and it should hopefully be published within the next week.

**Comment by JedMeister** [comment]
BTW, that's a pretty epic list of closed bugs! Well done to you and your community! :grin:

**Comment by tokenwizard** [comment]
FYI, I found this thread because I was looking for a way to update ZM in my Turnkey install. Seeing that the plan was to use the zmrepo versions, I just pulled these steps from the Official Debian install script and ran them in my existing 1.34 install. 

After the below steps, I then rebooted my Proxmov LXC and all seems to be working well on v1.36.33!

```apt install -y lsb-release gnupg2
echo "deb https://zmrepo.zoneminder.com/debian/release-1.36 "`lsb_release  -c -s`"/" | sudo  tee /etc/apt/sources.list.d/zoneminder.list
wget -O - https://zmrepo.zoneminder.com/debian/archive-keyring.gpg | sudo apt-key add -
apt update
apt install -y zoneminder
