### ISSUE TITLE
Invoice Ninja - Can't preview & print PDFs

### ISSUE THREAD

**Issue by tjwelde** [turnkeylinux/tracker#1794]
Using the 17.2 lxc template in proxmox (which can be downloaded directly via their web UI), I can't preview or print PDFs.
The original error states, that `libnss3` is missing. Installing that shows more dependencies missing. 
The following thread helped with installing all the necessary dependencies: https://forum.invoiceninja.com/t/new-install-cant-print-dl-invoices/12193/6. After that I was able to view and print PDFs. 
The person there said, that they made a PR, but I couldn't find it.

**Comment by JedMeister** [comment]
@tjwelde - Argh! That sucks, especially as v17.2 was a "bugfix" release to resolve a raft of bugs/missing features (in v17.1). I'm sure that I tested PDF generation, but clearly I missed something along the way...! :sob: 

Regardless, thanks so much for reporting. bonus points for all the info you've provided.

**Comment by JedMeister** [comment]
FWIW I found the PR: https://github.com/ikidd/invoice-ninja/pull/1 It looks like they accidentally opened the PR against their own fork, rather than TurnKey (easy mistake to make, I've done it a few times myself).

I'll rework it a little as it includes a number of packages that are already included by default (so are redundant in the plan).

I plan to rebuild with the next batch of v17.x appliances - hopefully within the next week or 2.
