### ISSUE TITLE
Set hostname via ConfConsole "advanced" option

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#180]
I think it would be sweet if you could set the hostname of the server via inithooks/confconsole. It could then either be preseeded or set at from the advanced menu of confconsole (defaults to current predefined hostname).
##

**Comment by JedMeister** [comment]
Will probably be one of the "advanced" inithooks (#369)

**Comment by JedMeister** [comment]
Would be best to have a non-interactive inithook and an option to interactively set within confconsole "advanced" options.

**Comment by JedMeister** [comment]
Added @DocCyblade for testing for v14.2

**Comment by DocCyblade** [comment]
@qrntz - Let me know how you would like me to test this. I could create a mock build from say core or lamp and inject the test version in, and test it that way, or just install it on a existing install and try to break it! I also want to build my own "plug-in" to test that functionality as well. I have not really looked too much into the code yet, how does it keep track that a run once function has been run, so I can reset it and have it run again.

**Comment by qrntz** [comment]
Sorry, I missed this one in the recent bout of notifications (GH doesn't seem to distinguish mentions from watched issue notifications… at least for me).

@DocCyblade, I think both ways should work equally well. I just purged the confconsole package and launched confconsole from the Git repo when I was testing because it doesn't seem to affect anything outside its own directory.

AFAIK confconsole as it is currently doesn't keep track of plugins between launches. However each plugin can have a `doOnce()` and a `run()` where the former is executed just once (in the confconsole executable's running lifetime) if the plugin needs some initialization steps, and the latter is executed each time a plugin is invoked via the menu. A good starting point would be https://github.com/turnkeylinux/confconsole/blob/a1c979b03f49e17bde11c52174ff4d96e4e2d14d/plugins.d/example.py

**Comment by DocCyblade** [comment]
@qrntz - I had a go with the hostname setting. I selected the option, and tried to cancel. Said it was updated (I did not put anything in the box!) 

I used the same setup as https://github.com/turnkeylinux/tracker/issues/546#issuecomment-265051242


Do you want me to open up new issues to keep track or just post my findings in the issues that are related such as the Let's Encrypt and the Hostname issues or should I open new ones and prefix them with ConConsole Testing: xxxxxx

**Comment by DocCyblade** [comment]
@qrntz - When I do put a hostname in, it does indeed change the name, but confconsole it's self needed to be restarted. Not sure if you can re-read the host name on the menu so it's an immediate on the confconsole.

**Comment by JedMeister** [comment]
@DocCyblade - your recent post suggests to me like the confconsole plugin system itself may benefit from some tweaking?! 

Re flagging issues - in some ways it'd be nice (and neater) to keep stuff together (in a single issue). However seeing as the work was split - between Anton (some plugins) and Stefan (the plugin system itself) it would probably makes it easier to direct to the right person if a new separate issue is created for each bug you encounter. That will also ensure that nothing gets forgotten or accidentally overlooked...

**Comment by JedMeister** [comment]
Following recent discussions with Alon & Stefan, we are currently thinking it may be best to defer non-interactive confconsole functionality for 14.2. We may have time to squeeze it in, but it's not currently working as it should and we don't want to block v14.2 release unless we really have to...

**Comment by JedMeister** [comment]
Actually, I'm closing this now, as it's essentially a duplicate of #450
