### ISSUE TITLE
TKLBAM,  Hub Snapshot, new Server reverts Debian Version in Hub View

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1818]
So,  I kept wondering why some of my builds were showing TKL 17.1 in the hub while others were showing 16.1 though they were originally 17.1.

Just traced back.  What was showing in the Hub as TKL Odoo 17.1 build, when "Launch New Server" from Snapshot is used,  the New Server ends up showing Odoo 16.1.1 build in the Hub View.

- Just opened the snapshot generated build and Webshell FB shows:
- "Welcome to Odoo, Turnkey GNU/Linux 16.1 (Debian 10/Buster)"
- 
- Just booted the "source" and I find that it also is showing the same (16.1, not 17.1) in Webshell (SSH).

so I started thinking about cause.  Perhaps it was my --skip database Tklbam-Restore which I ran on that Server set early in the process.

That in turn had me check a "raw" 17.1 Install that had not had TKLBAM restore run

- TKL Odoo 17.1 shows in Hub View and in WebShell.

Launch a new server from the one Snapshot.

- TKL Odoo 17.1 shows in Hub View and in Webshell

This leaves one question.
When a TKLBam-Restore is run over a 17.1x System from a 16.1x Backup Image,  Does the Debian and whole build change?  I had though that only the files, and perhaps the database changed.  
(* I have still not been able to get TKLBAM to move Odoo Data correctly, but files seem to move ok). 

"Sometimes it makes sense to just start over" was a saying that popped up today.  In this situation, I am going to go with that as I have other issue in the build anyway.

It is still a great system.

**Comment by JedMeister** [comment]
Firstly, in the context of the Hub, snapshots and backups are very different things.
- A snapshot is like a disk image. It is a copy of the whole OS and all of it's data.
- A backup (i.e .a TKLBAM backup) is just the data, (somewhat) separated from the OS. Some of the data contained maybe only relevant to the OS version it came from, but mostly it should be somewhat generic. For the expectations for restore that you can have of a TKLBAM backup, please see the [TKLBAM doc page](https://www.turnkeylinux.org/docs/tklbam). Whether or not a TKLBAM backup will restore cleanly and properly on a newer major version will depend on the software installed (e.g. in this case Odoo).

As such, if you launch a new server from a snapshot of a v16.1 server, then the new server will still be v16.1. That is expected behaviour.

The fact that the Hub displays v17.1 when the server is from a v16.1 snapshot (so is actually v16.1) is a bug. Although TBH, I'm not 100% sure how we would be able to work out what the real version (inside the snapshot) is? That's something to consider though.

Restoring a v16.1 TKLBAM backup to a v17.1 server is a completely different matter. You should end up with a v17.1 server with the data from your v16.1 backup. Additional steps required to get the old data working on a new instance will depend on the changes between the version the backup came from and the version that is being installed.

**Comment by l-arnold** [comment]
I was probably not clear.
I was trying to run new 17.1 servers..  but they were down stepping through  the process.  Was strange in that sometimes the Hub showed one generation but the SSH header was showing a different generation.  It did seem that something was taking place on subsequent snapshot restoration to move both down to 16.1.

This was complicated by a "way back" tklbam-restore where I was trying to move a number of modules forward from 16.1.  Then there was a migration to a different AWS account for a client, and the AWS image was running 16.1...  Then a migration of that into the Hub ...  I am guessing that AWS AMI image and subsequent snapshots, was a good boat anchor..  probably the root of a lot of this now that I think of it.

We can likely close this unless it arises again.

**Comment by l-arnold** [comment]
Closing for now.  Too many variables.  Should be broken into separate issues.  Mostly Tklbam generation migrations and having Full version updates on different build platforms be available (ie TKL Hub being the Same as AWS AMI).
All systems were working as worked through in this specific situation -- simply was not clear as to what generation builds were actually in place in their workings.  Seems best to trust the SSH Banner indicators.

**Comment by JedMeister** [comment]
Ok thanks @l-arnold. I think you are right re "breaking it down" a bit into smaller specific issues.

But please do not hesitate to open a new issue (or more as relevant) when you next hit something like this. Love your work mate. Take care and chat more soon.
