### ISSUE TITLE
hostname removed from network interfaces file on Proxmox LXC guests

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1832]
@LubomirH has [reported](https://github.com/turnkeylinux/confconsole/pull/69) that the `hostname` line for the main interface (`eth0`) was removed from the `/etc/network/interfaces` file on their TurnKey LXC guest.

<s>I'm unclear whether that was caused by Proxmox or old (buggy) Confconsole, although it does seem possible that it may be Proxmox?</s>

[update: [upstream issue](https://bugzilla.proxmox.com/show_bug.cgi?id=2838) - thanks @NitrogenUA]

If it was Proxmox, then it seems, at least in part, that it is a bug. According to [Proxmox docs](https://pve.proxmox.com/wiki/Linux_Container#_guest_operating_system_configuration), Proxmox modifications should be be noted as such:
```
# --- BEGIN PVE ---
<data>
# --- END PVE ---
```
And that doesn't seem to be happening.

I've tagged this upstream but it really requires more investigation. If we can confirm that it's introduced by Proxmox, then I'm sure that we could discuss it with them and make some improvements.

This bug is related to https://github.com/turnkeylinux/tracker/issues/1833

[update] I've had a quick poke around Proxmox and it appears this is the code that configures Proxmox LXC guest config: https://git.proxmox.com/?p=pve-container.git;a=blob;f=src/PVE/LXC/Setup/Debian.pm;hb=refs/heads/master

**Comment by JedMeister** [comment]
FWIW, in an existing v17.x TKL LXC container I have hanging around, I did some simple testing. I removed the `/etc/network/interfaces` file altogether and rebooted. When it came back up it had a new interfaces file - and it didn't include a `hostname` entry:
```
auto lo
iface lo inet loopback
iface lo inet6 loopback

auto eth0
iface eth0 inet static
	address 192.168.1.124/24
	gateway 192.168.1.1
```
However, I then manually add a `hostname` entry to the interfaces file and rebooted again:
```
auto lo
iface lo inet loopback
iface lo inet6 loopback

auto eth0
iface eth0 inet static
	hostname tester
	address 192.168.1.124/24
	gateway 192.168.1.1
```
When it rebooted, the location of the hostname entry had been moved (from the top to the bottom), but it is definitely still there!?:
```
auto lo
iface lo inet loopback
iface lo inet6 loopback

auto eth0
iface eth0 inet static
	address 192.168.1.124/24
	gateway 192.168.1.1
	hostname tester
```

**Comment by NitrogenUA** [comment]
@JedMeister That sounds about right! I've looked at Proxmox code and for [dhcp/manual](https://github.com/proxmox/pve-container/blob/master/src/PVE/LXC/Setup/Debian.pm#L244) configured interfaces only the interface name definition is preserved, while for statically configured interfaces all of the [interface attributes](https://github.com/proxmox/pve-container/blob/master/src/PVE/LXC/Setup/Debian.pm#L264) are preserved. Which is why yourself and @LubomirH are observing different behavior. Whether that is an oversight or by design - I don't know. I've swung by their bugtracker and there is a [report](https://bugzilla.proxmox.com/show_bug.cgi?id=2838) of this issue, however desired behavior would require specific implementation there.

While looking at the code I've also found that specifically for `interfaces` file the `# --- BEGIN/END PVE ---` markers are only applied when additional [routing directives](https://github.com/proxmox/pve-container/blob/master/src/PVE/LXC/Setup/Debian.pm#L140) are included by the PVE itself. I assume they don't consider enforcement of correct network configuration a modification, therefore don't include them otherwise. It does sound a bit inconsistent, but idk, for all my time using Proxmox this has never been an issue for me. I always knew Proxmox will override network settings if they diverge from original config so I never messed with that.

**Comment by JedMeister** [comment]
Thanks for your insight @NitrogenUA 

I'm not sure why, but it never occurred to me that the DHCP & static behaviour would be different.

**Comment by JedMeister** [comment]
With the [latest changes to confconsole](https://github.com/turnkeylinux/confconsole/pull/74) (sorry the PR is a bit of a mess - grab bag of a whole heap of stuff) I'm closing this issue now. The current code (which will only be packaged for v18.x) that should ensure that TurnKey is doing the right thing.

There will still be issues for those that choose to adjust networking on the guest (i.e. in TurnKey) rather than the PVE/LXC host, but we can consider that as a separate matter to improve via https://github.com/turnkeylinux/tracker/issues/1833
