### ISSUE TITLE
Upgrade from TurnKey GNU/Linux 14.1 / Debian 8.11 Jessie to latest

### ISSUE THREAD

**Issue by prassaschr** [turnkeylinux/tracker#1851]
Are there any way to upgrade from TurnKey GNU/Linux 14.1 / Debian 8.11 Jessie turnkeylinux openvpn to latest without changing configuration?

**Comment by JedMeister** [comment]
Hi @prassaschr - deep apologies on my ridiculously delayed response. I've had my head down working on our upcoming v18.0 release (which is so close, but I keep finding things to tweak/fix...) and I missed your post.

FWIW this is our consolidated issue tracker, for tracking bugs and specific feature requests, rather than more general support (such as your question). You'll almost certainly get a quicker response on our website ([forums](https://www.turnkeylinux.org/forum/support)). Unfortunately due to spammers, I've disabled automated account approval (so if you want a website account, please sign up and ask me to approve).

Regardless, while y9our here, I'll answer your question. :smile: 

----

Unfortunately, the short answer is not as far as I'm aware. You could try migrating your OpenVPN data/config to a new v17.x OpenVPN server. Considering the age of your server, I strongly suspect that it won't "just work". IMO you'd be best to make a clean start with a new server. Although if you do that, unless OpenVPN is a hard requirement, I'd encourage you to consider Wireguard instead. FWIW Wireguard has much higher throughput, lower latency and has lower system load (unlike OpenVPN, Wireguard is integrated into the kernel).

Longer answer is that it may be possible to do OS upgrades (i.e. Debian style OS upgrades), although my guess is that you'll still need to make config tweaks along the way.

From what I gather, Jessie has OpenVPN v2.3.4. Bookworm (i.e. current stable - the basis of our upcoming v18.0) has [v2.6.3](https://packages.debian.org/bookworm/openvpn). I'm not super familiar with the OpenVPN codebase but seeing as that's 2 minor versions, I'm fairly confident that you will need to tweak config as you go, although you may get lucky!?

Please note that you can't just upgrade straight to Bookworm. Debian OS upgrades don't support skipping releases, so you'd need to go:

```
Jessie -> Stretch -> Buster -> Bullseye -> Bookworm
```
It looks like Buster still had [v2.4.7](https://packages.debian.org/buster/openvpn), which suggests to me that the config changes should be minimal between Jessie & Stretch, then Stretch & Buster. Going to Bullseye will likely require some config tweaks (it has [v2.5.1](https://packages.debian.org/bullseye/openvpn)). And again going to Bookworm (as noted above, Bookworm has v2.6.3).

If you choose to give this a go, please be sure to create some sort of system snapshot (i.e image the whole OS - should be easy if you're running a VM; if you're running on hardware, try Clonezilla). I'd suggest that you create new snapshots each (successful) OS upgrade (to reduce having to go back if something goes wrong later). If you don't do that, there may be no going back! You have been warned...

One other thing worth noting is that because of the age of your server, I'm pretty sure that you won't be able to use the "normal" Debian repos. (AFAIK Jessie & Stretch repos are no longer available via default apt config). Although I note that both Jessie & Stretch are covered by the [Debian ELTS (extended long term support) program](https://wiki.debian.org/LTS/Extended). Please check out the details on the [Freeaxian website](https://www.freexian.com/lts/extended/docs/) - Freeaxian provides the LTS & ELTS support - it's actually a paid subscription service, but their work is freely available to everyone (although it doesn't provide support for all packages - only paying customers get to nominate which packages are supported).

Here are some other resources that might be useful:
- [OpenVPN - Deprecated Options](https://community.openvpn.net/openvpn/wiki/DeprecatedOptions)
- [OpenVPN manual - v2.4.x](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/)
- [OpenVPN changes - v2.4.x](https://community.openvpn.net/openvpn/wiki/ChangesInOpenvpn24)
- [OpenVPN manual - v2.5.x](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-5/)
- [OpenVPN changes - v2.5.x](https://community.openvpn.net/openvpn/wiki/ChangesInOpenvpn25)
- [OpenVPN manual - v2.6.x](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/)
- [OpenVPN changes - v2.6.x](https://community.openvpn.net/openvpn/wiki/ChangesInOpenvpn26)
- [Debian - Stretch release notes](https://www.debian.org/releases/stretch/amd64/release-notes/) (at least have a quick scan through and a closer look at Chapter 5:)
  - [Debian - Stretch release notes - Chapter 5: Issues to be aware of](https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html)
- [Debian - Buster release notes](https://www.debian.org/releases/buster/amd64/release-notes/) (as above)
  - [Debian - Buster release notes - Chapter 5: Issues to be aware of](https://www.debian.org/releases/buster/amd64/release-notes/ch-information.en.html)
- [Debian - Bullseye release notes](https://www.debian.org/releases/bullseye/amd64/release-notes/) (as above)
  - [Debian - Bullseye release notes - Chapter 5: Issues to be aware of](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html)
- [Debian - Bookworm release notes](https://www.debian.org/releases/bookworm/amd64/release-notes/) (as above)
  - [Debian - Bookworm release notes - Chapter 5: Issues to be aware of](https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.en.html)

Hopefully that's enough to get you going. I'm going to close this issue for now, but please feel free to post back (if you don't want to sign up to our website) and I'll respond when I get a chance.
