### ISSUE TITLE
MoinMoin VM is based on Moin 1.9.9 - version 1.9.11 exists

### ISSUE THREAD

**Issue by tbird1965** [turnkeylinux/tracker#1863]
Latest version of MoinMoin is 1.9.11.  It would be great if an updated TurnkeyLinux is released for it.  I manually updated MoinMoin and found one important item - even a superuser by default does not have rights to do anything.  In the wikiconfig.py file, there is a hint:
```
    # IMPORTANT: grant yourself admin rights! replace YourName with
    # your user name. See HelpOnAccessControlLists for more help.
    # All acl_rights_xxx options must use unicode [Unicode]
    #acl_rights_before = u"YourName:read,write,delete,revert,admin"
```
Must add to the wiki: `acl_rights_before = u"admin:read,write,delete,revert,admin"`

**Comment by JedMeister** [comment]
Hi thanks for reporting. And bonus points for sharing a tweak to improve it.

Unfortunately though v16.x is based on Debian 10/Buster - currently tagged "oldoldstable". Whilst it is still supported by Debian [LTS](https://wiki.debian.org/LTS) team, we've moved on (we don't have enough resources to support such old releases). As such there will be no updates to v16.x appliances at this late stage (FYI we're currently working on the v18.0 release).

The reason why there is/was no v17.x (based on Debian 11/Bullseye) release of the MoinMoin appliance is because python2 is EOL. So until there is python3 based release of MoinMoin, we won't be releasing a new appliance for it.

[MoinMoin v2.0](http://moinmo.in/MoinMoin2.0) is in the works, but unfortunately, there is [no ETA](http://moinmo.in/MoinMoin2.0#Release_date).

Sorry to be the bearer of bad news, but I do really appreciate your efforts.

I'm going to close this as I'm almost certain that by the time there is a MoinMoin v2.0 release, this particular issue won't be relevant (python3 solves a lot of the encoding issues apparent in python2, so these sort of issues shouldn't occur).

**Comment by tbird1965** [comment]
I 100% agree and understand.
