### ISSUE TITLE
Leantime: update to v3

### ISSUE THREAD

**Issue by brandstaetter** [turnkeylinux/tracker#1908]
Leantime is severely outdated. I managed to manually update to the latest 3.0.7 at the time of writing but it was not without challenges. Is someone already working on getting it updated or should I try to provide a new version myself (newb with TKL toolchain)

**Comment by JedMeister** [comment]
Hi @brandstaetter - thanks for the report. By my understanding was that the upgrade to 3.0.7 should be trivial But that's clearly not the case... We'll endeavour to do an updated release ASAP.

**Comment by brandstaetter** [comment]
There are some breaking changes between 2 and 3, and for me as user there were some unexpected issues along the way, for example that the update script didn't work because you had used " instead of ' in some settings files; I think this majjor upgrade warrants a new version of the image to make it less frustrating for less experienced users :)

**Comment by JedMeister** [comment]
Hi @brandstaetter - thanks again for dropping in.

We did do a new v18.0 release (based on Debian 12/Bookworm with PHP8.2) of our appliance about a month ago - which includes a newer v3.0.x version of Leantime. Although unfortunately, at the time I didn't notice that the Leantime version being installed was being set statically and because I didn't build it immediately, it was a slightly older version of Leantime than would have been ideal.

Pity that I wasn't aware of the quotes issue sooner or I would have addressed that at the same time.

**Are there any other issues or tweaks that you're aware of that we could improve on?**

> you had used " instead of ' in some settings files

FWIW I've opened a new issue for that (#1911) - and opened a pull request that fixes it (among other things): https://github.com/turnkeylinux-apps/leantime/pull/5

I will aim to rebuild fairly soon. Although we do have quite a few other updated appliances to build for v18.0 but I'll try to get onto it ASAP.

----

FWIW in the meantime you could run this sed line over the config file and that should change all the relevant `"` to `'` (without changing the ones which are already there and are obviously meant to be there):

```
sed -i.bak "\|public | s|\"|'|g" /var/www/leantime/config/configuration.php
```
That will update the `/var/www/leantime/config/configuration.php` file and create a backup file `/var/www/leantime/config/configuration.php.bak`. You could double check it worked as expected using diff:

```
diff -u --color /var/www/leantime/config/configuration.php.bak /var/www/leantime/config/configuration.php
```

Regardless, we certainly should have been consistent with the existing style. Although TBH I was under the impression that it was essentially a stylistic thing (beyond some specific circumstance which I wouldn't have expected to apply here)? While I admit that I'm quite a PHP novice, I assume that is something unique to your update script? Or is it a new PHP thing? Or am I missing something?

FWIW I've been building PHP based appliances for some time now (~15 years) and can't say I've ever hit that issue before.

**Comment by JedMeister** [comment]
PS whilst technically this issue should have been closed by our v18.0 release, I'll leave it open for now until we release the v18.1 version.

**Comment by brandstaetter** [comment]
The quotes vs doublequotes thing was only an isssue in the leantime v2 update script because there it wasn't considered...
This script is no longer provided with the v3 version anyway.

Thanks for providing the new version... as a hint for nebies to leantime, the current way to update to latest is to run 

```
bin/leantime system:update
```

**Comment by JedMeister** [comment]
@brandstaetter - Thanks for the info.

Re the `bin/leantime system:update` I assume that needs to be run as the webserver user (in our case `www-data`)?

**Comment by brandstaetter** [comment]
@JedMeister I just ran it as root user in my proxmox container and it worked fine; I don't think running it as less privileged user would work as it also backs up the DB etc

**Comment by JedMeister** [comment]
Ok, great thanks @brandstaetter.

Regardless, I think that we should still use single quotes when we make config changes, if for no other reason than keeping the style consistent.

I'm going close this issue now as we do have a appliance with v3.x. When we rebuild to resolve https://github.com/turnkeylinux/tracker/issues/1911 (re quotes), it will automatically install the latest stable. If you have any further concerns, please don't hesitate to open a new issue.
