### ISSUE TITLE
Collabtive Link in Turnkey Apps needs update

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1926]
[https://www.turnkeylinux.org/collabtive](https://www.turnkeylinux.org/collabtive)

gives:
[https://collabtive.o-dyn.de/](https://collabtive.o-dyn.de/)
which does not work:

[https://www.collabtive.com/](https://www.collabtive.com/)
does work

**Comment by JedMeister** [comment]
Hi @l-arnold 

Thanks for bringing this to my attention. However, we have deprecated Collabtive, hence why the lastest release on the website is listed as v16.x (and we're currently working on v18.x). I intend to remove that page altogether soon and I will archive the git repo.

I think that the site you've found is actually an old site, rather than a new one. I suspect that the link that we provided was a newer site- that no longer exists.

The reason what I say that is the v16.x appliance included [Collabtive v3.1](https://github.com/turnkeylinux-apps/collabtive/blob/master/conf.d/downloads#L8). Where as that site's download link is for Collabtive v0.6. As you can see on [SourceForge](https://sourceforge.net/projects/collabtive/files/collabtive/) v3.1 is the most recent release - nearly 7 years ago. v0.61 was released nearly 15 years ago!

So thanks again for pointing out the website issue, but the Collabtive appliane is pretty old and while it should still work, it's abandon-ware and I wouldn't recommend it for a new project. If you're looking for Project Management software then perhaps [Leantime](https://www.turnkeylinux.org/leantime) might be worth a look?

As such I'm going to close this issue. And I will probably get rid of the page on the website soon.

**Comment by l-arnold** [comment]
Yes,  I "edited" the note but I am guessing you got an email on the pre-edit re the links.

This came from simply browsing the turnkeylinux.org site and noted that I could not follow the link.  I think it not being really "open source" is good reason not to proceed.  Complicated issues to be sure.
