### ISSUE TITLE
Remove Django turnkeylinux Web Shell link

### ISSUE THREAD

**Issue by montvid** [turnkeylinux/tracker#1927]
As shell is used from webmin, Web Shell is not accesible, deprecated but the icon, link is still there. Please remove that as it is confusing. Thanks!

**Comment by l-arnold** [comment]
This probably should be universal on v 18 apps that don't have WebShell.
I presume this to be a "Confconsole" issue.  Hub for instance will not show a "Webshell Link" in v18 applicances.

It is actually an issue at times where there is also no "Webmin" such as in TKLDEV.  Not sure if that is a current issue there.

**Comment by montvid** [comment]
I tried 18 v django proxmox lxc and the iso from turnkeylinux and both have the webshell icon/link that does not work. I had to see the changelog to find out i have to use webmin now. Everything else works fine, thanks! 💫

**Comment by JedMeister** [comment]
@montvid - apologies. Including that link on the landing page was a gross oversight on our behalf!

As you've likely seen now in the changelog, because Webmin now has a proper terminal, we've removed Webshell.

The only issue there is that some of the earlier appliances in our v18.0 release may not actually have the `webmin-xterm` package installed (which provides the proper terminal in Webmin). It will still have a shell, but it's not a proper interactive one. :cry: 

TBH, I'm not sure if Django is one of those OTTOMH. But you can double check by going to the Webmin apt packages page and try to install `webmin-xterm` - if says that you have it already, then you're good to go. If it doesn't then it will be installed.

Sorry I forget exactly where the apt packages page is in Webmin, or exactly what it's called in the menu (perhaps just `packages`?) - but please post back if you can't find it and I'll have a closer look.

Another option is to log in via SSH and run:

```
apt update
apt install webmin-xterm
```

----

@l-arnold - Thanks for jumping in mate! You're a legend. :+1: 

FWIW TKLDev should be the only appliance without Webmin. And actually it does still have Webmin, it's just it's disabled by default. The reason why that is is that it would cause appliance builds to fail. Only one application can use a specific port at a time. If the TKLDev host is already using port 12321, then Webmin would fail in the appliance being built.

We could run Webmin on a different port on TKLDev. Perhaps that's a good idea?

**Comment by JedMeister** [comment]
Also @montvid - I didn't say before, but thanks heaps for reporting the issue.

I've just removed the Webshell link from the landing page in the Django appliance build code. So it will be fixed it in the next release.
