### ISSUE TITLE
Relese hash/sig file have wrong key URL

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1933]
A user has just reported:

> attempting to check the download (of the hash-file) I followed the 
> recipe in your docs for verifying.
> 
> 
> First the retrieval of the key:
> 
> $ curl 
> https://raw.githubusercontent.com/turnkeylinux/common/master/keys/tkl-bookworm-images.asc > tkl-bookworm-key
> 
> Then, the content of the downloaded "key-file" showed up:
> 
> $ cat tkl-bookworm-key
> 404: Not Found

That is because we include the wrong URL in the hash/sig file. It should be:

https://raw.githubusercontent.com/turnkeylinux/common/18.x/keys/tkl-bookworm-images.asc

Note the branch is `18.x` - not `master`. I need to update the file, but as a workaround (for existing releases) I will also commit the key to the `master` branch so it will work.

**Comment by OnGle** [comment]
Trying to solve this, I went down a rabbit hole realizing that buildtasks wasn't working properly, turned out to be a non-issue.Then today first thing, it turns out this issue is already fixed anyway....

Branch set here: https://github.com/turnkeylinux/buildtasks/blob/297bb52ba4792570a848accf9573abc82414c52c/bin/generate-signature#L45

Url set here https://github.com/turnkeylinux/buildtasks/blob/297bb52ba4792570a848accf9573abc82414c52c/bin/generate-signature#L60

And here's how it's added to the signature: https://github.com/turnkeylinux/buildtasks/blob/297bb52ba4792570a848accf9573abc82414c52c/bin/generate-signature#L83

:melting_face:
