### ISSUE TITLE
Twiki inithook not working consistently

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#206]
There is a thread detailing the issue on the [TKL forums](http://www.turnkeylinux.org/forum/support/20130715/turnkey-linux-twiki). 

In essence, Twiki inithook isn't working consistently to create the AdminUser password. I detailed my troubleshooting steps and how to consistently reproduce this error in [this post](http://www.turnkeylinux.org/forum/support/20130715/turnkey-linux-twiki#comment-20180).

**Comment by JedMeister** [comment]
The new version needs to b e checked to see if this is till and issue.

https://github.com/turnkeylinux-apps/twiki

**Comment by qrntz** [comment]
@JedMeister, works OOTB with the current version of the appliance.

**Comment by qrntz** [comment]
OK, this one is pretty funny.

crypt() only uses the first 8 characters of the string it is given. htpasswd warns about this. That warning message does **not** make a proper entry in the password file.

TWiki doesn't support bcrypt or APR MD5 (which are good choices in htpasswd) so that leaves us with SHA1 which is kind of insecure, but then it's still better than crypt.

**Comment by JedMeister** [comment]
:+1:
