### ISSUE TITLE
[Hub] Backups: Move old backups to AWS Glacier

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#208]
Suggested by `L. Arnold` on the [forums](http://www.turnkeylinux.org/forum/general/20140518/recomendation-tklbam-archive-glacier):

Instead of deleting old backups, (optionally) allow them to be archived in/migrated to [AWS Glacier](https://aws.amazon.com/glacier/). Glacier is very cheap (but slow) storage, ideal for old backups that you want to keep but probably won't ever need...

**Comment by lirazsiri** [comment]
I looked into this and the issue is that while storing backups to glacier is easy and cheap restoring them is potentially super expensive, in a really unintuitive way. You can restore a few percent of your glacier storage cheaply but if you need to restore a big chunk in a hurry you may end up paying thousands of dollars in extra fees. To prevent nasty surprises we would have to educate users about that, which complicates things.

**Comment by JedMeister** [comment]
I'm going to close this issue in favour of #501
