### ISSUE TITLE
Vim: symbolic link breaks install of vim full package

### ISSUE THREAD

**Issue by dafyddj** [turnkeylinux/tracker#300]
On fresh install of TKL Core 13.0 there is a symbolic link from `/usr/local/bin/vim` to `/usr/bin/vim.tiny`.
Should you install the full vim package via apt-get, vim is installed as `/usr/bin/vim.basic` but the symbolic link persists and launching `vim` launches `vim.tiny` i.e. the small version with no feature like e.g. syntax highlighting. This is very confusing and caused me to waste significant time tracking the issue down.

See also the forum [here](http://www.turnkeylinux.org/forum/support/20100114/howto-update-vim-turnkey-appliance-development#comment-10486)

**Comment by JedMeister** [comment]
Hmm, so it seems that this has been an issue for some time... I am not sure where/when this symlink is created but we'll have to look into it...... I have just had a bit of a dig around and I am none the wiser... I can't see how/where the vim-tiny package creates this symlink, but i find it hard to imagine that the TKL core devs would have manually added this to the vim-tiny install...

**Comment by dafyddbj** [comment]
Hi, 
I have tracked it down to [here](https://github.com/turnkeylinux/common/blob/master/conf/turnkey.d/vim.tiny).

I'm not familiar with the build process, or know why it's there but that is where the offending link is created. I can only imagine it is created for convenience as the base turnkey install does not include the full vim package - but as I've said it makes things very confusing should one want to use vim with plugins and syntax highlighting.

**Comment by JedMeister** [comment]
Great detective work! :) TBH it hadn't occurred to me that TurnKey would be adding that (I thought it must have been a bug in some other package). It goes to show how important it is to have the source code open and available! :)

And I suspect that you are right in regards to convenience. I'm no expert in these things but my understanding is that that the preferred way to handle this would be to use the Debian `update-alternatives` feature to set vim.tiny as the 'vim' editor. That way if full vim (vim.basic) gets installed it will automatically adjust the vim path to point to vim.basic instead... So that is what I propose to @alonswartz & @lirazsiri 

For reference this is what I did. TBH I think that a little more is needed (as when I install full vim there were quite a few warnings; so I suspect that I missed something...)

Removed symlink:
`rm /usr/local/bin/vim`
'Installed' vim.tiny as an alternative for vim:
`update-alternatives --install /usr/bin/vim vim /usr/bin/vim.tiny 10`
The 10 means really low priority (similar to apt-pinning) so if vim is installed vim.tiny will lose out...

Did some checks:
````
# which vim
/usr/bin/vim
# ls -l /usr/bin/vim
lrwxrwxrwx 1 root root 21 Feb 11 22:44 /usr/bin/vim -> /etc/alternatives/vim
# update-alternatives --get-selections | grep vim
ex                             auto     /usr/bin/vim.tiny
rview                          auto     /usr/bin/vim.tiny
vi                             auto     /usr/bin/vim.tiny
view                           auto     /usr/bin/vim.tiny
vim                            auto     /usr/bin/vim.tiny
````
Then installed 'full' vim:
````
# apt-get install vim
...
The following extra packages will be installed:
  libgpm2 vim-runtime
...
````
Then checked again:
````
# which vim
/usr/bin/vim
# ls -l /usr/bin/vim
lrwxrwxrwx 1 root root 21 Feb 11 22:44 /usr/bin/vim -> /etc/alternatives/vim
# update-alternatives --get-selections | grep vim
ex                             auto     /usr/bin/vim.basic
rview                          auto     /usr/bin/vim.basic
rvim                           auto     /usr/bin/vim.basic
vi                             auto     /usr/bin/vim.basic
view                           auto     /usr/bin/vim.basic
vim                            auto     /usr/bin/vim.basic
vimdiff                        auto     /usr/bin/vim.basic
````

Looks like a winner to me! :)
