### ISSUE TITLE
Your Ejabberd is too too old and not working

### ISSUE THREAD

**Issue by Cedybt** [turnkeylinux/tracker#306]
i've been using your ejabberd service on amazon ec2 micro, my Gash its too old!!!
Once you luanch the instant it shows Running but when i use an xmpp client using the hostname you gave me, it takes like forever to login,overall it fails to login... your ejabberd is 2.1 wtf!!!
i mean what do we pay you for?
seriously am so disappointed in you guys!!!!!

**Comment by JedMeister** [comment]
For starters, this isn't really the place for support; it's for bug tracking (and feature requests). The place for support is our [forums](http://www.turnkeylinux.org/forum/support). I'm tempted to just close this issue but perhaps there is a bug? Also I guess your 'issue' could be interpreted as a 'request' for a newer version of eJabberd?!

Also whilst on face value v2.1 may seem really old in comparison to the recently released v15.02; it doesn't take into account that they version jumped (roughly 18 months ago) from 2.13 straight to v13.01!

For a further bit of context; eJabberd is installed from (Debian) package management; hence why it is 'old'. It is the nature of the Debian way... Debian packages trade security and rock solid stability for having the 'latest and greatest'. The security side of things comes from the way the official Debian packaged software has security patches backported (by the Debian security team) and automatically applied (via a TurnKey tweak); so you don't need to constantly watch for security notifications and manually update software all the time - just to keep your server secure... 

I'm guessing by your tone that you come from the Windows world where you always have to chase your tail to try to keep your software secure (not that Debian is perfect; it's just a far better model IMO).

So other than the fact that you think it's too old, is there actually any problem with using the Debian packaged version? Does it have any specific usability bugs? (Sometimes they slip through and they often aren't patched unless they have security implications). Or are there significant features or improvements that would warrant us giving up the advantages of the packaged version?

If so, please make your case and we will consider installing from upstream in future releases of TurnKey... FWIW whilst you'd generally expect later releases to be better; the eJabberd devs don't recommend against using the Debian version (they advertise it's existence on their website)... Another reason that I wouldn't be keen to install from upstream is that the next version of Debian (which is what TurnKey v14.x will be based on) include eJabberd v14...

Final point - considering that all our appliances are available to download (and self host) free of charge; what you are paying for is the ability to easily launch and manage your appliance in the cloud (and funding the development of free open source tools such as [TKLBAM](http://www.turnkeylinux.org/docs/tklbam) and [friends](https://github.com/turnkeylinux)). In fact if you are only using a single micro appliance then you probably aren't paying us anything (and if you are then you don't need to be...). For a single micro appliance all the money would be going to Amazon...

**Comment by Cedybt** [comment]
Get a life! 
Talking about bugs you should advise your ejabberd customers to use an Elastic IP coz once you stop an instance AWS automatically allocates a new IP as soon as you start it again...this conflics with your Domain xxx.tklapp.com DNS records. you should make it more flexible to suit the IP changes.
i had that prob....
and one more thing maybe try and install ejabberd from the installer or source code don't go for simple solution,
i mean,how long would it take me to install a package? an apt-get only takes a few secs
Sorry if i was Rude.
Regards Bee
Rwanda.

**Comment by JedMeister** [comment]
FWIW to me your posts do come across as rude. To me "Get a life!" is basically saying "screw you!" 

And I consider that rude. Especially considering that TurnKey Linux is free software and is gifted to you. Is that the way you would speak to your friends or family if they gave you a gift that you didn't want or like? I would imagine that you would be a little more polite and say something more like "thanks anyway but it's not really what I want" or "thanks but I'd rather that it did XYZ" - which would be completely appropriate here too!

Anyway:

Elastic IP
FWIW I do (on the forums) recommend that users use elastic IPs... Also if you use a decent DNS (like Google Public DNS - 8.8.8.8) then it should take no more than 5-10 mins (after relaunch) for the new IP to propagate (as documented). ISP's DNS (as many/most users use) are often configured to have a very long TTL which overrides the default tklapp.com configured TTL.

Installing from apt vs source
Please read my previous explanation re why we prefer to use Debian's package management - there's a really good reason! But like I said if you can give us a good reason (e.g. bugs and/or killer features) why we should use upstream source instead then we will certainly consider that (for our next version)!

If you can set up your own eJabberd server in "a few secs" then it sounds like TurnKey Linux may not be for you!? And perhaps many of the other included features are of no use to you (e.g. Webmin, Webshell, automated 'smart' backups (TKLBAM)), if so that's cool. We don't pretend that TurnKey Linux is perfect and is the best tool for every use and/or every person. What we are saying (or at least trying to build) is a headless server OS library that is ready-to-use for newbs and a good starting point for those more experienced. 

If it isn't to your liking then please give us some constructive feedback on how it could be better - not just your opinion but a rationale on why we should change it (please take into account the rational that I have already given you regarding why we use default repo version - in my previous post). If that's all too much work then please feel free to use something else.

TBH I'd love it if you can give me a good reason why the newer version of eJabberd is better...

**Comment by JedMeister** [comment]
Closed due to lack of response
