### ISSUE TITLE
Can't create account, can't open pages.

### ISSUE THREAD

**Issue by fran-sgd** [turnkeylinux/tracker#307]
I know this might be off topic, but the site contacts do not respond or require an account. While trying to create an account to use the forums, to ask questions, I get this error:
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/4575270/6516962/7b934764-c364-11e4-9d63-b0b935bdf680.png)

When I visit www.turnkeylinux.org to get more info about an AMI I get this:
![f10ec7f7-f65a-4169-8020-2d258fe9992c](https://cloud.githubusercontent.com/assets/4575270/6517010/efc5481c-c364-11e4-81c1-8a7fa56cb256.png)

Is this site still alive?

**Comment by JedMeister** [comment]
Hi,
Thanks for reporting. Yes we are still very much alive!!

Unfortunately there is something wrong with the website at the moment; and actually your first screenshot gives me a hint to try disabling the spam filter (at least temporarily).

I might try disabling that so that at least then you can post... (We'll probably get flooded with spam but better that than people not being able to post at all).

If that doesn't work we'll need to wait for Liraz to have a look (when he gets up - he's in Israel - probably sleeping right now...).

**Comment by JedMeister** [comment]
Strange, I just had a look and the spam filter settings seem ok... I will have to leave it for Liraz. Sorry about that... You may be able to at least read content via Google cache (i.e. do a google search but instead of clicking on the link, click on the drop down next it it (RHS) and select 'Cached'.)

**Comment by fran-sgd** [comment]
Thanks, I'll check in tomorrow since I have question that I didn't see on the site before it went away.

**Comment by fran-sgd** [comment]
Account creation and blog visits are all working, thanks!
