### ISSUE TITLE
Why does Lapp call itself in lapp/plan/main ?

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#310]
First two lines of the plan for Lapp are:

#include <turnkey/base> "turnkey/base"
#include <turnkey/lapp>  "turnkey/lapp"

Not sure how it can or why it does, call itself.  I was looking at using this as a base in TKLDEV and just working through my understanding of theTKLDev process.

**Comment by l-arnold** [comment]
Also, I don't understand why there is no Conf-D folder as there seems to be in every other App that I am looking at (joomla, posgresql, web2py etc.

**Comment by l-arnold** [comment]
Ok,  there are others that seem to call themselves.  The #include commands have arrowheads around them not quotation marks.  Don't show up properly if shown.

**Comment by JedMeister** [comment]
To answer your first Q:
This is pointing to the shared plans in common (see here: https://github.com/turnkeylinux/common). Whilst on face value that may seem messy; it is so that the code can easily be shared amongst appliance and doesn't need to be included in each one individually (meaning that it would get repeated). So in the case of the LAPP appliance is needs to include the [turnkey/base plan](https://github.com/turnkeylinux/common/blob/master/plans/turnkey/base) and the [turnkey/lapp plan](https://github.com/turnkeylinux/common/blob/master/plans/turnkey/lapp).

Second Q:
As I mentioned on the forums; the LAPP applaince doesn't need a conf.d script as nothing further needs configuring...

Third Q:
TBH I'm not 100% sure what you're talking about but I am guessing you mean less-than (&lt;) and greater-than (&gt;) symbols? Without knowing exactly which ones you're talkign about (and I can't find any jsut at the moment) I'm guessing that again it's probably stuff in common...

**Comment by l-arnold** [comment]
Correct on Q and A.   Forums more appropriate "forum"

Coming back to this just to comment, it was helpful in understanding TKLDEV.
2 Months later now it does make sense.  Was getting thrown by the role of the

/turnkey/mk files that were calling to core, and particularly how an app could seemingly call itself.  
IE
 #include "turnkey/base"
#include "turnkey/lapp"
