### ISSUE TITLE
(Jessie) TKLDev SSL crash on make

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#344]
Wheezy 386 made it through
Weezy 64 crashes needing ISO Linux
Jessie has more complicated crash  (nearly complete)

System uses Odoo, and is using a Proxy to make Odoo Server put out as SSL Apache Proxy.

near end of make get the following.  Can't figure how to fix (including first adding a file in "sites-enabled" (there was one in "sites-available" in overlay)...  Then tried deleting references to openerp-ssl site all together..  running "make clean && make")  (MAY BE BETTER THAN MAKE.. BUT MUST WAIT A WHILE)

Prob is that this is not a Proper Apache Site that is being proxied to.
error below

 Make SSL work properly
+ echo ------------------------
------------------------
+ a2enmod ssl proxy_http headers rewrite
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Considering dependency proxy for proxy_http:
Enabling module proxy.
Enabling module proxy_http.
Enabling module headers.
Enabling module rewrite.
To activate the new configuration, you need to
  service apache2 restart
+ a2ensite openerp-ssl
ERROR: Site openerp-ssl does not exist!
/usr/share/fab/product.mk:476: recipe for targ
led
make: *** [build/stamps/root.patched] Error 1

**Comment by JedMeister** [comment]
Failing to build because of no isolinux is most likely because you ran `make CHROOT_ONLY=y`
first and then ran `make`.

If you first run `make` with `CHROOT_ONLY` you need to run `make clean` before you run `make`. That is because CHROOT_ONLY will only install packages that are required for a chroot (i.e. none of the packages needed to build an ISO will be installed).

As for your issue; you say that you are running Wheezy and refer to 32 & 64 bits. Let me clarify a few things:
- TKL v14.0 will be 64 bit only at this point
- Updates done to the common repo mean that v13.0 builds are now broken (unless you clone the repo from  the relevant v13.0 tag)
- So I strongly suggest that you stop using TKLDev Wheezy and exclusively use the v14.0RC1 with my `jessie-apache-tweak` branch of common (I I mentioned in another post).
- To help you troubleshoot your issue, do it in a methodical way. Start from a known good point. E.g. build the vanilla base appliance first (LAPP in this case). 
- Ensure that works before you move on to building your customised appliance... 
- Assuming that the base appliance build works fine, try making small changes to your custom appliance build scripts and test. You can always comment code out (in the conf.d script) if you have already made big changes...
- If all else fails, go back to the TKLDev docs... Perhaps you need to spend a little more time getting to know TKLDev...?

**Comment by l-arnold** [comment]
Focus has been on Jessie.  Core Builds.  Lapp Builds.  
Odoo does not build in Jessie as described.

I just downloaded (or tried to) the Build Folder but an hour later nothing is showing up.  Plenty visible in the SFTP window.  Cannot find anything refering to Openerp-ssl.

I am spending quite a bit of time with TKLDEV.
3 Variable results (including a functioning install that will not be supported) makes me not feel that I am causing the problems with it.

ALSO, I did not run 
make CHROOT_ONLY=y

**Comment by l-arnold** [comment]
Wondering if this is a TX c XXL subject.  I assume is controlled still in Apache.  Anything else that could bear on a Proxy redirect and TX vs SSL?

You (Jeremy) have a forum post about same redirect on the Odoo subject. But was about manual build.

Sent from Nine

**Comment by JedMeister** [comment]
Ahh! Just re-read you initial post...

And I see: `a2ensite openerp-ssl ERROR: Site openerp-ssl does not exist!`. 
I know what the issue is! In Jessie the updated version of Apache is much more strict so rename your Apache site file from:
`/etc/apache2/sites-avaialble/openerp-ssl`
to
`/etc/apache2/sites-avaialble/openerp-ssl.conf`

**Comment by l-arnold** [comment]
Almost Missed your post just now. Bottom was written before.  The two references below seem related.  Will rename to .conf  (sounds good).  Need to Bring it back in of course.
--------------

https://bitbucket.org/anybox/anybox-odoo-host/pull-request/1/add-optional-support-to-apache/diff

http://www.turnkeylinux.org/forum/general/20150402/installing-odoo-step-step-tkl

Although my file did not have the following (see your step by step) at the End, the Post install Error is calling a2ensite and "openerp-ssl site does not exist"  and therefore likely related to "optional support" above.  Likely need to 

EOF

a2dissite default
a2ensite odoo

a2enmod proxy_http headers rewrite

service apache2 reload

**Comment by l-arnold** [comment]
Info here on the .conf usage...
https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-debian-7

**Comment by JedMeister** [comment]
Note that DigitalOcean link is for Wheezy (TKL v13)... Things have changed between Apache2.2 (Wheezy/7) and Apache2.4 (Jessie/8). Some may still apply for Jessie (v14), other stuff has changed...

**Comment by l-arnold** [comment]
Comment I found (Google Search) was about both actually.  
mf.digitalocean February 23, 2014
@Kamal, great article but for forward compatibility with Apache 2.4 you should follow @monkeydump's advice and change step 4 to: sudo cp /etc/apache2/sites-available/default /etc/apache2/sites-available/example.com.conf  @monkeydump's rightly points out that if you use Debian Jessie (the upcoming release) you'll get Apache 2.4 which requires ".conf" — Debian Wheezy (the current stable) uses Apache 2.2 which doesn't require ".conf" but still accepts it.

**Comment by l-arnold** [comment]
Best is to put an AutoRename into the TKLDEV protocol.  This is going to be an ongoing issue.  Was the issue with PGPADMIN now that I think of it.

Pretty much any migration w/ TKLDEV or TKLBAM will need renames taking place.

**Comment by l-arnold** [comment]
I got a Jessie 64 B ISO...  yay!  Now to test install tweak it so that Port 80 is Odoo actually pushing to 443...  (Right now Odoo is in 12325 (throwing 8069 into SSL) and index.php is 80.)

Guessing Make will have to download Odoo again.

**Comment by l-arnold** [comment]
re: 32 Bit.  Seems to still be supported by Jessie.  (not saying do it, but it is a good way to use older equpt).  Very large speed differential though IMHO.
https://www.debian.org/releases/stable/i386/release-notes/ch-whats-new.en.html#idp149600

**Comment by l-arnold** [comment]
Odoo Loads (after Manually starting Posgresql).  Also loads in proxied SSL/TLS.

Apache seems to have a new structure.  Not finding the index.php file...  SFTP not opening along with my SSH window for some reason. (Bitvise SSH Client)

**Comment by l-arnold** [comment]
offending line was last section of Odoo Installation
(Did not end in "conf")  As for the others in Overlay, it does not seem to matter if CONF is in the name.  TKLDEV is moving them in with that name.  It was the non standard Odoo Config that was causing the error. (see "conf" at end - added to openerp-ssl)

echo "------------------------"
echo " Make SSL work properly "
echo "------------------------"
a2enmod ssl proxy_http headers rewrite
a2ensite openerp-ssl.conf

**Comment by JedMeister** [comment]
Sounds like you're ahving some wins! :smile:

**Comment by l-arnold** [comment]
Ran Fresh LAPP Install 5-19-15
Http and Https  (80 and 443) working
Also showing in Apache
12322 Adminer Runs under Https.  
12320 and 12321 Do not run under Http.  (Recommend perhaps a redirect as Webmin 12321 provides)  
---------------
12320 HTTP Returns This webpage is not available

ERR_CONNECTION_RESET
-----------
12322 HTTP Returns:  Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

**Comment by l-arnold** [comment]
I would like to Close this for now as there have been changes to LAPP that are giving functional service at present.  Odoo build may still have issues but lets close this for now.

**Comment by l-arnold** [comment]
Found that If I have this in (or all of) my Virtual Host 80, it redirects very well to Hpps 443

    RewriteEngine on
    ReWriteCond %{SERVER_PORT} !^443$
    RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R=301,L]
