### ISSUE TITLE
(Jessie RC1 TKLDEV) SSL in LAPP (assume others)

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#347]
Got LAPP up and Running to see barebones situation.

It appears that NO Port 443 is Transferring over into Apache "Existing Virtual Hosts" after a TKLDEV run in Jessie RC1.  (Assume a TLS migration subject, but controlled view of such would be helpful to see)

In Webmin Apache I have ports: (LAPP)
"Any" , 80, and 12322 showing in (Existing Virtual Hosts)

That Said, I can Run Webmin 12321 with Certificate Error accepted.

In IE8: WEBSHELL will not actually start however after "continue to this website" in IE8. though I see in the Tab Header "Shell in a Box".  (Get Error on Page finally)

In CHROME v42 - Can run WEBSHELL on Chrome,  HTTPS likewise seems to be enabled.

 (Webmin's FileManager runs on IE8 but not on Chrome).  

Both need to be running to be functional it seems (I recommend Bitvise SSH Client for somewhat of an alternative to both -  has both shell and graphical FTP, but no insitu editing as Webmin Filemanager has)

**Comment by JedMeister** [comment]
I don't know IE8 at all but my first guess is that this issue is due to the default disabling of SSL in all Debian Jessie software. Only TLS is used now for HTTPS connections. Webmin which only supported SSL has now been hidden behind a TLS tunnel (provided by stunnel).

The Webmin FileManager issue is the result of what happens when you try to load a Java applet (FileManager) in a browser (Chrome) that now no longer supporting NPAPI - which is what Java uses to provide the Java plugin.

To get everything functioning in a single web browser you'll need to install Firefox...

I know that it doesn't really 'solve' the issues you reported, but there isn't too much for us to do I don't think. If you agree, then perhaps we should close this issue? Otherwise can you offer some clear suggestions of what we might do?

**Comment by l-arnold** [comment]
for now just comMen on the landscape.  Might be worth documenting in a Navigating brief how to organize ones self for Tkldev interactions.  There are docs of this nature for navigating in Git hub or doing TKL development for. instance.  Let's close this and move to forums topics of the sort.

**Comment by JedMeister** [comment]
Sounds good. PS I just corrected my post above. I stated that Webmin didn't support TLS. That is wrong and I meant Webshell doesn't support TLS...
