### ISSUE TITLE
[Jessie] PostregreSQL inithook doesn't restart PostgreSQL daemon

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#362]
In the latest build of the LAPP appliance PostgreSQL is not running by default.

It seems that the inihook (password set/reset) seems to stop the PostgreSQL service and not restart it.

**Comment by l-arnold** [comment]
Just ran Lapp install with new TKLDEV Jessie RC1. 5-19-15 
Seems that Server did start at boot.

Needed to login to Adminer with Postgres Username and PW.
Inside, I found that "Template0" is an Invalid Database

Template0 is populated as is Root and Postgres
I can't say that I see any differences yet between them.  Expect that perhaps one Template should populate Root, and another Postgres (but not clear on this or comparing to old install)

The other Databases (public) were empty, but

**Comment by JedMeister** [comment]
FWIW the server starts ok, it's that the inihook (when you set the 'postgres' password) it stops it and doesn't start it again...

As for the default DBs/templates I don't know much about PostgreSQL really so am no immediate help there... 

AFAIK that is the default Debian Jessie PostgreSQL setup. IIRC correctl there aren't any TKL custom DBs added or subtracted (although I'm pretty sure that phpPgAdmin added it's own DB).. Not sure how it compares to v13/Wheezy either... I guess I should have a look...

**Comment by JedMeister** [comment]
Closing this as it no longer seems to be an issue. Please reopen if need be...

**Comment by JedMeister** [comment]
Reopening this as it seems I shut it too soon...!

**Comment by DocCyblade** [comment]
I posted in the other odoo thread but reposted here 

@JedMeister Ok, so I played around with the python script and this is whats going on at 
https://github.com/turnkeylinux/common/blob/master/overlays/pgsql/usr/lib/inithooks/bin/pgsqlconf.py#L61

it's trying to start the service (it's already running) it's failing because it is trying to get the status of the service by https://github.com/turnkeylinux/common/blob/master/overlays/pgsql/usr/lib/inithooks/bin/pgsqlconf.py#L49

I think it's because of the new init system in jessie. You get a different result now with running /etc/init.d/postgresql', 'status I think the script needs revised

**Comment by JedMeister** [comment]
Fixed: https://github.com/turnkeylinux/common/pull/51
