### ISSUE TITLE
Easy way to add SSL certs to TurnKey appliances

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#382]
It'd be great if there was a really easy way to add 3rd party trusted SSL certs to TurnKey appliances. The quicker, easier, most reliable way possible... 
##

**Comment by l-arnold** [comment]
Its Pretty Easy and I think it could be scripted.  Difficulty comes when you get into EV Certs that have multiple layers to them.

Could for instance however Generate CSR at first Boot
Be Presented with the CSR text.
Go to your SSL Provider in another Window
Drop the CSR, buy the CERT, Get Emailed Back
Then firstboot, or in Webmin Later, tie the CSR and Cert(s) together.

**Comment by l-arnold** [comment]
Could also get a contract with a Cert provider to do this via API.  Basically have it run through the Hub if you want (would need a yes/no branch on the inithook)

I like Namecheap.com

**Comment by l-arnold** [comment]
My thought for now is to make a Button link to Docs for (at least my) Appliances.

One of the sections would give a clear instruction on how to install a simple SSL via Webmin and SSH.

I think this solves it for now.  Can be a project moving forward.

**Comment by JedMeister** [comment]
Ideally we'd love to be able to do this via the Hub. But to start with we'll probably just have some helper script (so via commandline)

**Comment by JedMeister** [comment]
On https://github.com/turnkeylinux/tracker/issues/392#issuecomment-111312106 @l-arnold provided some info directly relevant to the Magento appliance but is possibly also generically useful for this issue.

**Comment by dashohoxha** [comment]
How about using Let's Encrypt SSL certificates:
- https://letsencrypt.org/howitworks/

They promise to give them for free and to install them programatically (via a script). So, I can imagine that each appliance can get automatically a free SSL certificate on init hooks.

**Comment by JedMeister** [comment]
That's the plan! :+1:

**Comment by Dude4Linux** [comment]
I was thinking along these lines when I added the --csr option to turnkey-make-ssl-cert.  My thought was to make it easier for the admin to generate a certificate request in a standard format accepted by providers like StartCom.  The problem I see with acquiring a certificate during firstboot is that a fair amount of information about the certificate owner needs to be collected for the certificate request.  If many appliances are to be created, then some method of pre-seeding the common information is needed.

**Comment by JedMeister** [comment]
Moving this to v14.2 as we'd like to push the v14.1 out soon. Obviously feature requests that have already been included will stay; but otherwise focus for v14.1 is now shifting to bugfixing and maintenance.

@Dude4Linux - Very good points.

I must admit that that's why I was thinking doing it via the Hub (obviously supported on the free plan) might be the best way to go. Although obviously supporting pre-seeding would be useful too.

**Comment by gordon-morehouse** [comment]
Let's Encrypt is now live and no longer in beta.

Adding support for automated Let's Encrypt SSL setup would be a great improvement over self-signed certs, IMO.

Let's Encrypt certs do [expire every 90 days](https://letsencrypt.org/2015/11/09/why-90-days.html), so automated renewal will also be needed.

**Comment by gordon-morehouse** [comment]
I documented what I did on a Turnkey appliance. Pasting it here. It's probably not exactly what you all would want to do, but it's a start. I did this on my first TKL box so no potshots please :)

## Installing LetsEncrypt SSL certs for HTTPS-based services

Refer to https://letsencrypt.org/getting-started/ as needed.

Do this as your non-root sudo user (it will require sudo, but let's do it that way instead of running this as root). *On some platforms, this command installs a build toolchain* if one is not present. You may not want to leave a build toolchain on production servers.

    $ git clone https://github.com/letsencrypt/letsencrypt
    $ cd letsencrypt
    $ ./letsencrypt-auto --help  # this installs a build toolchain

Now, get a cert for yourself. Since the letsencrypt client in 'standalone' mode needs to use ports 80 and 443, we need to shut down any web server that is running (for example, the default, lighttpd). Once you've done that:

    $ sudo service lighttpd stop
    $ ./letsencrypt-auto certonly --standalone -d yourbox.example.org

Now enter an email as requested and agree to the terms. You will receive cert files in <code> /etc/letsencrypt/live/yourbox.example.org/</code> which you must tell webmin and shellinabox to use, since they each use their own HTTP server.

Don't forget to restart your web server once you're done with the letsencrypt-auto client in standalone mode.

Get the self-signed certs out of the way, keeping a copy if you need them later:

    # cd /etc/ssl/certs ; mv cert.crt cert.crt~ ; mv cert.key cert.key~ ; mv cert.pem cert.pem~

Then (is this step necessary?), in <code>/etc/ssl/certs</code> create a file <code>lets-encrypt-x3-cross-signed.pem</code> and put the content at this URL into it: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt (see https://letsencrypt.org/certificates/ for details)

Now link in the Let's Encrypt certs. Note that we create one cert by concatenating two separate files - this puts a file in your /etc/sssl/certs directory that is NOT a symlink, so be aware.

    # ln -s /etc/letsencrypt/live/yourbox.example.org/privkey.pem cert.key
    # ln -s /etc/letsencrypt/live/yourbox.example.org/cert.pem cert.crt
    # ln -s /etc/letsencrypt/live/yourbox.example.org/chain.pem cert_chain.pem
    # cat /etc/letsencrypt/live/yourbox.example.org/privkey.pem /etc/letsencrypt/live/yourbox.example.org/cert.pem > /etc/ssl/certs/cert_combined.pem

Now deal with permissions:

    # chown root.certssl /etc/ssl/certs/cert_combined.pem
    # chown root.certssl /etc/letsencrypt/archive
    # chown root.certssl /etc/letsencrypt/live
    # chmod g+rx /etc/letsencrypt/archive
    # chmod g+rx /etc/letsencrypt/live

### Lighttpd config

Edit <code>/etc/lighttpd/lighttpd.conf</code> 

In the :443 config section, place the current snippet for Lighttpd from https://cipherli.st/ taking care to place ssl.engine = "enable" at the top, and to comment out defaults which conflict with the CipherList config snippet.

The snippet will change from time to time, but here is one from April 2016.

    ssl.honor-cipher-order = "enable"
    ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
    ssl.use-compression = "disable"
        setenv.add-response-header = (
        "Strict-Transport-Security" => "max-age=63072000; includeSubdomains; preload",
        "X-Frame-Options" => "DENY",
        "X-Content-Type-Options" => "nosniff"
    )
    ssl.use-sslv2 = "disable"
    ssl.use-sslv3 = "disable"

Now, point Lighttpd at your various cert/key/etc files:

    ssl.ca-file = "/etc/ssl/certs/cert_chain.pem"
    ssl.pemfile = "/etc/ssl/certs/cert_combined.pem"

*Make sure to comment out defaults in the :443 config section which conflict with the above.*

    # service lighttpd start

Starting the service should result in an "OK", possibly with some spew. Now you should be able to hit https://yourbox.example.org/ without SSL warnings.  If you like, run the [SSL Labs test|https://www.ssllabs.com/ssltest/] on your server to check for problems.

*Don't forget to unset any firewall rules allowing outside access to port 80 and 443* if you are not allowing outside connections to said ports, as is described in this guide.

### Webmin SSL config

1. Edit <code>/etc/webmin/miniserv.conf</code> and set <code>keyfile=/etc/ssl/certs/cert_combined.pem</code>
1. <code># service webmin restart</code>

Webmin should no longer cause self-signed cert errors in the browser. Note that Chromium 49 does detect an "obsolete cipher suite" in use if you look at details under the green lock icon.

### Shellinabox SSL config

You'll need to hit the shellinabox URL before doing this, as it creates a self-signed cert for the hostname of your machine when you first use it. It will prevent mistakes if you can see the filename of the cert.

After you've loaded the URL (you can close it right away), on the command line:

    # service shellinabox stop

In <code>/var/lib/shellinabox</code> delete the (broken) <code>certificate.pem</code> symlink, then:

    # ln -s /etc/ssl/certs/cert_combined.pem /var/lib/shellinabox/certificate.pem

Now look for the host-specific cert in <code>/var/lib/shellinabox</code> and note the FILENAME, then:

    # rm /var/lib/shellinabox/FILENAME
    # ln -s certificate.pem /var/lib/shellinabox/FILENAME
    # service shellinabox start

Now verify that there are no SSL warnings in the browser when you connect to the in-browser console.

**Comment by JedMeister** [comment]
Thanks for sharing Gordon. FWIW though by default both Webmin & Shellinabox run behind stunnel. That's probably why the cert.pem symlink is incorrect. Webmin does include it's own server so having that available is probably not such an issue (although it doesn't then pick up our improved cipher suite that we include in stunnel). 

Shellinabox OTOH is an issue. AFAIK it doesn't support TLS OOTB; hence why we put it behind stunnel. The version in Debian has been patched to work around that and we will probably rebase on the Debian version at some point in the future. The reason why we still use our own fork is that we have already extensively tested it and haven't tested the Debian version.

**Comment by gordon-morehouse** [comment]
I realized that my pasted docs are written based on 13.0. I'm going to set up 14.1 and I'll edit my comment above.

**Comment by gordon-morehouse** [comment]
Updated my docs after setting up Let's Encrypt certs on a 14.1 OpenVPN appliance. I hope they're useful.

**Comment by JedMeister** [comment]
@gordon-morehouse - Thanks heaps. I just edited your post a little to note that it explicitly relates to lighttpd webserver. We had some confusion from a user who followed your exact instructions on an appliance that didn't include lighttpd and he was wondering why it didn't work! :smile:

**Comment by JedMeister** [comment]
Closing this as all v14.2 appliances include a confconsole plugin to get (and set auto renewal of)  Let's Encrypt certificates.

Please see the [confconsole docs](https://www.turnkeylinux.org/docs/confconsole) - the Let's Encrypt stuff is explicitly detailed [here](https://www.turnkeylinux.org/docs/confconsole/letsencrypt).

**Comment by mhermosi** [comment]
Sorry to write on this closed thread but I have another scenario, I already have a centralized management for my SSL certificates (Let's Encrypt) and the centralized tool allow me to script the deployment to a remote machine... would be nice if TurnKey had an API or way to add and update the SSL certs from external centralized management

**Comment by JedMeister** [comment]
@mhermosi - no problem, apologies on slow response.

Could you please elaborate on what you have in mind? On face value it sounds like it could be cool, but I'm not completely clear on exactly what you are after.

Also, I appreciate you posting on an existing issue that already somewhat fits with your request. However, in this case I am not keen to reopen this one. So it might be best to open a new issue and clarify exactly what you are suggesting. I can't guarantee that we will implement it in a timely fashion (or at all even) but as a new issue then at least it won't get forgotten! :smile:
