### ISSUE TITLE
Update apps that use apache-lighttpd overlay to use the new adminer overylay

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#403]
Need to identify the apps that currently use it

Apps that need to convert
1. LAMP (done
2. LAPP (done)

**Comment by DocCyblade** [comment]
Note: lamp and lapp are both found in common mk lapp.mk and lamp.mk

**Comment by DocCyblade** [comment]
I have created new branch on my forked copy of common called [laXp-adminer-overlay-update](https://github.com/DocCyblade/common/tree/laXp-adminer-overlay-update) and I am testing the lamp and lapp build now

**Comment by DocCyblade** [comment]
I did a few test builds on the lamp app where I changed the overlay but the CHROOT on root.sandbox is not working when I try and go to the port via web browser. I did a `netstat -net -all` and it only showed it was listening on ipv6. So I am reverting back my common and lamp fork back to master and doing a build see if that turns up anything. I am wondering if there is a bug in the current lamp build. 

I'll report back later with my findings. I will also do a ISO instal to rule out any strange CHROOT issues that could be going on.

**Comment by DocCyblade** [comment]
Did another build this is what I see when I do a `netstat -net -all`

```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          11496      
tcp        0      0 127.0.0.1:8124          0.0.0.0:*               LISTEN      13         11380      
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      104        134712     
tcp        0    336 10.6.19.99:22           10.6.19.3:51011         ESTABLISHED 0          107297     
tcp        0      0 10.6.19.99:22           10.6.19.3:50280         ESTABLISHED 0          104160     
tcp6       0      0 :::80                   :::*                    LISTEN      0          135048     
tcp6       0      0 :::22                   :::*                    LISTEN      0          11505      
tcp6       0      0 :::443                  :::*                    LISTEN      0          135052     
tcp6       0      0 :::12322                :::*                    LISTEN      0          135056     
root@tkldev ~# 
```

As you can see its only listening on ipv6. Can anyone confirm that this is a bug? I have not looked at the config yet doing that now

**Comment by JedMeister** [comment]
TBH I am not quite sure what is happening on your end... I just did a clean build of LAMP (using the existing code) and it worked as it should, I then changed `common/mk/turnkey/lamp.mk` so that it used the `adminer` overlay (rather than the `adminer-apache`) one and rebuilt it. It works a treat for me.

Strange thing is though that even though it is working fine for me, netstat returns the same thing as you...!?

````
# netstat -net -all
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          11316      
tcp        0      0 127.0.0.1:8124          0.0.0.0:*               LISTEN      13         9886       
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      104        46849      
tcp        0    352 192.168.1.152:22        192.168.1.251:48703     ESTABLISHED 0          10063      
tcp6       0      0 :::80                   :::*                    LISTEN      0          46601      
tcp6       0      0 :::22                   :::*                    LISTEN      0          11318      
tcp6       0      0 :::443                  :::*                    LISTEN      0          46605      
tcp6       0      0 :::12322                :::*                    LISTEN      0          46609 
````

Nice Adminer theme BTW :smile:

**Comment by JedMeister** [comment]
Did a little research and it turns out that Apache uses ipv6 sockets but they can handle both ipv4 and ipv6 traffic (ipv4 is remapped to ipv6). So unless you specifically set Apache to use ipv4 exclusively then you won't see ipv4 connections in netstat (they exist but as they are remapped to ipv6 netstat sees them as ipv6). 

So that mystery is solved... But the mystery of why your server isn't working still remains...

**Comment by DocCyblade** [comment]
I'll do a full reboot and rebuild could be something going on with.

**Comment by DocCyblade** [comment]
I did a clean install, same thing. This time a took a look at the `/var/log/apache2/error.log` and found this little line that sheds some light on the subject.

```
[Mon Jun 29 02:42:45.328252 2015] [ssl:warn] [pid 32188] AH01906: localhost:12322:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Jun 29 02:42:45.328287 2015] [ssl:warn] [pid 32188] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
```

It's a SSL error. I then remembered, I did not run the first boot ssl gen inithook. Once I ran that, restarted apache2. Good to go on the lamp, testing lapp now

**Comment by DocCyblade** [comment]
Both LAMP and LAPP build and test correctly with the adminer update.

@JedMeister should I submit pull request on this to should a do a few more changes, like change the db-driver to only show mysql(LAMP) or postgres(LAPP) and update the verbiage and remove phpMyAdmin and phpPgAdmin and replace with Adminer? Or should these by separate pull requests?

**Comment by DocCyblade** [comment]
@JedMeister - also is lamp and lapp the only ones that used adminer update?

**Comment by JedMeister** [comment]
>should I submit pull request on this to should a do a few more changes, like change the db-driver to only show mysql(LAMP) or postgres(LAPP) and update the verbiage and remove phpMyAdmin and phpPgAdmin and replace with Adminer? Or should these by separate pull requests?

I don't think it really matters.... Generally you separate branches/pull requests to separate specific issues/purposes; but in this context so long as each change is self-contained then that's ok too. So they could be separate (because they are self-contained) or combined (because they are all parts of the same issue/purpose) 
>also is lamp and lapp the only ones that used adminer update?

I have just grepped through all the appliance code and it appears thiat it will actually be really easy to update; just need to update lamp.mk and lapp.mk in common! All the other appliances that have Adminer appear to leverage those 2 makefiles...

**Comment by DocCyblade** [comment]
I'll go ahead a submit this so it's done. There are some other things to work on for lamp/lapp and mysql/postgres appliances. Seems like those are the ones I mostly tinker with anyways. Look for a pull request soon

**Comment by JedMeister** [comment]
For the record Alon & I discussed this last night and he really likes it. He was saying actually he'd like to reorganise common (at some point down the track - not anytime soon) so that it separated by application rather than conf/overlay/mk. Common would then become something of a collection of poor man's packages... Anyway I digress...

**Comment by JedMeister** [comment]
Just realised that this wasn't tagged etc... I know that it's about to be closed but better late than never! :smile:

**Comment by DocCyblade** [comment]
Pull request merged. Good to go here
