### ISSUE TITLE
Simple Invoices

### ISSUE THREAD

**Issue by Green-Guy** [turnkeylinux/tracker#405]
Reports will not show. I searched and found this article:

http://simpleinvoices.org/wiki/using_simple_invoices_on_bsd_or_darwin?s=reports

Tried the fix but did not work for me. Tried using LINUX and BSD. It was initially set to WIN so I am sure it has something to do with this value but I have no clue. Not sure what the issue is. Please assist.

**Comment by DocCyblade** [comment]
@Green-Guy I assume your testing was from a TKLDev build from the current source of simple invoices on turnkeylinux git repo? Or was it something else?

**Comment by Green-Guy** [comment]
Yes current download from the site. Everything else is great. Just the reports do not show.



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by DocCyblade** [comment]
@Green-Guy - I'll do a quick build and see whats what while I am waiting for some other things I am working on. See if I can confirm what you're seeing. 

For testing purposes, are you doing a CHROOT_ONLY build or your doing a full ISO install from the make build?

**Comment by Green-Guy** [comment]
My apologies for not being more savvy. I just installed the virtual machine and went from there. Nothing unique.



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Green-Guy** [comment]
Any update? Thanks!



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by JedMeister** [comment]
A little bit of miscommunication here I think... @Green-Guy you downloaded the ISO or VM (etc) from the website? If so then you are using v13.0. 

I think @DocCyblade thought you were testing the latest build (the v14.0 build of TurnKey SimpleInvoices).

I'm really sorry but currently I am flat out working on the [v14.0 release](http://www.turnkeylinux.org/blog/marching-towards-14.0rc2) so haven't got the time to look into this further right now. As @DocCyblade hinted though the new (v14.0) [SimpleInvoices build code](https://github.com/turnkeylinux-apps/simpleinvoices) has been updated and I'd be really interested to hear if this is still an issue in the latest build. Unfortunately we don't yet have ISOs to download but they aren't hard to build yourself if you are interested; see my blog post on how to do it [here](http://www.turnkeylinux.org/blog/howto-build-isos-with-tkldev).

Regardless could we please have some more info on the nature of the problem. I just did a quick google to see if anything jumped out at me and it seems that there are a whole range of report issues; mostly around php errors. When you say "Reports will not show" do you mean you get a blank screen in your web browser? If so it is probably a PHP error (please check /var/log/apache/error.log and post it back). Otherwise there are reports of SI reports being blank (apparently also related to PHP issues) and SI reports not being formatted properly...

Also if you could please document the steps on how I would be able to recreate this on a fresh install would also be useful. Thanks...

**Comment by DocCyblade** [comment]
@JedMeister - I should have been more specific, thanks for stepping in! I have not had much time over the weekend as I would like. Was on call for the three day weekend and it was very busy. Just worked 16 hours... Thought I would do some TKLDev to relax :-)

@Green-Guy - I'll be happy to try an replicate the issue, but like Jed asked we want to make sure we are all on the same page.

**Comment by Green-Guy** [comment]
Thank you for the updates guys much appreciated. It is the 13 release off the site. I will follow the guide you posted to see if can get it running on 14. I will let you know as I have time to allocate.



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Green-Guy** [comment]
I will check into the 14 thing you posted. I did nothing special to create the error. Just setup the simple invoices vm. Added invoices and tried to view the reports. No changes or manipulation were done on the vm to create the issue. I googled the blank page issue and came up with the article I posted initially. The values were set to WIN so I changed them as indicated but still the issue persists. I have not modified any of the php stuff.



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by DocCyblade** [comment]
@Green-Guy - Did you download the VM or the ISO? It should be the same... but I want try and replicate exactly your build. I am trying it now with both v13 and a new build v14. I'll post what I find

**Comment by DocCyblade** [comment]
@Green-Guy - I did an ISO install from a v13, added a biller, and a product. Created an invoice, and clicked reports. I can confirm that nothing shows on the screen. However, there is data being output to the browser. 

Strange that no one has said anything? Till now.


@Green-Guy did you do all the updates on first run?

**Comment by Green-Guy** [comment]
I downloded the vm version and spun it up on my esxi box. I did not actually do any updates on the vm.



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Green-Guy** [comment]
I also get the same thing. There is page source but nothing actually renders.



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by DocCyblade** [comment]
@Green-Guy Ok, the issue is PHP. The reporting code uses some functions that were removed in PHP 5.4 causes the issue. SI forms show a lot of people have this issue with 2011 release in regards to reporting. Looks like it does work with PHP v5.2. I tried a brunch of things that were mentioned but did not solve the issue.

@JedMeister - Looks like reports are busted and I don't see an updated version other than their beta and that does not look stable. Should SI be excluded from v14 until they release a stable that works with 5.4/5.5?

**Comment by JedMeister** [comment]
@Green-Guy - thanks for helping @DocCyblade troubleshoot...

@DocCyblade - Bugger! Yes I think that you are right... We can't release a broken appliance (if we know it is). And I'm not a big fan of using unstable and/or beta software...

**Comment by JedMeister** [comment]
We'll defer SI for the v14.0 release and relook at it for v14.1. Hopefully by then they'll have made a new stable release that we can include...

**Comment by Green-Guy** [comment]
I spun up a new Debian server with all necessary stuff (php, apache, etc) on my existing ESXI box installed the 2013 beta code for Simple Invoices and imported my database. All seems stable and working. Reports are functional. I really liked the ease of use your vm provided. Just needed the reports to easily track funds. Appreciate all the assistance and hope to see a new appliance as soon as it's ready for the road.



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by JedMeister** [comment]
@Green-Guy Thanks for testing out the TurnKey appliance and reporting the issue (and helping us work out what was going on). Thanks also for your report on the current state of their beta. I am almost (but not quite) inclined to use the beta for a v14.0 appliance but I won't...

It may not be relevant to you if you are already an SI user, but from our perspective perhaps we might look at a new appliance using "Invoice Ninja"?

https://www.invoiceninja.com/
https://github.com/hillelcoren/invoice-ninja

**Comment by DocCyblade** [comment]
We may have a valid replacement or addition. I am going to test drive this out invoice ninja looks good. I actually need a new invoice app soon. @JedMeister I'll open a new issue for a new app if I find that this is really good and I can get it built.

As for SI I'll contact the owner of SI see if they have a idea of a stable release date for those SI fans out there.

**Comment by DocCyblade** [comment]
I have sent an email to the Justin Kelly (http://blog.justin.kelly.org.au) to see if he had a time line for the stable release hopefully he will contact me back directly or post here. I gave him the link to this issue.

**Comment by JedMeister** [comment]
Great work @DocCyblade thanks mate. 
FWIW I created an Issue on their GitHub repo (https://github.com/simpleinvoices/simpleinvoices/issues/213) and have been informed that it (the beta) should be fine... So perhaps we could do that. I'm still a little hesitant but the comment (over there) along with @Green-Guy 's report perhaps...? What are your thoughts Ken?

**Comment by DocCyblade** [comment]
@JedMeister Well most open source software is beta for years, some times never "stable" I did a quick look at the code base it looks like it pretty active. I too have mixed feelings about it. Since if I was "looking to download SI" I would get stable 2011. However is "stable" really stable, since you would have to downgrade to php 5.3 it seems for it to work correctly. Just thinking out loud.

If we were to proceed, then we need to make a way or give TKL users easy way to update their SI installation. Whats TKL stance on apps security and updates for things like this

Now putting on my TKL end user hat, when I am looking for something like SI I just want to download it and let it work. I really don't care it its beta or not. As long as it works, and if I want to update it, it needs to be easy (like using TKLBAM) 

With that said, I think if we can make it work, and make it easy to upgrade I am for it

**Comment by JedMeister** [comment]
@DocCyblade - As a general rule (yet to be broken from my experience but maybe one day?) TKL draw a line in the sand on using older (unsupported) fundamental components such as PHP. That is based on the fact that we depend on the Debian packages to make TurnKey both rock solid and secure (as possible). If upstream provided a supported LTS type version (with security patches) then that would be a possibility but I'm fairly sure they don't...

Not that it wouldn't be possible. We could (theoretically) downgrade to the Wheezy version of PHP (using pinning) but I think it is hacky and far from ideal. I know that all options ATM are somewhat hacky, but TBH I'd rather provide SI beta (based on reports of it's stability) than a hacky (PHP) workaround to make the stable version work.

If we were to push ahead with the current SI beta; then I would be inclined to clone their git repo into the appliance (using `--depth 1` to ensure minimum size) and then users could (at least in theory) easily update with `cd /var/www/simpleinvoices && git pull`. Obviously though that would rely on SI not changing their DB layout. If they did then that would totally break the appliance... So TBH I'm not certain that automating the update in some way is a good idea at all... I think documenting it would be better; then we could add the cautionary notes...

So final word, I am still torn on this. I'd be really interested to hear from you what the dev says...

So, round up of the choices (ATM) that are on the table as I see them:
1) defer the appliance for now
2) use the beta (master branch of repo) and take pot luck on the state of it
3) use a previous beta version release (download zip/tar.gz)
4) use master branch but at specific commit (so it should always build the appliance from a working point in time, even if they accidentally introduce a regression into  the master branch)
5) use master branch but at specific tag point (would need to double check best way of doing this with the version of git in Jessie; `-b` switch should do it...)

2 & 4 (& maybe 5) would support fairly easy update although both have risk of breaking the appliance. Reports suggest that the risk would be minimal but we don't know for sure...

**Comment by DocCyblade** [comment]
I Iike the idea of 5 however if they remove the tag building breaks. Number 4 seems to be the best and we can control what commit the appliance is at. Better for testing.

**Comment by JedMeister** [comment]
Ok. Well my current plan is 1 (for now anyway, I could probably be swayed). 

However; I think that your point above is valid:
>Now putting on my TKL end user hat, when I am looking for something like SI I just want to download it and let it work. I really don't care it its beta or not. As long as it works, and if I want to update it, it needs to be easy (like using TKLBAM)

So if you'd like to go down the path of 4 (or 5 even) then I would totally support that (and am fairly sure that i could persuade Alon to agree - especially if we get a core dev to say that its "stable enough")! :smile: 

However I still stand by my opinion on documenting the update process (with relevant warnings) rather than automating it; or even providing a helper script...

**Comment by DocCyblade** [comment]
i am also ok for option one if we have another option out there like invoice ninja. I also agree with your documentation statement. I guess we should let Alon have the final vote. If we do option one, maybe we should proceed with invoice ninja, looks promising.

**Comment by JedMeister** [comment]
We have BambooInvoice in the library already (it is abandonware but stable and seems to work fine).
And if we defer it doesn't mean never, just means not at the moment. We can add Invoice Ninja too though regardless...

**Comment by JedMeister** [comment]
I just did it... No 4: Updated the SI appliance to use 'master' branch and tested all working fine. Alon said to just use master but take note of the tested commit.

FWIW it seems to work well.
