### ISSUE TITLE
Etherpad app - 502 bad gateway nginx 1.2.1

### ISSUE THREAD

**Issue by vr00m** [turnkeylinux/tracker#440]
Fired up a freshly downloaded etherpad 13 app, on virtual box 4.3.28 r 100309 on windows 8.1 with TLKBAM not initialized. But connecting to the Etherpad server (running on my laptop) from my laptop's browser, gives me the 502 bad gateway -nginx 1.2.1 page.

/var/log/nginx/error.log and /var/log/nginx/access.log are empty

/var/log/nginx/nodejs.access.log contains:
127.0.0.1 - - [04/Aug/2015:19:29:15 +0000] "GET / HTTP/1.1" 502 172 "-" "Wget/1.13.4 (linux-gnu)" 
192.168.1.5 - - [04/Aug/2015:19:36:11 +0000] "GET / HTTP/1.1" 502 172 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
192.168.1.5 - - [04/Aug/2015:19:36:17 +0000] "GET / HTTP/1.1" 502 172 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0" 

/var/log/nginx/nodejs.error.log contains:

2015/08/04 19:29:08 [error] 2589#0: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.7, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "192.168.1.7"

2015/08/04 19:29:15 [error] 2589#0: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "localhost"

2015/08/04 22:42:50 [error] 2627#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.5, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: 192.168.1.7" 

where 192.168.1.5 is the machine I'm connecting from, and 192.168.1.7 is the etherpad server.

**Comment by JedMeister** [comment]
Sorry for slow response... We are currently trying to get the v14.0 release out the door and are at that weird place where you don't want to waste time fixing old out of date appliances; but haven't quite got the new ones ready for public consumption...

So TBH I don't have anything to help you with right now sorry. However; if you would like to build (and help test and/or improve) the new etherpad appliance (which is newer and better and based on Debian Jessie instead of Wheezy)) then please have a look at this [blog post](http://www.turnkeylinux.org/blog/howto-build-isos-with-tkldev). It should walk you through setting up the dev environment and build the new etherpad ISO.

**Comment by JedMeister** [comment]
Whilst this bug still exists in the v13.0 appliance I am closing this as the v14.0 appliance has been released and this issue appears to be resolved.
