### ISSUE TITLE
[TKLDev] Feature Request: HTTPS downloader cache/proxy script

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#467]
Since HTTPS traffic is not cached via the proxy see (https://github.com/turnkeylinux/tracker/issues/466#issuecomment-142472156) for details. In that feature request (#446) was a request create a wrapper for git-clone, here it would be downloading files over https so they are stored locally (cached) 

Maybe write a command like fab-https-dl to download files over https with caching baked in. 

If this would come to realization, it would change ALOT of the common and downloader scripts that use HTTPS or some of them redirect to a HTTPS connection. Or you could wrap all "downloads" through it and the script could decided to use the build in proxy for http or proxy it itself and store the file for later use if it's over https. 

Thoughts?
##

**Comment by JedMeister** [comment]
Could be a good way to go. I guess then that downloads wouldn't use a full url; just the domain and path (and let the caching downloader work out what protocol to use)? The downside that I see with a method (if we are going to do it properly and actually remove the issue as a whole) is that we will then need to add/implement scritps for each command/tool. And currently there are quite a few... In fairness they are probably not caching now anyway; but like I say if we fix it, let's fix it for everything... So OTTOMH we'll need to cover the cases we've discussed already (git & curl/wget) but also all the other tools like pip (python dep manager), gem (ruby dep manger), composer (php dep manager), npm (nodejs package manager) as well as other third party tools (such as drush for durpal; mage for magento, etc)

Perhaps going the MITM caching proxy direction (as mentioned https://github.com/turnkeylinux/tracker/issues/466#issuecomment-142476727) we may be able to circumvent those issues? Obviously in many (most?) contexts a MITM https proxy is a bad idea; but IMO in this usage scenario it's a good idea! Perhaps we could force all internet traffic through a (MITM) caching proxy? Then it should work for all future apps that download stuff (not just the ones we currently use).

Thinking about this some more; perhaps that sort of set up will be much easier once we containerise the build process (so build in a LXC container rather than a chroot? Then we can actually control the build space's network access? Hmm... Lots of food for thought...

**Comment by JedMeister** [comment]
Some more bits:
Using git --reference (http://randyfay.com/node/93)
Note though that you will also need to `git repack` when done or the repo won't work... (http://randyfay.com/node/119)

As mentioned it looks like that's what drush does (https://github.com/drush-ops/drush/blob/master/commands/pm/package_handler/git_drupalorg.inc#L56-89)

And a similar suggestion for composer too
https://github.com/composer/composer/pull/1338

**Comment by DocCyblade** [comment]
Boy did I open a can of worms! 

Good point in all the other scripts that use curl wget internally. 

Again making this transparent or using a different proxy that would work for both https/http traffic would be good.

Lots of food for thought, my head hurts!

**Comment by JedMeister** [comment]
Yeah I agree (on all counts)! :smile:

**Comment by DocCyblade** [comment]
Moving the conversation here from #466 - I just [cloned tkldev build and setup a working branch](https://github.com/DocCyblade/tkldev/tree/https-proxy) and will start looking around. Current proxy does more than just http proxy, so not sure if squid would fully be able to replace the current or use both.

**Comment by JedMeister** [comment]
> Current proxy does more than just http proxy
Does it? What? It does cache the apt stuff too but that is still http really...

Besides Squid can do anything! :smile: 

IMO a stepped/staged process would be the go. With steps like this:
1. Setup Squid to handle the https proxying only (i.e. side-by-side with polipo)
2. Relieve polipo of general http proxying duties too
3. Remove polio completely and replace all functionality with squid.

Achieving step 1 has real value and would resolve the current issue. Step 2 would make life easier for appliance builders as then appliance build code could all be using the one proxy config. Step 3 would be the end game goal IMO but no rush to reach it...

**Comment by DocCyblade** [comment]
Sounds like a plan.... Looks like I need to read up on squid! I like the stepped approach. I was thinking of doing just that, adding squid and setting it up on another port. Exporting the https_proxy variable so that GIT would use it. I think if we use wget that would work as well for https

**Comment by JedMeister** [comment]
Sounds great! :smile:

**Comment by JedMeister** [comment]
FWIW, @OnGle had a bit of a play with Squid and it seems like that's the go. Regardless though, I'll moving this one to v17.0.

**Comment by JedMeister** [comment]
As per @OnGle's suggestion elsewhere (https://github.com/turnkeylinux/tracker/issues/353#issuecomment-774827928) I'm closing this and opening a new consolidated issue; #1560.
