### ISSUE TITLE
(Still) problems updating WordPress...

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#489]
Argh! It seems this is still an issue in v14.0 WordPress... :cry: 

Please try this and report back:
````
chown -R www-data wp-includes
chown -R www-data wp-admin/{js,css,includes,network}
chown www-data wp-admin/about.php
chown www-data readme.html
````

**Comment by pdipietro** [comment]
I just downloaded today the appliance and the bug is still there.

I tried to apply the cmd as above, but the error persists.

**Comment by JedMeister** [comment]
Unfortunately you are right... We hope to (finally) have this resolved (properly) for the v14.1 release. In the meantime one of our community members has posted a work around on our forums: https://www.turnkeylinux.org/forum/support/20131121/wordpress-ftp-and-update-issues#comment-24662

**Comment by jakesilly** [comment]
Oh my, what a disaster... finally got it working after JedMeister's link. I thought I'd try Turnkey Linux because of all the configuration yadayadas in Ubuntu. This really isn't much better. You should get this sorted out with highest priority and not let these typical problems linger. People turn to Turnkey for an easy and secure way to setup their wordpress. Moving heaven and earth to get the updates working is not a good sign.

**Comment by JedMeister** [comment]
Thanks for your feedback @jakesilly . 

FWIW the problem isn't getting it to work. The problem is balancing security against user friendliness. Because from feedback we receive TurnKey users also look to us for security.

So we have tried to improve usability incrementally so that we can keep the install as locked down as possible. Unfortunately (as you can see) that hasn't really panned out quite how we would have liked. 

As per the commits to the code (noted above) for v14.1 we have decided to ditch the generic Linux server security "best practice" in favour of making it more user friendly. The upside (that IMO makes the tradeoff legitimate) is that we can enable automated WordPress minor updates. So whilst the overall server security is arguably reduced (as Apache has greater access; thus if Apache or PHP is compromised more damage can be done) the WordPress security itself should be better (as it will auto install minor updates).

**Comment by jakesilly** [comment]
I do get the picture... but with these trade-offs, I think you also have to keep in mind that people need the updates to come in to stay secure with the wordpress-bit. If people don't get it out of the box, they WILL manually make their server-side less secure to keep the updates coming in.
People who care THAT much about server security will probably start off with a stable debian distro and build the whole setup themselves, tying down whatever needs to be tied down for 99.99999% system security.
I'm probably a nobody, but the strong point of something like Turnkey is you install an iso and you get wordpress working out of the box. Just click-a-dee-click and you have a site up and running without having to go through all different tutorials of which only half work because they were written for an older version and yadayadayada.
Of course, security IS important, but if you make something that doesn't work out of the box, get people complaining (or rather asking for advise) about how to make it work as they expect, then direct them to another tutorial and yet some other trick to make it finally work... doesn't it all end up being the same as implementing it straight into a new version of Turnkey. Saves a lot of people a lot of frustration, both users and developers. The end result, in my opinion, is exactly the same. It only takes longer to have to give support and get to deal with annoying people like me ;)

**Comment by JedMeister** [comment]
Of course you're not a "nobody"! You're a TurnKey user and that makes you a somebody; in my eyes at least! :smile: 

The points you raise are totally valid! And I totally agree (especially in light of the time and energy that has previously gone into this - all to no avail). Hence why I've just merged the code to close this issue (hopefully) once and for all. 

The new improved TurnKey WordPress appliance; with minor auto updates enabled and web based "click" major updates supported OOTB will be a part of the v14.1 release (when we get there; hopefully not too far away)

**Comment by jakesilly** [comment]
Really great to see things can move fast and there's actual development on the product.
I have my (private) site up and running now, tinkering with content but when I need a break, I'll definitely check it out and give positive feedback where due ;)

**Comment by slacka** [comment]
@JedMeister 
When turnkey-wordpress-14.1 drops, how will we access this new feature? If we manually 

`# chown -R www-data:www-data /var/www/wordpress
`

will that cause problems in the future?

**Comment by JedMeister** [comment]
Obviously if you install the v14.1 appliance then you'll have them automatically. But if you have v14.0 and want to include the changes that we did for v14.1 then you can essentially just do what we did for v14.1.

The commits of interest are:
 - [Auto minor version updates](https://github.com/turnkeylinux-apps/wordpress/commit/f7b4ff4f37c03131ee2b083462b655031b7b8699): 
Add these entries to your wp-config.php (`/var/www/wordpress/wp-config.php`)
 - [Set permissions](https://github.com/turnkeylinux-apps/wordpress/commit/a8acb11c954e7d26ee294be79b6fec745d632f38): 
Run these lines on your server (`WPROOT=/var/www/wordpress`)

As you can see the chown line you quoted is actually one of the commands we use, so won't cause any issues...

Also FWIW I plan to release v14.1 today! Yay! :tada:
