### ISSUE TITLE
update webmin packages to 1.780

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#496]

**Comment by OnePressTech** [comment]
I have added a new issue requesting upgrade to webmin 1.78 unless there is a reason not to and to install mon pre-configured to monitor the system. If accepted, this new issue would supercede this issue.

**Comment by JedMeister** [comment]
None at all; just that when I posted this 1.770 was the latest...

**Comment by OnePressTech** [comment]
Just thought I would do my bit in the issue tracker :-) I just updated my VM to 1.78 because it is required to load the webmin monit plug-in. Just an FYI, the 1.78 Webmin defaults to a new web-based file manager. The good news...we no longer have to rely on Java being installed in the browser and it now works on Chrome (where Java add-ons have ben disallowed for some time). The bad news is that I found that I could not access all the files in some folders with lots of files. The search capability is not as powerful as the Java version as well. To get the functionality I need I had to return to the Java-based file manager (which is still available at the xxx.yyy1231/file address).

**Comment by JedMeister** [comment]
THanks for the feedback on the filemanager. I had read that in many ways it was superior however it sounds like there are also some deficits. It's very handy to know about those as no doubt we will get questions; and it's saves me the time of having to test it myself! :smile:

**Comment by JedMeister** [comment]
FWI Webmin 1.780 is now in TurnKey's "jessie-testing" repo. It will be merged into the main TurnKey Jessie repo within the next day or two.

I have written a little script that will upgrade just Webmin packages. It will also install webmin-filemin (the new non-java filemanager):
````
echo "deb http://archive.turnkeylinux.org/debian jessie-testing main" > /etc/apt/sources.list.d/jessie-testing.list
apt-get update

rm -f /tmp/list

apt-cache policy webmin* > /tmp/output
echo "webmin-filemin" >> /tmp/output
echo "Installed: yes" >> /tmp/output

while IFS= read line; do
	check="$(echo $line | grep webmin | cut -d: -f1)" 
	[ -n "$check" ] && echo "$check" > /tmp/package
	check=$(echo $line | grep Installed)
	if [ -n "$check" ] && [ ! "$(echo $check | grep '(none)')" ]; then
		echo "Will upgrade/install $(cat /tmp/package)"
		cat /tmp/package >> /tmp/list
	fi
done < /tmp/output

apt-get install $(cat /tmp/list)

service webmin start
echo

rm -f /tmp/list
rm -f /tmp/output
rm -f /tmp/package
````

Or if you want to upgrade all the packages (not just Webmin) then do this:
````
echo "deb http://archive.turnkeylinux.org/debian jessie-testing main" > /etc/apt/sources.list.d/jessie-testing.list
apt-get update
apt-get upgrade -y
apt-get install webmin-filemin
````

**Comment by OnePressTech** [comment]
Nice :-)

This is just in the knick of time since we are going to need to use the Webmin web-based file manager vs. Java-based file manager moving forward once [Oracle drops JAVA browser support](http://www.eweek.com/developer/oracle-dropping-java-browser-plug-in-in-jdk-9.html).

You might want to create a blog post on the upcoming Oracle / Java change since all legacy TKLX VMs operating with an older Webmin will lose their file manager tool.

**Comment by JedMeister** [comment]
As noted in the updated post above, Webmin packages are now in TurnKey's jessie/main repo. I have updated the scripts/snippets above to fit.

I know that you know this already Tim, but for the benefit of others:
FWIW if you enabled the testing repo to get them but now want to disable it; you can either rename it (rename it back again to re-enable it):

````
mv /etc/apt/sources.list.d/jessie-testing.list /etc/apt/sources.list.d/jessie-testing.list.disabled
apt-get update
````
Or delete it all together
````
rm /etc/apt/sources.list.d/jessie-testing.list
apt-get update
````

Closing this issue now... :smile:
