### ISSUE TITLE
Unable to edit controller files

### ISSUE THREAD

**Issue by vinothpr** [turnkeylinux/tracker#508]
Hi,

I am not able to edit python files for my newly created app through the browser. Tried different browsers from different machines still does not work. The code edit frame does not load when I click on the edit link.

regards
Vinoth

**Comment by JedMeister** [comment]
As noted in the [readme](/turnkeylinux/tracker#turnkey-dev-tracker) this is our issue tracker (i.e. for bugs and feature requests). For support, please post on our [support forums](https://www.turnkeylinux.org/forum/support). Also include info on how you are trying to "edit python files ... through the browser" . I don't really understand what your problem is...
