### ISSUE TITLE
Update appliance documents to reference Admin rather than Root for login

### ISSUE THREAD

**Issue by OnePressTech** [turnkeylinux/tracker#543]
On the TKLX Core page (https://www.turnkeylinux.org/core) it is correctly stated that:

"Login as root except on AWS marketplace which uses username admin."

The appliance pages though (e.g. LAMP) incorrectly state that:

"Webmin, SSH, MySQL, Adminer: username root"

It should read:

"Webmin, SSH, MySQL, Adminer: Login as root except on AWS marketplace which uses username admin."

**Comment by JedMeister** [comment]
Thanks for spotting that. :+1: 

Liraz has automated this detail (rather than having to copy paste it into every appliance page) so I suspect when you noted this the fix was already in progress (IIRC he manually did Core before automating the other pages).

So I'm closing this for now but if you spot any that got missed, please feel free to reopen.

**Comment by OnePressTech** [comment]
Yup...all looks good now. Thanks guys :-)
