### ISSUE TITLE
Update Ansible for v14.1 release

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#557]
A pull request for the v14.1 updates has been issued.
https://github.com/Dude4Linux/ansible/pull/1

**Comment by JedMeister** [comment]
Awesome John, thanks for that! :+1: I have merged your changes into the TurnKey repo ready for v14.1. I also made a slight tweak to the changelog. 

FYI your PR was against the master branch of your own repo. That happens because GitHub defaults to doing pull requests against the "original" repo (i.e. yours). The TurnKey repo is the fork of yours. If you wanted to do a PR against TurnKey Ansible repo, you need to do a PR "across forks" (there's a link when you do your PR) and then select TurnKey.
