### ISSUE TITLE
PCI Tests failing

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#566]
Just ran a PCI Security test and get the following "failure".
This one is (redacted) 14, but likely consistent across systems.
(any way to fix?)

22/tcp
OpenSSH 6.7p1 is vulnerable
High (3)
 
12321/tcp
server is susceptible to POODLE attack over TLS
High (3)

**Comment by JedMeister** [comment]
Is this an old appliance or a v14.x one? If it's v14.x then has it been restored from an old backup (i.e. migrated from an earlier version server)?

The reason why I ask is that I'm almost certain that stunnel as configured in v14.x is not susceptible to the POODLE vulnerability. By default we turned off SSLv3. See [here](https://github.com/turnkeylinux/common/blob/master/overlays/turnkey.d/stunnel/etc/stunnel/stunnel.conf#L43) 

Can you give more info about the test(s) and/or the vulnerabilities (particularly OpenSSH)? It'd be good to find out more so that we can confirm whether they are infact vulnerabilities we should be concerned about (and if so we need to fix them) or false positives. The OpenSSH package does have a few open vulnerabilities (see the [Debian security tracker](https://security-tracker.debian.org/tracker/source-package/openssh)) but they are all designated as 'minor'.

**Comment by l-arnold** [comment]
This is a new 14 with no Migration.  It is running on a Linode - blank disk to XEN, so perhaps something entered in that way.

Again, this is a Default Magento appliance and test on:  (Jessie) with no TKLBAM etc involved.
ran check on:
https://smartscan.controlscan.com/

**Comment by l-arnold** [comment]
Reading this again, some more details:
--------
22/tcp   OpenSSH 6.7p1 is vulnerable

Risk: High (3)
Port: 22/tcp
Protocol: tcp
Threat ID: shell_ssh_openssh

Details: OpenSSH keyboard-interactive authentication vulnerability
07/23/15
CVE 2015-5600
OpenSSH 6.9 and earlier are prone to a vulnerability,
which can be exploited by malicious users to bypass the maximum number of authentication 
attempts and launch brute force attacks. Note: The vulnerability exists 
on systems that have keyboard-interactive authentication enabled by default.
XSECURITY restrictions bypass vulnerability
07/09/15
CVE 2015-5352
OpenSSH before 6.9 is prone to a vulnerability,
which can be exploited by malicious users to bypass certain security restrictions.
The vulnerability exists due to OpenSSH not checking refusal deadline in
x11_open_helper function after ForwardX11Timeout expires.

Information From Target:
Service: ssh

-------------------

12321/tcp  server is susceptible to POODLE attack over TLS
(this could be WebMin Only, not the port)

THREAT REFERENCE

Summary: 
server is susceptible to POODLE attack over TLS

Risk: High (3)
Port: 12321/tcp
Protocol: tcp
Threat ID: misc_tls_poodletls

Details: SSL POODLE Attack
12/22/14
CVE 2014-8730
Only the SSLv3 protocol, and not the TLS protocol, is affected by this vulnerability. However, some TLS implementations, most notably in F5 and A10 devices, are known to be affected due to failure to enforce the protocol. 
Furthermore, even those clients and servers which correctly support TLS may still allow sessions to be downgraded to SSLv3 to allow compatibility with older peers. An attacker may be able to force this downgrade to occur by intercepting and modifying packets during the protocol negotiation phase, thus facilitating the POODLE attack.
10/15/14
CVE 2014-3566
The SSLv3 protocol, when used with CBC ciphers, is susceptible to an attack known as Padding Oracle On Downgraded Legacy Encryption (POODLE). The vulnerability arises because the padding is not deterministic and is not covered by the Message Authentication Code (MAC) and therefore cannot be verified during decryption. This may allow an invalid, specially crafted stream of ciphertext to have a one in 256 chance of being accepted. Each time such a stream is accepted, one byte of the plaintext data can be inferred.
An attacker who is able to intercept SSL sessions (as in a man-in-the-middle attack) can exploit this vulnerability using javascript code which forces a user's browser to send HTTPS requests to a server, and then modifying these requests such that the desired plaintext byte is aligned with the end of a block. If this is done repeatedly, the desired plaintext byte will eventually become known, and the attacker can move on to the next byte, and then the next, until the desired plaintext (for example, the user's session ID) is known in its entirety.

Information From Target:
Service: 12321:TCP
Sent:
TLSv1 request with invalid padding
Received:
HTTP/1.0 403 Access denied for 127.0.0.1

**Comment by JedMeister** [comment]
Thanks for the additional info @l-arnold.

I'll have a closer look at this ASAP. From a glance I'm fairly certain that at least some of these are false positives. Once I have checked and confirmed then we can report them as false positives. AFAIK most PCI testers have a facility to deal with false positives.

**Comment by JedMeister** [comment]
Ok I've had a closer look and here is what I can tell you so far:

##OpenSSH

**[CVE 2015-5600](https://security-tracker.debian.org/tracker/CVE-2015-5600)**
Technically vulnerable but default settings make it not possible to exploit (keyboard-interactive authentication disabled by default).

**[CVE 2015-5352](https://security-tracker.debian.org/tracker/CVE-2015-5352)**
Potentially vulnerable but irrelevant as we don't have X11 installed/running.

##Stunnel4 
stunnel4 provides SSL for both Webshel & Webmin; I.e. ports 122320 & 12321

TBH I'm surprised that the same issues didn't show for port 12320 as well. It has exactly the same stunnel config...

This may be a legitimate concern although I'm not 100% sure. Both the CVEs exist on the Debian system but neither note stunnel is affected. I'd need to do some more testing and/or reading... 

FWIW though I did check with [Qualys SSL Labs tester](https://www.ssllabs.com/ssltest/index.html) (it only checks port 443 so I used a Core instance and reconfigured stunnel to use port 443 for webmin instead of 12321) and it got pretty good results (score of 'T' or 'A' if the cert trust issues are ignored) after I told it to ignore the self signed cert and regenerated 2048 bit dhparams on my test server.

In the test results it explicitly states:
````
POODLE (TLS):	            No
Downgrade attack prevention:	Yes, TLS_FALLBACK_SCSV supported
````

**Comment by l-arnold** [comment]
Ok.  Let me see where I can get woth this.
Nack when I hear more.

**Comment by l-arnold** [comment]
Part of the issue is that stunnel runs on 12321 and it is difficult to set a different Cert.  My situation is that I have installed a XEN image.  My own Cert's work fine on the App but strangely the Turnkey Cert does not show on Webmin.  Rather there is a Cert from Linode.  I assume this is also related to the SSH subject.  

I will see what I can find from Linode on how their SSL is applied here.

**Comment by JedMeister** [comment]
Should be easy to set a cert for ports 12320 & 12321 (stunnel). Just edit the cert path in `/etc/stunnel/stunnel.conf` (default is the self-signed cert i.e. /etc/ssl/private/cert.pem).

TBH I'm not sure why it is showing a Linode cert for Webmin though, that's a bit weird IMO. Perhaps post your stunnel.conf:
````
cat /etc/stunnel/stunnel.conf
````

**Comment by l-arnold** [comment]
If I edit the Cert Path and I "misconfigure" it can I still access to fix?  Seems it would fail all means of Access at that point (at least how Apache doesn't like it with a bad "SSL" config).

I will look and test a bit here (maybe on something I can use a snapshot on)  (Turned off my VM sys so complicated)

**Comment by JedMeister** [comment]
I know you aren't a great fan of commandline, but my recommendation would be to use SSH (e.g. via Putty on Windows). SSH doesn't use SSL certs so, so long as you backup your config, worst case scenario you'll make Webmin & Webshell inaccessible for a few minutes (until you restore your config).

TurnKey has etckeeper installed which uses git to version control all the config (in /etc). So first thing is to double check that everything is committed and your /etc is clean.
````
cd /etc
git status
````
The last line should report something like 
> On branch master nothing to commit, working directory clean

Then check the path of your certificate. In PuTTY just selecting text with your mouse copies it. Then open the stunnel config in `nano` (simple commandline text editor).
````
nano /etc/stunnel/stunnel.conf
````
and adjust the cert path to be to your CA certificate. Ctrl x to save and exit. Then restart stunnel.
````
service stunnel4 restart
````
If there is no response then it has passed the first test (your config file is valid). You can now test Webshell & Webmin in your browser and see if the cert works as it should.

Instead, if you get something like
> Job for stunnel4.service failed. See 'systemctl status stunnel4.service' and 'journalctl -xn' for details.

Then something is wrong with your config file. The bet way to go is to restore your old conf file and try again. Because it's stored in git restoring the old file is super easy!
````
git checkout /etc/stunnel/stunnel.conf
service stunnel restart
````
And you should be back to where you started, ready to try again! :smile: 

Once you have it working and are happy with it, probably best to commit your changes:
````
git add /etc/stunnel/stunnel.conf
git commit -m "updated stunnel conf to work with CA cert"
````

**Comment by l-arnold** [comment]
I will give that a Spin sometime soon.

FYI I just got through my test (running a Magento tunnel through Joomla)..  so at least I can do business.  Its good to learn/note this stuff as we go.

Who knows why Joomla passed and Magento didn't but I think it indicates an issue with the Magento build somehow.

**Comment by JedMeister** [comment]
Perhaps, and it would definitely be worth checking out. 

However IMO it's more likely that it's a flaw in the testing process. Joomla has exactly the same setup WRT to Webmin and Webshell (and as I said, Webshell is actually running on exactly the same stunnel config as Webmin on both appliances and that didn't show in your original Magento test). Also Joomla should have the exact same version of OpenSSH as Magento (with those same security bugs as discussed above)...

**Comment by l-arnold** [comment]
yes,  still Joomla passed first try.  Magento failed 3 tries..My setups were the same as well.

Linode Cert is seemingly on webmin/12321 of Joomla as well so who knows what the difference is.

**Comment by l-arnold** [comment]
probably can close this for now (though would be worh testing PCI with Magento elsewhere as it would seem important).

**Comment by JedMeister** [comment]
Ok let's close this for now. Please feel free to reopen or start a new one when you get back to this.
