### ISSUE TITLE
ownCloud appliance readme needs updating

### ISSUE THREAD

**Issue by izzaboo** [turnkeylinux/tracker#590]
![root owncloud](https://cloud.githubusercontent.com/assets/1684036/13822712/5aedf1e0-eb6c-11e5-9e6f-b585cb493e7a.png)
Not sure if this is a bug, but it is at least a minor issue. ;-)

As they say, "no biggie."

I set up an instance of the ownCloud appliance via hub.turnkeylinux.com. (Amazon EC2)

The location of the ownCloud installation is not the same as reported on the webpage describing that appliance.

So I d/l appliance and it looks like same deal there. Website says owncloud installed in /var/www/owncloud but it isn't. Looks like it is in /usr/share/..... amongst other places.

find / -name "owncloud"

edit to add: p.s. I'm not a frequent user of github, yet. Not sure how to add tags to this "issue". Sorry.

**Comment by izzaboo** [comment]
the appliance I downloaded was running version 7.x of owncloud. I upgraded using repository and version 9.x installed in /var/www/owncloud.

huh. Wonder what I did wrong when I d/l from turnkeylinux site.

**Comment by JedMeister** [comment]
Thanks for the heads up. We need to update the readme as your first post is correct that the install location is different.

As of v14.0, ownCloud is in the Debian repos so we are installing that (rather than from upstream). There are pros and cons both ways, but we prefer installing from Debian as it will get auto security updates. When you install from upstream you have a newer version but you need to keep an eye out for security issues and do updates manually.

The upstream packages do not comply with the Debian packaging policy and that is why the install location is different. TBH it's a bit of a pain that they install to different places but that's how it is...

**Comment by izzaboo** [comment]
Thanks for your reply. For various reasons I ended up using a core TKL and installing ownCloud using their ppa. (are they called ppa in Debian?) I think the ownCloud folks did make some changes to their packaging (with v8? or v9?). Anyway...not difficult to get it working following their instructions.

All in all I'm pretty darn happy with how slick these turnkeylinux appliances are to set up!

**Comment by JedMeister** [comment]
No problem. Core is a fine base for pretty much anything Linux (server wise anyway) although in some circumstance the LAMP appliance might also be a good option (or the Nginx or Lighty appliances if you prefer). 

Glad to hear you like our appliances! Please feel free to pass on any further or specific feedback (good or bad). :smile: 

I'll rename this issue and leave it open (because we need to update the readme) but generally our [forums](https://www.turnkeylinux.org/forum/) are the best place to post (unless of course you're reporting a bug or making a specific feature request).

**Comment by JedMeister** [comment]
Ok, I've just updated the readme so I'm going to close this. Thanks again for the bug report! :smile: 

I've just changed the wording on the readme so it's no longer misleading. It's now not really helpful but at least is it correct!

So I can make the readme a little more helpful; as an ownCloud user, which sort of file locations would you want/need to know? And for what purpose? I understand that there are "apps" that you can install so I guess you'd need to know where to put them. And obviously you'd need to know where all your files are stored. I'm guessing that it probably keeps some database of files too?
