### ISSUE TITLE
missing generic script file for bootstrapping

### ISSUE THREAD

**Issue by heneault** [turnkeylinux/tracker#600]
When creating the bootstrap image, it seems the default script used by debootstrap is called "generic" but it is not available anywhere. According to git comments, it seems this is the only script that will use the env. variables that defines the base and required packages list.

Could you please add this script to the bootstrap project on github ?

**Comment by JedMeister** [comment]
I'll have to get back to you on that. Shouldn't be too big a deal. 

Out of interest are you cooking up something interesting?

**Comment by JedMeister** [comment]
I have uploaded the script and done a PR (https://github.com/turnkeylinux/bootstrap/pull/1) so that it can be included. But in the meantime you can grab it from my fork: https://github.com/JedMeister/bootstrap/tree/add-missing-file

I also added a line at the top of the readme just in case you didn't know where to put it...

**Comment by JedMeister** [comment]
Alon has suggested that rather than including it in the repo; that instead we should just add it to TKLDev. I'm in the process of doing that now which will close this issue.
