### ISSUE TITLE
Provide Gitlab upgrade instructions

### ISSUE THREAD

**Issue by Sajaki** [turnkeylinux/tracker#606]
hello, 

i'm using the Gitlab turnkey version 7.11.4 b725318 
`Linux gitlab 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64                      
Welcome to Gitlab, TurnKey GNU/Linux 14.0 / Debian 8.2 Jessie `

As Gitlab is now at 8.7.0, i would like to know if there is a recommended upgrade path ?

**Comment by JedMeister** [comment]
FWIW this question is probably not a great candidate for the way we try to use TurnKey GitHub Tracker "Issue"s and is normally the sort of thing that would be better discussed on the forums. Having said that it is an "issue" that needs some resolution (which would be useful for others too) so from that perspective is probably quite relevant here...

TBH I don't currently have a good and/or clear suggestion on upgrading GitLab. Our current [GitLab buildcode](https://github.com/turnkeylinux-apps/gitlab) is quite complex and over time we have deviated significantly to upstream (GitLab) recommended installation. Actually to be more correct; we haven't really updated the way we do things, whereas upstream (GitLab) have improved and streamlined their install process...

So to resolve this issue what we'd need to do is:
 1. start with a vanilla GitLab appliance and manually update it to the point where it works
 2. (with a tested working backup) test that same process on an existing server that includes data

We can do 1, although I'm not quite sure when we'll have a chance to get to it. But we'll still need you (or someone else who is using GitLab and has data there) to do 2.

Out of interest is there a specific reason why you want/need the newer version? Or is it just because there are features/bugfixes which you'd like?

**Comment by JedMeister** [comment]
Related to #511

**Comment by JedMeister** [comment]
Sorry about the delay on posting but we have (finally) published the update instructions: https://github.com/turnkeylinux/tracker/wiki/Upgrade-GitLab-in-v14.0-and-v14.1-appliances
