### ISSUE TITLE
Include fail2ban in appliances?

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#630]
As suggested by @timhibberd (most recently on our [forums](https://www.turnkeylinux.org/forum/general/20160425/turnkey-core-vulnerability#comment-25556))  it could be good to include [fail2ban](http://www.fail2ban.org/wiki/index.php/Main_Page) by default in appliances.

I have actually never used it so aren't really aware of the pros and cons but please discuss! :smile:

**Comment by vondrt4** [comment]
I would be for it. When building a single server for a customer, I put in a random password, Monit for CPU load, RAM, disk and the user-facing services, and fail2ban.

Securing SSH is as easy as installing the Debian package. Furthermore, there are pre-defined "jails" to monitor logins to other services. I have used e.g. Asterisk SIP registrations, HTTP basic authentication and FTP. These could be enabled by sed-ing a line in the jails.conf in the appliance builds. I imagine that e.g. Wordpress could put its admin section behind HTTP authentication and secure it agains bruteforcing by fail2ban.

The downside is that it manages iptables and can clash with other automatic firewall managers (not with people). Is it used somewhere in TKL? The alternative that does not is denyhosts, but that only works for services that read hosts.deny, that is those that use PAM - SSH, FTP, telnet..

**Comment by vondrt4** [comment]
I see (in core) `/turnkey/fab/common/conf/turnkey.d/webmin-fw` edits `/etc/iptables.up.rules`. It should work with that. When the fail2ban ademon starts, it adds rules to the top of the firewall tables redirecting to chains with attacking addresses.

**Comment by timhibberd** [comment]
I think that we should consider putting [ipset ](http://ipset.netfilter.org/) in front of iptables for better performance.

This can also be [tied to fail2ban](http://lawsonry.com/2015/01/automatically-block-banned-ips-with-fail2ban-iptables-and-ipset/) to create an efficient bruteforce protector with a lean blacklist behind it.

I considered but rejected trying to use ipset / iptables as a comprehensive ip blacklist due to the large number of blacklisted ip addresses ([over 1million](http://www.squidblacklist.org/faq.html)). As long as the application tier login is protected properly hackers can poke away as far as I'm concerned as long as the poking does not suck up all the RAM / CPU. So a fail2ban / ipset / iptables combo seems to provide a reasonable gatekeeper for network traffic into the VM.

**Comment by prassaschr** [comment]
One vote for fail2ban.
I use it for many years successfully and I thing it is a must!

**Comment by JedMeister** [comment]
I'll add this to the v14.2 milestone. That's no a guarantee it'll make it in, but it is a possibility...

**Comment by JedMeister** [comment]
Sorry this is getting bumped again :cry: v15.0?! :smile:

**Comment by JedMeister** [comment]
Another user has requested this via support.

**Comment by JedMeister** [comment]
A minimal implementation of fail2ban will be included in v15.0. Initially it will only provide cover for SSH, with a plan to extend that coverage for v15.1.

I'll close this issue for now and open a new one for v15.1.
