### ISSUE TITLE
Web shell and webmin use obsolete cipher suites

### ISSUE THREAD

**Issue by gordon-morehouse** [turnkeylinux/tracker#631]
When I point Chromium 49 at shellinabox or webmin, Chromium 49 describes the cipher suites as obsolete.

https://cipherli.st/ has a good reference for modern ciphers, although the list will probably need adaptation for the shellinabox and webmin HTTP servers.

**Comment by JedMeister** [comment]
I think that is because you are no longer using stunnel at the front end? See https://github.com/turnkeylinux/tracker/issues/382#issuecomment-217773825 for context. Is that the case?

FYI the default stunnel conf is here:
https://github.com/turnkeylinux/common/blob/master/overlays/turnkey.d/stunnel/etc/stunnel/stunnel.conf
The ciphers we use are configured here:
https://github.com/turnkeylinux/common/blob/master/conf/turnkey.d/zz-ssl-ciphers

**Comment by gordon-morehouse** [comment]
I was using 13.0 instead of 14.1, so this ticket is probably invalid. I assumed my provider was up to date but that wasn't the case.
