### ISSUE TITLE
Redmine git sample repository broken

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#636]
The syntax is for some reason /srv/repos/git/helloworld/.git, not /srv/repos/git/helloworld.git
Also, in the documentation, the correct way to use a git repository is IMHO
`git clone root@addr:/srv/repos/git/helloworld`, not `git://addr/git`

**Comment by JedMeister** [comment]
Thanks for this bug report. I confirmed that the git repo is not working... I'm not quite sure what happened there...

**Comment by kthkaya** [comment]
This bug has reoccurred in the latest version as of today

**Comment by JedMeister** [comment]
Hi @kthkaya - the appliance hasn't yet been rebuilt so it still includes this bug. Because we're a small team and our overhead to rebuild and re-release images, we generally only do appliance re-releases if it has a major bug that makes the appliance unusable. 

I have just amended the tracker readme to include additional info and explanation. I haven't yet merged it, but you can read it on my fork [here](https://github.com/JedMeister/tracker/blob/95ec443ac048f0785ac144f5d8050446476617f0/README.rst). Hopefully that makes it clear how it all works. If you can improve it or something still doesn't make sense, please let me know.

Regardless, thanks for taking the time to post.
