### ISSUE TITLE
why php-cgi instead of php-fpm

### ISSUE THREAD

**Issue by bash99** [turnkeylinux/tracker#659]
php-fpm is good than php-cgi in every place.

When I need tune the fastcgi socket backlog for burst income connections, only php-fpm provide this options.

**Comment by JedMeister** [comment]
Hi @bash99 is this a feature request or a general question? If it's more of a general question then our [forums](https://www.turnkeylinux.org/forum) are a better place for that in the future.

Also it would be handy to know which appliance in particular you are referring to. I assume that you are referring to one of our LAMP based appliances (because all of our Lighttpd and Nginx based servers use php-fpm).

And finally, we always appreciate feedback and do our best to accommodate as much as possible. But as there are essentially unlimited options for server configuration and we can't be everything to everyone. Our defaults are rarely fine tuned for performance. They are optimised primarily for a combination of security and user friendliness, with being "lightweight" the third consideration. They are intended to be useful as they come for newbs, but only as a better starting point for others that are more experienced.

**Comment by JedMeister** [comment]
@bash99 as you haven't responded with clarification I am closing this issue for now. If you want to reopen it, that's fine although please add the additional information/clarification as I requested above.
