### ISSUE TITLE
Ftp login issue

### ISSUE THREAD

**Issue by seekergeeker** [turnkeylinux/tracker#660]
I notice the webmin doesn't have ftp server on it so I'd have to use sftp via ssh to login pretty much but wordpress won't let me login on there script which this is = fail need ftp server within the install seriously common sense.

**Comment by JedMeister** [comment]
FTP is an insecure protocol and shouldn't be used in our opinion. So we don't provide it in any of our appliances (even our fileserver). AFAIK the only reason why WordPress still supports it is for users who wish to install WordPress on shared hosting (who don't have other options because they don't have direct filesystem access any other way). 

My suspicion is that the error message is a red herring and it's actually a permissions issue. If you have been uploading files via SFTP then those files will be owned by root. WordPress can't do anything with them because it doesn't have the correct permissions (WordPress runs under the webserver account `www-data`). And/or there is some misconfiguration in your WordPress install?

Generally these sort of issues are best discussed on our [support forums](https://www.turnkeylinux.org/forum). Please consider opening a new thread over there are if you could elaborate on your set up (e.g. what version of TurnKey WordPress, what customisations you've done since initial install etc) we could try to help you troubleshoot what your actual issue is?

If I'm wrong and you have a plugin or theme that explicitly requires plain FTP access then you have 2 options:
 1. (Preferred IMO) Contact the developers and ask them if/when they plan to support SFTP or other alternate (and secure) ways of connecting to the server. If they don't, then that's pretty poor IMO and I would consider using an alternate plugin (or paying someone to develop one if one doesn't exist).
 2. Install a vanilla FTP server. E..g to install ProFTPd and it's Webmin module: `apt-get update && apt-get install proftpd-basic webmin-proftpd`
