### ISSUE TITLE
New appliance - NextCloud

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#663]
Hi!
We wanted to test the new ownCloud fork and I was tasked to create an image. So with a TKLDev lying idle:
https://github.com/nextcloud/turnkeylinux-app
Please comment and consider for inclusion as an official app.

**Comment by JedMeister** [comment]
Awesome thanks. I had a quick look and from what I can see it looks great. II can't promise when we'll publish it; but as part of the v14.2 release at the very latest. I plan to make some time next week to give it a proper look over and do some testing early next week.

**Comment by OnGle** [comment]
I've updated the appliance to nextcloud 11.0.1 ready for next release. Now since nextcloud is a fork of owncloud and owncloud already has a turnkey appliance and github doesn't support multiple projects forked from a common origin in a single user (and I assume the same goes for organisations), we cannot directly fork this repo. I've cloned the repo and pushed it's history (plus the update) to a new repo here https://github.com/OnGle/nextcloud.

**Comment by oparoz** [comment]
@OnGle  - The best thing to do is to just create PRs against the main repo, that way we all work on the same image and make it better. I've already created one to upgrade to 11.0.2.

@JedMeister - What's missing here to push this forward? It's been over 6 months since the ticket was created.

**Comment by JedMeister** [comment]
Hey @oparoz - apologies on the delayed response.

Whilst generally you're absolutely right, in this instance I suggested that @OnGle do it that way. I'll be bringing it into the turnkeylinux-apps org soon, but as it's a fork of our ownCloud appliance I won't be able to fork it here on GitHub. So it's easier for me if I just have to clone and push a single repo rather than do it twice (once from the original, and again with @OnGle's updates).

As to what is missing; it's still missing updated artwork (logo and screenshots in `.art`). Beyond that I'm what's blocking it's release. Currently I'm working on v14.2 Core... Once I have that done (really soon hopefully) then we'll be releasing new apps and updating the existing library. In the past we've done it in one big batch, but this time I anticipate that we'll be releasing them in smaller batches as they're ready to go... So the new apps like this one should be released soon after Core.

**Comment by JedMeister** [comment]
It's built and on the mirror. I just need to make the appliance page and do the blog post.

**Comment by oparoz** [comment]
Many thanks @JedMeister !

**Comment by JedMeister** [comment]
Finally got this published: https://www.turnkeylinux.org/nextcloud
