### ISSUE TITLE
Turnkey TWiki 14.1 has several perl issues breaking functionality

### ISSUE THREAD

**Issue by qubez** [turnkeylinux/tracker#668]
VMDK image tWiki 14.1

This bug happens with Debian Jessie and TWiki 6.0.1 in the VMDK image tWiki 14.1, which results in wiki pages instead serving an error to cookie session users:
http://develop.twiki.org/~twiki/cgi-bin/view/Bugs/Item7721

Additionally, this bug, /bin/configure can't run due to issues with perl > 4.0.3, (I had to replace the distro's CGI.pm with a 4.0.3 binary):
_CGI::param called in list context from package TWiki::Configure::UIs::PromptPASS line 50, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 436, <DATA> line 1._

twiki.org/cgi-bin/view/Support/SID-01980

It was hours of hunting solutions to these issues to get a fully-configured wiki working.

(twiki.org is down right now or I would add more info)

**Comment by JedMeister** [comment]
Thanks for the bug report and sharing your info.

So to summarize (what you wrote and what I read from the links you provided) it seems there are 2 bugs, both it seems introduced by Debian security updates:

1. a Debian sec-update broke Twiki (not sure whether it's a Twiki or Debian bug). 

2. an incompatibility between Twiki and current versions of Perl (seems to be Twiki bug)

But you've managed to work around both of those issues then? Did upgrading to Twiki 6.02 help at all, or didn't you try that? From what I can gather it should resolve 1, but can't be sure. 2. is obviously a lot newer.

Can you recall exactly what you did to workaround these issues? If we can post a clear workaround then we will keep the appliance. Otherwise I think I might pull it from the mirror for now. Do you have any thoughts/suggestions in that regard?
