### ISSUE TITLE
Let's encrypt instead of self-signed certificate

### ISSUE THREAD

**Issue by Darcidride** [turnkeylinux/tracker#671]
Hi,

At first, thank you for your work on this Gitlab image.

Then, please can you add a support for **Let's encrypt** instead of self-signed certificate ?

I think no need to explain what is Let's encrypt, for information the **certbot** is available for **Debian 8 + Nginx** :
[](https://certbot.eff.org/#debianjessie-nginx)
![](http://i.imgur.com/CvExCYf.png)

**Comment by JedMeister** [comment]
Hi, thanks for taking the time to lodge your feature request. FWIW we are working on something like this for v14.2 but intend to provide it as a separate install for current TKL v14.0/v14.1 users.

See the other issues regarding this: #382 & #546 Also a user has detailed a pretty straight forward way to use LE here: https://github.com/turnkeylinux/tracker/issues/382#issuecomment-217766799 Note that that was documented specifically for the OpenVPN appliance (which uses lighttpd rather than nginx - but the theory remains essentially the same).

**Comment by JedMeister** [comment]
Oops forgot to close this. We now have [dehydrated integrated into confconsole](https://www.turnkeylinux.org/blog/v14.2-core-release).
