### ISSUE TITLE
[torrentserver] Crashes all the time

### ISSUE THREAD

**Issue by Tackyou** [turnkeylinux/tracker#680]
**Conslusion:** rTorrent appears to broken and/or unstable and will need some deeper review for v14.2, and/or we should consider using something else (e.g. Transmission as suggested by @Tackyou) - @jedmeister

----
Hi,

rTorrent always crashes for me and ruTorrent WebUi can't connect anymore with following error:

"No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file."

If I do:
service rtorrent stop
rm -rf /var/run/rtorrent
service rtorrent start

In terminal it works again.

If I don't delete /var/run/rtorrent it doesn't work. Neither service restart nor a full server reboot. I need to delete the file manually first before starting.

About 30 minutes later, same error. 

I'm using **debian-8-turnkey-torrentserver_14.1-1_amd64.tar.gz** in an LXC container on Proxmox. All other LXC and VM on the server have no issues. The LXC container for the TurnKey Torrentserver has enough resources. 1.7 TB free HDD. 16 GB RAM (14 allocated to rTorrent). 4 vCores. 

Only running about 10 torrents.

I made no modifications at all, so I really wonder why I'm the only _?_ one having this issue.

Any suggestions on how to debug & fix this issue?

**Comment by JedMeister** [comment]
TBH I'm not sure and haven't experienced that myself. Having said that I'm not a regular user of it (only for testing purposes).

FWIW in the torrentserver appliance; [rtorrent is installed from the Debian repos](https://github.com/turnkeylinux-apps/torrentserver/blob/master/plan/main#L12) so it is [v0.9.2](https://packages.debian.org/jessie/rtorrent) (v14.x is based on Debina Jessie). The TurnKey appliance [starts rtorrent within a tmux session](https://github.com/turnkeylinux-apps/torrentserver/blob/master/overlay/etc/init.d/rtorrent) (FWIW tmux is somewhat like screen, but better).

So to start with, have a look at the rtorrent logs (should be in `/var/log` somewhere). They may give you a clearer idea of what is actually going on.

Also be aware that Proxmox allows over allocation of LXC resources, so just because you allocate 14GB RAM doesn't mean your container can actually access 14GB RAM (it may run out of RAM if other VMs/containers are already using it). Conversely AFAIK HDD space cannot be overallocated, so you need to check the space that the container has access to, not the free space on the PVE host.

Also from my googling it appears that rtorrent is quite sensitive to HDD issues (e.g. [here](https://github.com/rakshasa/rtorrent/issues/39#issuecomment-107608923)). So it may be worth double checking the health of your physical harddrive. Because of the way HDD space is allocated, it is quite possible for a single VM/container to consistently have hardware related HDD issues while other VMs/containers and the host system itself run fine (AFAIK that does not apply to SSDs due to the way wear balance). 

It's probably also worth doing some RAM checks on the PVE host. I have experienced weird issues with a specific VM on a PVE host that had a bad stick of RAM. PVE ran flawlessly for years (literally) but this one particular VM was consistently unstable (others running Windows and Linux ran flawlessly). I didn't work out what the issue was until I upgraded the hardware and repurposed the old hardware. On the original hardware Windows consistently BSODed during install and hardware tests revealed the bad stick of RAM! I assume that something similar may also be possible for containers although I am not 100% sure.

It's also worth looking over the existing [Debian bug reports](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=rtorrent;dist=stable). I note that there are a number of bugs related to rtorrent crashing and you may find some useful info and/or workarounds that you can try.

From my general googling I found that many crashes which seem similar to yours (at least on face value) are often attributed to specific torrents and/or specific peers. So one path may be to disable individual torrents to see if that has any impact. I have also seen it recommended to delete the dht cache file (although TBH I'm not sure where that is found, perhaps somewhere in `/var/cache/`?)

Finally if you have any joy finding a resolution please post back. Alternatively if you get sick of searching you can always uninstall rtorrent/rutorrent and install something else (e.g. Transmission and Deluge both have headless options).

**Comment by Tackyou** [comment]
Hm, the only log file is /var/log/rtorrent/clamav.log which lists about 5 files it scanned. No errors. Not really useful at all.
I will reinstall a clean OS and use Transmission as it's really stable.

Thanks a lot for your effort and sorry for taking your time without finding a solution.

**Comment by JedMeister** [comment]
Ok. FWIW the Torrentserver is built on top of the [Fileserver](https://www.turnkeylinux.org/fileserver) so if you wanted the same functionality as the existing Torrentserver (except install Transmission yourself) then that might be a good option. Or if you don't want/need all the fileserver stuff, then [Core](https://www.turnkeylinux.org/core) might be better?

**Comment by JedMeister** [comment]
Looks like something might have broken with the appliance recently, we had a 2nd report of the rTorrent broken on the Torrentserver after security updates.

**Comment by Tackyou** [comment]
That could be the problem. I always accepted to install the security updates, never tried without.

**Comment by JedMeister** [comment]
I'm not sure. Regardless, it's broken because the security updates will install anyway (at night if you don't install them on firstboot). You can disable them, but that's not an acceptable solution IMO.

**Comment by JedMeister** [comment]
For v14.2 we will use Transmission instead. rTorrent is cool in theory, but appears to be a little unstable.

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux-apps/torrentserver/issues/9

**Comment by cpugenesis** [comment]
In setup it started to work then started to see this issue:

 "Torrent list not yet available, connection to rTorrent not established."

For me, even when I ran rtorrent itself, I could see the rtorrent console but still saw the above error in rutorrent.



The below has got it up and running for me, allthough need to do some extensive testing now:


* Edit rutorrent config
 nano /var/www/rutorrent/config/config.php
**SET scgi config TO 
 $scgi_port = 5000;
 $scgi_host = "127.0.0.1";

*Edit rtorrent config
 nano /var/lib/rtorrent.rc

**Remove SCGI_LOCAL
 scgi_local       = /var/run/rtorrent/rpc.socket
**Add SCGI_PORT
 scgi_port = 127.0.0.1:5000

** NOT NEEDED - Later changed back to 0.0.0.0 and worked fine
** CHANGE bind
 bind 127.0.0.1

**Add new line for max file size
***Fixed an error I had with download not starting below.
 set_max_file_size = 300G




When launched via etc.d it does some stuff with the rpc.socket file we no longer use
 chmod: cannot access '/var/run/rtorrent/rpc.socket': No such file or directory
 chown: cannot access '/var/run/rtorrent/rpc.socket': No such file or directory
just commented these out in the /etc/init.d/rtorrent file
nano /etc/init.d/rtorrent
         #chmod ug=rw,o= $SOCKET
         #chown rtorrent:www-data $SOCKET

Sync'd daemon up
 systemctl daemon-reload

Re-Set permissions on rtorrent folder
chown -R  rtorrent:rtorrent /var/lib/rtorrent/
chmod -R 777 /var/lib/rtorrent/

Also noticed rtorrents download folder was set to permission for root, so changed that too

 chown -R rtorrent:rtorrent /srv/storage
 chmod -R 777 /srv/storage


When I run service rtorrent start I see the below error still, however, rutorrent works and connects successfully.
 Warning: Unit file of rtorrent.service changed on disk, 'systemctl daemon-reload' recommended.







### OTHER ERRORS ###

* Download not starting

  >file_list: Failed to prepar
 XMLRPC Error: Found a file exceeding max file size

Add max file size to rtorrent.
   nano /var/lib/rtorrent/.rtorrent.rc
   add below line
 set_max_file_size = 300G



* ERROR Could not lock session directory
rtorrent: Could not lock session directory: "/var/lib/rtorrent/.session/", Permission denied

This was despite ls -o showwing drwx and rtorrent owner, but cown / chmod above fixe dit.

**FIX - Re Set permissions with chown / chmod as above 

#### DEBUGGING ###


* Run rtorrent application as user rtorrent, with interactive output in shell
 su - rtorrent -s /bin/bash -c "rtorrent"



* Run rtorrent as root

 cp /var/lib/rtorrent/.rtorrent.rc ~/

 rtorrent



* Check permissions on rtorrent folder

      su - rtorrent -s /bin/bash -c "rtorrent"
