### ISSUE TITLE
Update supported AWS instance types 

### ISSUE THREAD

**Issue by aijanai** [turnkeylinux/tracker#687]
Hi guys,

I've just started using your OpenVPN appliance and it's really handy.

The only thing, the instance types available (t1, m1, m3) are really outdated and I fear that your appliance may become undeployable in the near future due to this.

Could you please release a version compatible at least with t2 and m4, please?

Many thanks

**Comment by JedMeister** [comment]
Hey @aijanai, Thanks for taking the time to post and glad to hear that you find our OpenVPN appliance useful. :smile: 

As you note, the current MarketPlace images are really old. We have much newer instances that you can [download](https://www.turnkeylinux.org/openvpn) (for self hosting) or launch on AWS via the "[TurnKey Hub](https://hub.turnkeylinux.org/amazon/launch/openvpn/)". If you want to run only t2.micro then they are free (plus AWS usage fees), larger sizes require a monthly subscription (paid plans start at $20/mth).

The newer HVM instances (which provide t2 etc) are coming soon to AWS MP but we will be introducing charges for them (to help us fund development of cool new stuff).Because of the changes and the way that we wanted them implemented, it has taken us tons longer than we anticipated or hoped (nearly a year!) But it appears that the hard work has finally paid off and we have negotiated a mutually acceptable arrangement with AWS.

I'm not sure when the new images will be available (it's in the hands of AWS now) but we are hoping really soon. As a current subscriber you will get 3 months free (when charges kick in) but unfortunately the updated image for your current subscription will still still be PV images (so only support the old instance sizes). We had hoped to provide the new HVM AMIs to existing PV users but AWS were unwilling (unable?) to do that. That means to launch the newer instance sizes you'll need to subscribe to the new HVM products (once they go live).

AFAIK the charges will be $0.01/hr (for all sizes) so about $7/mth (for an always on server).

As this issue is essentially resolved, I hope you don't mind but I'll close this.
