### ISSUE TITLE
Nginx PHP FastCGI Server - Can't disable SSL

### ISSUE THREAD

**Issue by Modhappy** [turnkeylinux/tracker#712]
Imported virtual machine, and in the webmin configuration, SSL shows that its off with the radio button when its clearly on and working. If you try and toggle it on,  on it disables webmin and you cant get back in.

**Comment by JedMeister** [comment]
Thanks for posting. This is a known "issue" (it's sort of a feature...). 

The reason is because we have hidden Webmin behind stunnel (along with Webshell). So Webmin is configured to allow non-SSL connections but only from localhost. Stunnel is configured to allow SSL connections to the outside (on port 12321) and then passes them to Webmin (via the non-SSL connection on localhost).

Allowing non-SSL traffic direct to Webmin is **HIGHLY** discouraged. Doing that will mean that all traffic between your browser and Webmin will occur in the clear, including your root user account credentials. Anyone connected the network your appliance is running on could harvest your root credentials and other sensitive information. Even if you are running this on a LAN, any guests connected to the same subnet could gain this information fairly easily if they were inclined. FWIW It's only a couple of extra clicks to get past the self-signed cert in Chrome and you can add a permanent exception for the self-signed cert in Firefox. Getting a "proper" (CA signed) cert is also possible for free via Let's Encrypt.

If you want to allow non-SSL traffic to Webmin despite my advice, then you will need to remove the Webmin related entry in the stunnel config (`/etc/stunnel/stunnel.conf`) and adjust Webmin so it allows connections from anywhere (change `bind=127.0.0.1` to `bind=0.0.0.0` in `/etc/webmin/miniserv.conf`). If you want to continue to use port 12321 you'll need to add that to the Webmin config too (it defaults to 10000). Both services will need restart for the new setting to apply:

````
service webmin restart
service stunnel4 restart
````

**Comment by JedMeister** [comment]
PS I've just adjusted your title, although I just relised that perhaps you were trying to disable SSL for nginx itself? If so you'll need to do that yourself in the nginx config (in the relevant file(s) in `/etc/nginx`). There isn't an nginx Webmin module.
