### ISSUE TITLE
New Appliance: Invoice Ninja

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#715]
Current Status (Researching)

Will be picking backup the build maybe by 12/1/2016, currently researching.

[My TKLDev Github Repo](https://github.com/DocCyblade/tkl-invoice-ninja)

[Invoice Ninja Site](http://www.invoiceninja.org)

[Debian and Nginx Install Guide](https://www.rosehosting.com/blog/install-invoice-ninja-on-a-debian-7-vps/)

[User Guide](http://docs.invoiceninja.com/en/latest/)

**Comment by DocCyblade** [comment]
Picking this one back up for hopefully v15 :-)

**Comment by JedMeister** [comment]
In an effort to finalise v15.0, I'm moving this to v15.1. If it gets done prior to v15.1, we can always move it back (and release as a late addition to v15.0).

**Comment by bormanst** [comment]
Although I use a different build framework, most of the info below should prove to be useful if not outright copy/paste:

Invoice Ninja:
[Latest install info](https://invoice-ninja.readthedocs.io/en/latest/install.html)
[Used combo of Manual install and suggested Ubuntu and Apache install](https://websiteforstudents.com/install-invoiceninja-on-ubuntu-16-04-18-04-with-apache2-mariadb-and-php-7-2/)

FormaVid:
[Apache php.ini updates](https://github.com/bormanst/formavid/blob/master/lamp/php/php)
[All apt-gets]( https://github.com/bormanst/formavid/blob/master/applications/invoiceninja/all-apt-gets)
[Build script](https://github.com/bormanst/formavid/blob/master/applications/invoiceninja/invoiceninja)
[Initialize script](https://github.com/bormanst/formavid/blob/master/bin/initialize/python/invoiceninja.py) 

Notes:
1. The zip method was preferred over the composer method as *rattling* github caused the *api rate limit exceeded* issue and required an Oauth token; while maybe not an issue for a creating a pre-built appliance like your offerings, it's not well suited for *user* install scripts such as what FormaVid provides.
2. The install completes short of your *normal completion* by letting the user confirm/complete the final setup using the app provided */setup* page instead. I stopped there since the user may want to customize some of those settings, there are *accept condition* choices, and the submitted setup process is relatively quick. For convenience, most of the settings are *auto-populated* by the build script in the *initialize app env file* section.
3. The */setup* page is protected by an Apache dbm password (created by the python script) as indicated in the *Location* directive of the apache.conf near the bottom of the build script; this was done for obvious security reasons. Once setup has been completed, access to the app is controlled by the app and not Apache (even though the setup *location* remains *blocked* by Apache it cannot be *re-executed* anyway.)
4. The APP_KEY and PHANTOMJS_SECRET in the .env file are randomly generated in the build script and everything *appears* to work fine but I have not *test driven* the app enough to know if there may be an issue with using those *random* keys. Best to make sure before you slap your name on it ;)
5. In the build script, replacing of mod_php5 with mod_php7 in all .htaccess files is just a security precaution I put in my scripts and not indicative of the provided app code; it is moot in this case.

Hope this saves someone time :)

**Comment by JedMeister** [comment]
Thanks @bormanst ! I'm not sure when we'll get to this one, but I'm sure your notes will be invaluable when we do. Thanks tons! :smile:

**Comment by JedMeister** [comment]
Closing this as we now have an [Invoice Ninja appliance](https://www.turnkeylinux.org/invoice-ninja).
