### ISSUE TITLE
Can't access the instance after attaching external volume

### ISSUE THREAD

**Issue by ankitjain6** [turnkeylinux/tracker#718]
1. We have Setup the new instance in our AWS account called "LAMP Stack - Web Stack (MySQL) powered by Turn Key GNU/Linux" 
2. Login to instance successfully
3. Then Attached the new Volume 
5. Formatted the volume with Linux type file system (mkfs.ext4 disk name) 
6. And then mounted the drive 
7. Rebooted to the server or instance. 
8. And we lost the access of instance.
We have contacted to Amazon team and they said issue seems at OS level.
We tried to setup the instance many times and every time we face the same issue, after attaching any new volume to the instance and then reboot the server and we lost the access until we remove the volume.
Your suggestions are highly appreciated.

**Comment by JedMeister** [comment]
Could you please tell me what sized instance and what region? Also whether it's 32 or 64 bit and whether it's the HVM one?

Thanks.

**Comment by ankitjain6** [comment]
![screenshot_176](https://cloud.githubusercontent.com/assets/7967929/19691302/64e3944a-9af1-11e6-97ed-6f472502b90f.png)
The instance details attached with the screen shot.
Instance type:   M1.medium
Region:  US-East-1d
Processor: 64 Bit
Volume size: 300GB
And it's not the HVM.
I have tried to Launch the instance with another size also like m1.large and m3 but same issue in all.

**Comment by JedMeister** [comment]
Do you need PV? If not, I recommend you try the the HVM build: https://aws.amazon.com/marketplace/pp/B01KVGYKF8?qid=1477345840677 

I haven't explicitly checked that, but the error you are reporting certainly seems similar to an issue we've had with PV servers not booting from the right volume. That's why we don't offer the m1.small anymore. It's a bug on Amazon's end which they won't fix as they consider PV legacy.

Also out of interest, I also have an open support request regarding this same issue. Is that you? Or someone else with the same issue?

**Comment by ankitjain6** [comment]
Hello Jeremy,

Thank you for the suggestion. I really appreciate.

Let me try to set up the HVM instance as you suggested.

Yes, I think this me, I am chatting with you with Victor's account.

**Comment by ankitjain6** [comment]
Hello Jeremy,
I have setup the instance with the suggested HVM turnkey by you.
And we are able to access the instance after attaching the volume and reboot.

Seems the issue has been resolved with this HVM turnkey LAMP instance (m3.medium)

Thank you for your suggestion. I really appreciate.

**Comment by JedMeister** [comment]
Great thanks for the update.
