### ISSUE TITLE
Support "out of band" appliance updates

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#754]
**[update]** I have had a lengthy discussion with Alon and Liraz. We have decided that the easiest way to implement the spirit of this feature without risk of breaking stuff (and this the least amount of work) is to just allow the appliance version to get out of sync. I.e. Core might be v14.2, but other appliances might be v14.3 or v14.4.

----

As noted elsewhere, currently TurnKey requires that all appliances be at the same version (i.e. currently all apps are v14.1). This means that if we wish to update or re-release an appliance we must either re-release it as the same version - which is dirty and makes it hard for users to know which version they have without querying the installed appliance. Or we need to do a new full release - which is very labour intensive.

Historically this means that appliances with "showstopper" bugs (i.e. when the appliance is totally broken) or upstream security issues get rebuilt (as same version) and appliances with other less critical bugs need to wait until our next release. It's how things have worked for many years now and it's ok, but it's certainly sub-optimal.

As part of v14.2 release, we'd like to support future sub-versioned appliances (e.g. `v14.2~1` - i.e. `v14.2 - update 1`). This will allow us to re-release updated individual appliances as need be. This will mean that we can update the third party software of popular appliances more regularly and also patch non-critical bugs between full library releases. It is anticipated that these changes will allow us to be more responsive to community input as well as consistently providing superior quality appliances.

It's not yet set in stone, but as hinted above, we are currently planning to will use `~` (tilde) as the sub-version/update separator. The initial full library release will use the existing version notation e.g. The next release of LAMP will be `turnkey-lamp-14.2-jessie-amd64`. I.e. if `~` isn't in the version string, then it assumed to be `~0`. Subsequent updates will include `~UPDATE_NUMBER` e.g. the first updated release will be `turnkey-lamp-14.2~1-jessie-amd64`.

Considerations:
- [ ] website
- [ ] initfence
- [ ] buildtasks
- [ ] Proxmox index (and index file build script)
  - index and buildcode already done, but needs minor tweak to finalise
- [ ] Hub
- [ ] TKLBAM
- [ ] LXC appliance 
  - PR which needs only minor tweak [here](https://github.com/turnkeylinux-apps/lxc/pull/9/files)
- [ ] ?????

**Comment by JedMeister** [comment]
As noted above in my update to the OP, we're looking at implementing the spirit of this in  slightly different way...

**Comment by DocCyblade** [comment]
@JedMeister - Per our conversation thought I would post it here so that it's documented. 

As you said that common would be a problem as it could be out of sync (updated with fixes for a single appliance or new appliance) that we would need a way to pin a version of the applicant with a commit hash from common. 

So I purpose that the build tools be able to handle see how either in a file with a commit hash or a tag name OR a variable in the make file whatever would make more sense. The idea would be that file/variable be able to be changed while development and the make tools would use that to checkout common at the commit hash or version tag and proceed with the build.

To make things easier for the public at large, I personally like version numbers. If common gets tagged with version numbers (don't have to be the 14.x but we could start at 14.2 and keep it in line with core or the tkldev) This would allow us to say that common follows core/tkldev in the major/minor version and any movement in apps that would alter common would increase the patch/hotfix 

Example: Time Line in common...

- Core/TKLDev: v14.2 (tagged at v14.2.0) 
   - Updates/fixes to other appliances once the app has been published bump v14.2.1
   - New appliance gets added, once published (right before so to tag it) v14.2.2
   - An appliance gets updated and common is updated (right before so to tag it) (v14.2.3)
   - An appliance gets updated and common is updated (right before so to tag it) (v14.2.4)
   - An appliance gets updated and common is updated (right before so to tag it) (v14.2.5)
- Core gets updated v14.3 - (Common gets tagged at v14.3.0)
   - Updates/fixes to other appliances once the app has been published bump v14.3.1
   - New appliance gets added, once published (right before so to tag it) v14.3.2
   - An appliance gets updated and common is updated (right before so to tag it) (v14.3.3)
   - An appliance gets updated and common is updated (right before so to tag it) (v14.3.4)
   - An appliance gets updated and common is updated (right before so to tag it) (v14.3.5)


So looking at the build code for say Odoo v14.4 may depend on a common v14.2.2 so the file or variable in the odor v14.4 build code would reference v14.2.2 instead of 751abef3337134ba122f648eea2f022a9a6304a1 

It would be a little more maintenance for tagging common only when an appliance is published or when core is updated

Just some thoughts

**Comment by JedMeister** [comment]
@DocCyblade  - thanks tons for that. That sounds like a really sensible way to go! I like it! :+1:

**Comment by JedMeister** [comment]
I'm closing this for now.
