### ISSUE TITLE
Confconsole leaves terminal dirty on crash

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#755]
since confconsole utilizes the dialog library (wrapper for dialog which uses ncurses). When confconsole crashes, is killed or interrupted it usually leaves the terminal in a state not suitable for commandline usage. 

As a workaround typing `stty sane` into the terminal should fix it.

**Comment by qrntz** [comment]
`reset` also works. I don't think we can do much with the underlying issue because it's just what dialog itself does on interrupt (at least in my experience).

Perhaps we can just use a simple wrapper around confconsole.py which would call it, check exit status and issue `reset`/`stty sane` if the status is non-zero. And if the TTY is in default mode it's basically a no-op so shouldn't hurt.

**Comment by OnGle** [comment]
Agreed.

We could wrap it 2 ways, externally with `confconsole || stty sane` (not reset to preserve traceback) or we could wrap confconsole's `main()` in a catch-all try-except, run `reset` and print the traceback.

The first way would be obviously  quicker and not very messy to implement. The second is a bit dirty but it allows preserving of tracebacks too long to fit in a single screen (probably not "that" important in confconsole).
