### ISSUE TITLE
Please, update package to Magento 2.1+ 

### ISSUE THREAD

**Issue by spyrule** [turnkeylinux/tracker#759]
a Package like this is badly required to allow for fast development for Magento 2.1+. Please consider upgrading/offering a new package that is Magento 2.1+ compatible (php 7, either nginx or apache)

**Comment by JedMeister** [comment]
Hi,

Apologies on my slow response. I am currently working on the v14.2 release so your request is timely...

FWIW Magento [2.0+ depends](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements-tech.html) on MySQL 5.6 and Jessie only has [5.5.54](https://packages.debian.org/jessie/mysql-server). However I do note that it says it's compatible with MariaDB. Jessie has MariaDB [10.0.29](https://packages.debian.org/jessie/mariadb-server). From my reading, that is compatible with MySQL 5.6 so that should be an acceptable workaround.

Actually, the build code has already been [updated to use MariaDB](https://github.com/turnkeylinux-apps/magento/blob/master/plan/main#L7) (). It also [includes Magento v2.1.0](https://github.com/turnkeylinux-apps/magento/tree/master/overlay/usr/local/src). Obviously we'll update that to use the latest current version when we actually release it.

WRT to PHP, Jessie has [PHP 5.6.29](https://packages.debian.org/jessie/php5). There is no Jessie PHP7 package (not even in backports) so providing that as default is not something we'd like to do. I note though, that PHP7 is only a recommendation for Magento 2.1.x, not a hard dependency.

So will that work for you? Or do you require/strongly desire PHP7? If so I wonder if we could work around that by simply providing a helper script to allow you to install PHP7 from a third party (such as dotdeb or similar)? Any thoughts or feedback?

Why it hasn't yet been released when the build code was updated nearly 4 months ago is a long story. Why that is and what we plan to do to resolve it (or at least reduce it) is something I plan to discuss in a blog post. Although as per usual, due to our labour bottleneck, it's something that keeps getting pushed aside in favour of more important stuff. In the meantime I hope you can accept our apologies on how slow we move sometimes...

**Comment by spyrule** [comment]
php 5.6.29 is fine, however most major M2 deployments are quickly moving to php7 for the speed performance (something like ~30% increase!)  I'm more curious why turnkey hasn't made a major upgrade for all "primary" services (php7, mysql 5.6+) ?

**Comment by JedMeister** [comment]
It's because we're based on Debian and leverage all the great work they do (standing on the shoulders of giants and all that...). They (and us too) value stability and security over performance. That why TurnKey is based on Debian stable. 

To provide rock solid stability, Debian freeze the software versions in the lead up to stable release. To provide post-release security, they have a team who backport security patches to the (frozen) version included in the OS. It is not uncommon for Debian Security Team to release backported security patches before upstream even publicly acknowledge there is a security bug!

The upside of that is that a server you installed a year ago will have the exact same software API as it did the day you installed it (so long as none of your functionality relies on security bugs that have since been patched).

It also means that we can configure our servers out of the box to install security updates and the risk of it breaking something is REALLY low! AFAIK there have been 2 or perhaps 3 things TurnKey servers include which were broken by security updates within the last ~10 years! You'd have to agree, that's a much better track record than most! (cough cough Microsoft) :smile: 

From my experience and a lot of the feedback we receive, what we provide is what most Sys Admins want. The less they need to update things, the less things break, the cheaper/easier maintenance is...

Obviously the downside is that you don't have the latest versions. As you well know, new versions often include new features and sometimes provide performance improvements (although not always). But they can also introduce new bugs and issues and may change the API. That means that generally they also carry a vastly increased maintenance overhead. 

In my experience, that sort of trade off appeals much more to Devs than it does to Sys Admins. That is especially the case with Devs who primarily use Windows. For fear of sounding like a Linux fanboy (which I pretty much am - since I switched ~4yr ago), IMO Windows users already accept a crazy level of maintenance overhead without question and often don't realise that there is (IMO) a better way.

FWIW the next stable release of Debian (ETA later this year) will include [PHP7.0](https://packages.debian.org/stretch/php) & it appears that they will [drop MySQL altogether in favour of MariaDB 10.1](https://packages.debian.org/stretch/default-mysql-server). That may well change between now and release though...

**Comment by spyrule** [comment]
Thanks for the update, supposedly Magento 2 is working on official support for MariaDB (but is reported to be completely compatible with MariaDB with no intervention... just not "officially"), but until that happens I'm not worried. 

Keep up the awesome work you do!

**Comment by JedMeister** [comment]
Yeah I have read a post by one of the Magento devs on the Magento site (perhaps in the forums?) that the only reason why Magento don't "officially" support MariaDB is because they don't want to spend the resources to exhaustively test it. 

All reports that I have read say that Magento works flawlessly with MariaDB. And that isn't a great surprise as MariaDB devs appear to be really committed to providing a "drop in" MySQL replacement (albeit with what they deem to be performance and stability improvements). I also note that I have seen explicit mention of MariaDB in the newer Magento documentation (despite not "officially" supporting it).

**Comment by JedMeister** [comment]
Sorry on the delays and radio silence. We've been flat out behind the scenes. FWIW, this is in progress and we hope to release within the coming weeks. I've done the basics and it builds ok, but I've handed to my colleague Anton to finalise. https://github.com/turnkeylinux-apps/magento/pull/15
