### ISSUE TITLE
Amazon ec2 Magento TurnkeyLinux instance

### ISSUE THREAD

**Issue by nabilashraf** [turnkeylinux/tracker#760]
Hi,

I have an issue with my instance. I have added the CNAME record and A record for Elastic IP of my amazon ec2 instance to the custom domain I purchased from godaddy. 

The dns settings are being configured in cloudflare. 

Now I installed the let's encrypt certificate for my domain and when I browse it manually, it says it is secure.

The problem I have  is that when I reach out to my admin backend url or any url , it says insecure connection as well as show the amazon public dns rather than my custom domain.

Please Help!

**Comment by JedMeister** [comment]
Hi,

Firstly apologies on the delayed response. Secondly, this is our "issue tracker" and is intended for tracking bugs and feature requests. For support, our [forums](https://www.turnkeylinux.org/forum) are the preferred medium.

But seeing as you're here already, I suspect that what you are experiencing is because when you did the initialization, you used your AWS DNS name (rather than your custom domain). That can easily be resolved, by re-running the Magento inithook. You can do that like this:

````
/usr/lib/inithooks/bin/magento.py
````

Note you will need to also re-enter your password (you can change it if you want, or re-use the one which you have set already). You will also need to re-enter your email, however IIRC it will suggest the email which you have already used.

Also, if you want you can do it non-interactively by using switches, e.g.:

````
/usr/lib/inithooks/bin/magento.py --pass=mypassword --email=me@email.com --domain=my.custom.domain
````

Note that if your password has spaces, you'll need to quite it. Alternatively the space can be escaped. Many other special characters will need escaping too. I.e. precede the special character with `\`, e.g. `Pa\$\$\ w0rd` is `Pa$$ w0rd` with the special characters escaped.
