### ISSUE TITLE
OpenVPN: Revoking client certificates fails

### ISSUE THREAD

**Issue by ainkinen** [turnkeylinux/tracker#801]
Revoking client certificates fails while using the instructed commands. The instructions are online (https://www.turnkeylinux.org/screenshots/openvpn-turnkey-quick-ref) and on the appliance web server default page.

Original instructions:
Revoke client certificate
`source /etc/openvpn/easy-rsa/vars`
`/etc/openvpn/easy-rsa/revoke-full client-name`

Reason:
While running with the normal admin user, the second command fails with a `permission denied` message, because the admin user doesn't have permissions to access the certificate files.

Fix:
The second command runs successfully if `sudo -E` is used for raised privileges while still keeping the loaded environment variables.
`sudo -E /etc/openvpn/easy-rsa/revoke-full client-name`

Issue and fix tested on:
AWS Marketplace OpenVPN AMI (HVM)

**Comment by ainkinen** [comment]
Other commands in the instructions also need `sudo`, but this is especially unclear because just using `sudo /etc/openvpn/easy-rsa/revoke-full client-name` fails with another error, because the environment variables are not loaded.

**Comment by JedMeister** [comment]
Thanks again. You rock! :smile: 

Not sure how far away it will be but I hope to updating our release really soon.

FWIW the OpenVPN appliance buildcode can be found here: https://github.com/turnkeylinux-apps/openvpn

**Comment by ainkinen** [comment]
Thanks for the link. I'll look into making an actual pull request if I have the time.

**Comment by JedMeister** [comment]
Looking at this in the light of day, I think perhaps the best place to adjust things to resolve this issue is in the [docs](https://github.com/turnkeylinux-apps/openvpn/tree/master/docs). 

I say that because only the Amazon Marketplace instances have `root` disabled and use `admin`. None of our other instance types even have `sudo` installed. FWIW we use a tool called [turnkey-sudoadmin](https://github.com/turnkeylinux/inithooks/blob/master/turnkey-sudoadmin) to enable/disable the sudo `admin` user so AWS Marketplace users can disable the admin account and re-enable `root`. 

We provide that on AWS Marketplace instances to meet Amazon's (in our opinion misplaced) "security" concerns about root logins. We use `admin` (rather than the suggested default of `ec2-user`) so at least make sure this piece of "security by obscurity" is actually somewhat obscure! (The idea of switching one default for another seems a bit pointless if you ask me).

TBH I'm not 100% sure of the best way of implementing this. My first thought is to just put a note within the docs about the need for `sudo` (or disable sudoadmin) when running from AWS Marketplace. And that would probably work. Although we'll need to make sure it's pretty visible. I know myself, that I often use a combo of google and my browser's "in page" search to find what I'm looking for. In many cases, I'd possibly miss a notification like I'm suggesting.

If you have specific thoughts or preferences, I'd love to hear.

**Comment by JedMeister** [comment]
I was hoping to close this in v14.2, but I've just realised that the bug report is explicitly related to the index page contained within the appliance. But we've already published the v14.2 appliance :cry: 

It's fixed as of ihttps://github.com/turnkeylinux-apps/openvpn/pull/21 but unfortunately it won't be in the appliance until the next release (v15.0). I'll leave this open until we merge the code.
