### ISSUE TITLE
OpenVPN Initialisation fails OOB with 14.2 (Proxmox)

### ISSUE THREAD

**Issue by Xyon** [turnkeylinux/tracker#857]
While running up a clean version of this appliance (with hash 01fe55f285995fc6e762a6123de87c212dfd0e151e8d8b4614d64c4bd439afdb93f8018407ba53919ebd7c2bacab290d376d0d90aacbc3ec14b53d7bf5a03f09), turnkey-init fails to provision OpenVPN itself, silently continuing to the TLKBM setup screen without apparently suffering an issue - however the VPN itself remains unconfigured.

![tk-ovpn](https://user-images.githubusercontent.com/1128431/27078588-17d85db6-502c-11e7-9664-c48b670700fd.png)

Barely visible is the issue itself, which is captured in the screenshot - /etc/openvpn/server.ccd exists in the filesystem as a dangling symlink, and its existence causes a python exception. Removing this file, and manually invoking turnkey-init, successfully causes the appliance to function as it should.

![tk-ovpn-dangling](https://user-images.githubusercontent.com/1128431/27078593-22d24b14-502c-11e7-844f-2117ffcb28ab.png)

This symlink should be removed from the base template, as it's recreated by turnkey-init during setup.

**Comment by Xyon** [comment]
Sorry, turnkey-version:
turnkey-openvpn-14.2-jessie-amd64

**Comment by JedMeister** [comment]
Thanks heaps for the bug report. I'll have a look and rebuild ASAP.

**Comment by JedMeister** [comment]
I have confirmed the issue and am looking at how to resolve it... The line in the buildtime conf script that creates the symlink was to work around a bug that a user experienced. I took the bug report on face value and resolved it (in the buildcode) as per the bug report. 

However, I obviously should have done some more looking through the code and much more testing than I did...

So, my inclination is to remove the conf script line (as you suggest) and adjust the inithook script to recreate the symlink (rather than just create the directory). 

I think that the best way to would be to use the `/etc/openvpn/server.ccd` directory as the primary location, and `/etc/openvpn/easy-rsa/keys/crl.jail/etc/openvpn/server.ccd` should just be a symlink to that. Although I'm not completely sure whether that will work (due to the jailed users, file permissions, etc). 

If you're playing with this at the moment anyway, would you mind testing my thoughts and see if that will work?

**Comment by Xyon** [comment]
I'm game - I've got the appliance working, but spinning up a new container costs me nothing. I can poke about with what I have, or I can run up something else if you're rebuilding. I'll take a look when I get to work.

**Comment by JedMeister** [comment]
Awesome thanks! :smile: I'm hoping to have a chat with my colleague Alon about it really soon (i.e. today). And then I should have some more clarity on the best way to go.

FWIW the symlink will only work the way that it's currently in the build code. Making the dir within the chroot a symlink won't work (because it's a chroot). But a bind mount should achieve the same ends. 

I'll be in touch ASAP and hopefully I'll have a container for you to download and test. Roughly where abouts in the world are you? If I know that I can upload the container template to somewhere near you so it'll download quicker!

**Comment by JedMeister** [comment]
Hey @Xyon thanks again. We've decided that we're going to roll back to the v14.1 appliance for now. We'll work out a proper fix for the bug that I was trying to resolve and this time do a better job of testing it! That means that there isn't too much pressure to push it out the door.

The v14.2 OpenVPN appliance was only made public late last week and we haven't even officially announced it yet. Due to the fact that this bug was discovered so quickly (thanks to you!) and it's completely broken (at least for most people) we'll be removing the existing v14.2 OpenVPN appliance. In the coming weeks we'll replace it with a re-released (and fixed) v14.2 build. 

If you're still open to help testing the finished result (before we publish it) then that'd be awesome. I'm not sure when I'll have something ready for you to test, but hopefully soon. I'm happy to communicate via this thread if you want. If you'd rather though, please feel free to email me directly jeremy@turnkeylinux.org

**Comment by Xyon** [comment]
Cool - I'm glad I could help - I get email notifications on replies, so I'm happy to communicate here (openness is good!), and I can surely test when you have something. I'm in the UK, but I have reasonable internet (on clear days, when the wind is right), and my test box is in Hetzner (Germany). IIRC the container's less than half a gig, so it shouldn't be a major stretch to fetch it.

**Comment by JedMeister** [comment]
Awesome!

When we get there, I'll upload a container template to the bucket I have in Ireland already. So even if it's a bit cloudy you should be ok! :smile:

**Comment by JedMeister** [comment]
@Xyon - as posted previously, we're pretty sure we've solved the issue. Thanks again for reporting it! :smile: 

I have just uploaded a new v14.2 OpenVPN build in the LXC container/Proxmox format to an S3 bucket in Ireland. Here it is (and the hash file too):

https://s3-eu-west-1.amazonaws.com/tkl-test-builds-eu/debian-8-turnkey-openvpn_14.2-1_amd64.tar.gz
https://s3-eu-west-1.amazonaws.com/tkl-test-builds-eu/debian-8-turnkey-openvpn_14.2-1_amd64.tar.gz.hash

Please let me know how you go.

**Comment by Xyon** [comment]
Downloaded and tested the template you sent in the same test server, and the provisioning completes successfully; looks like the issue is indeed fixed! :+1:

**Comment by JedMeister** [comment]
Awesome, that's for the confirmation. Hopefully it will be live within the next few weeks. The ISO is actually on the mirror already, but I'll need to wait until my colleague Alon is back on board (he's away for a couple of weeks).

Thanks again. :smile:
