### ISSUE TITLE
Let’s Encrypt - ACME v2 API Endpoint

### ISSUE THREAD

**Issue by bormanst** [turnkeylinux/tracker#881]
Just an fyi as I'm guessing Core v15 will be available sometime early next year:

Let's Encrypt says ACME v2 API Endpoint Coming January 2018: https://letsencrypt.org/2017/06/14/acme-v2-api.html

They "are not setting an end-of-life date for the ACME v1 protocol" so it should not affect the current confconsole plugin for quite some time.

ACME v2 will supposedly allow wildcard certs to be issued according to: https://arstechnica.com/information-technology/2017/07/lets-encrypt-to-start-offering-free-wildcard-certificates-for-https/

Thanks.

**Comment by JedMeister** [comment]
Thanks for posting @bormanst  Great info!

**Comment by JedMeister** [comment]
I've assigned this to myself for now. I have recently been doing some work on the Confconsole Let's Encrypt plugin. Unfortunately, I've been pulled onto other stuff before I managed to finalise what I was working on, but I'll aim to have a read up on where things are up to with the v2 API endpoint.

**Comment by JedMeister** [comment]
The rollout of ACMEv2 has been (further) delayed (see the top post in this [thread](https://community.letsencrypt.org/t/acmev2-and-wildcard-launch-delay/53654)). There is no current ETA, although I note that they haven't revised their roadmap (ETA: Q1 2018 - so by the end of this month probably).

I have checked and can confirm that [`dehdrated`](https://github.com/lukas2511/dehydrated) (the tool we use to get the certificates) is primed to support ACMEv2. However, we currently install dehydrated from the Debian repositories. We could install it via an alternate method, but my inclination would be to stick with the Debian repos. The version in Stretch is [v0.3.1](https://packages.debian.org/stretch/dehydrated) which only supports ACMEv1, but it appears that someone is actively maintaining it, as [v0.5.0](https://packages.debian.org/stretch-backports/dehydrated) is in stretch-backports!

I'm tempted to update our Confconsole implementation to be compatible with ACMEv2 (and install the newer version of dehydrated from backports), however, it appears that the significant plus for the v2 implementation of ACME is the support for wildcard domains. Wildcard domains rely on [DNS challenges](https://community.letsencrypt.org/t/wildcard-certificates-via-http-01/51223) though rather than the current HTTP challenges we currently use. I think that authenticating via DNS may be beyond the scope of TurnKey to provide at the moment. Although, I'm fairly sure that we could support that via HubDNS.

So for now, I'm going to move this issue to the v15.1 milestone.

**Comment by bormanst** [comment]
You were right about the ETA as it went live on March 13:

https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

For what it's worth.

**Comment by JedMeister** [comment]
@EdNett - no idea sorry. I'm not even sure that Dehydrated supports it?! 

If you need it and like Dehydrated, then perhaps you could open an issue relating to it on the [Dehydrated issue tracker](https://github.com/lukas2511/dehydrated/issues) (although please double check first, perhaps there is already an open issue, or perhaps it's already supported?). 

FWIW it looks like `acme.sh` (another ACME bash client) [supports it](https://github.com/Neilpang/acme.sh/issues/331) so perhaps you could use that instead? 

Although it won't work with the TurnKey Confconsole Let's Encrypt integration, as that was explictly developed to depend on Dehydrated.

**Comment by JedMeister** [comment]
[Confconsole v1.1.1](https://github.com/turnkeylinux/confconsole/releases/tag/v1.1.1) now includes support for the Let's Encrypt v2 API endpoint out of the box. It requires some specific steps to use on a v15.x server, so please see the [release notes](https://github.com/turnkeylinux/confconsole/releases/tag/v1.1.1) for further info.
