### ISSUE TITLE
Can't import existing sqlite mumble database?

### ISSUE THREAD

**Issue by Enigma0** [turnkeylinux/tracker#939]
Can't find any documentation on how to do this.

I have a normal mumble server configuration that didn't use ICE/turnkey that I'd like to import into this turnkey mumble server.

**Comment by JedMeister** [comment]
My usage of SQLite is pretty limited and I've never migrated from SQLite to MySQL (what our appliance uses as a DB backend) before, but I don't imagine that it would be too hard...

A quick google (of "migrate db from sqlite to mysql") produces quite a few results (although many of them appear to be going the other way, i.e. MySQL -> SQLite). 

One that jumped out at me was [this](https://github.com/weewx/weewx/wiki/Transfer-from-sqlite-to-MySQL#using-sqlite3-and-mysql-commands). It's specifically relating to a piece of software (`weewx`) so you won't be able to follow those instructions exactly; but it looks like it provides most (if not all) of the info you'll need. 

Alternatively, [this StackOverflow answer](https://stackoverflow.com/a/87531/3363571) looks like it might be pretty useful and includes a Perl script. In the comments, there is a link to a [Python script](https://stackoverflow.com/a/1067151/3363571) to do the same thing.

Also, moving forward, this is our "development issue tracker" and is intended for reporting bugs and feature requests. For future reference, our [forums](https://www.turnkeylinux.org/forum) are a better place to post more general questions (or if you want to discuss a bit more before filing a bug). It's not that big a deal, but it is better if we can keep the GitHub issues limited to things that need to be done (bugs fixed or features implemented) rather than for Q&A. Apologies that I didn't mention that previously...

So, I'm going to close this "issue" for now. Please feel free to post back here regarding this specific topic and I'll see it. But any new questions or issues, please open a new thread on the forums (unless they are clearly a bug - in which case here is fine). It's not the end of the world if you post in the "wrong" place, but it's better if you post in the "right" place! :smile: 

Good luck with it!

**Comment by JedMeister** [comment]
PS, it may also be useful for you to know that under the hood, TurnKey is Debian (v14.x = Debian Jessie). Our next release (v15.0) will be based on Debian Stretch. 

Most software is installed from the Debian repos and you can get the installed versions from the commandline, e.g.: `apt-cache policy <package-name>`. Another option is to consult the [Mumble appliance manifest](https://releases.turnkeylinux.org/turnkey-mumble/14.2-jessie-amd64/turnkey-mumble-14.2-jessie-amd64.manifest). FWIW, a link to the manifest (and some other appliance related files) can be found on the relevant appliance page, e.g. [Mumble](https://www.turnkeylinux.org/mumble). Click the link to "Manifest and Sigs", then locate the `.manifest` file.

**Comment by Enigma0** [comment]
@JedMeister Well the issue is that it appears to be very difficult to do something that should be easy.

I honestly wouldn't even begin to know what to do with the information you provided. While I appreciate you providing it, it sounds like it has nothing to do with my issue. I may be wrong but I wouldn't know.

What I do know is that the default `mumble-server.sqlite` appears to still be needed and used. If I rename it, or point the `mumble.ini` to my imported `.sqlite`, the server (as seen in the MyMumb-Panel web interface) reverts to an uninitialized/unusable state.

When I point the `.ini` back to the original `.sqlite` & restart mumble-server, it picks up the changes again.

Likewise with swapping in & out the original `.ini` & the imported `.ini`.

I think there's something about the ICE/iceweasel password but I have no idea since the line that has that in the original `.ini` is either obfuscated or corrupted. It's whatever it is by default though.

**Comment by JedMeister** [comment]
Ah ok, it looks like I was headed off on a bit of a tangent... I wasn't aware that the Mumble appliance even had SQLite installed!? So that's news to me! The appliance is fairly new to the library, I didn't create it and other than testing, have not used it. TBH, I'm almost certain that you know more about Mumble Server/Murmur than I do... 

FWIW, I was under the impression that our Mumble appliance uses MySQL (as it's SQL DB) and doesn't even have SQLite installed. But it seems I was mistaken, I can see in the [manifest](https://releases.turnkeylinux.org/turnkey-mumble/14.2-jessie-amd64/turnkey-mumble-14.2-jessie-amd64.manifest) that it has a few sqlite related packages installed. Although I do note that it doesn't have the SQLite commandline client (that's the `sqlite3` package installable via apt).

`mumble-server` itself is installed from the Debian repos, currently that appears to be [version 1.2.8](https://packages.debian.org/jessie/mumble-server). My guess is that to migrate in an existing config, you'd need to match the versions (i.e. to/from same or similar version). So perhaps that's the issue? I'm not really sure... 

If you need/want a newer version of mumble-server, then 1.2.18 is in [jessie-backports](https://packages.debian.org/jessie-backports/mumble-server). Backports should already be enabled, so it should be as simple as this:
````
apt-get update
apt-get install -t jessie-backports mumble-server
````

If your data comes from a different Mumble-server version, then perhaps you can try to update/downgrade your other install (the one your trying to import from) to the same version we're using (or the version in backports if that's easier; my guess is that updating to a newer version would be easier than downgrading to an older one).

FWIW, I'm currently working on v15.0 (our next release) and it will be based on Debian Stretch, so it will have that newer version (1.2.18) by default.

Hopefully this time, some of my post is relevant and useful. If not, I suggest that you try asking the Mumble-server community as they would know much more about the specifics of it than I do. It may also be worth reaching out to the Debian Mumble-server package maintainer(s) and see if they perhaps have some insight or suggestion.

Regardless, please let us know how you go. AFAIK you're the first Mumble server user to post to us, and my guess is that if we can work this out, it will be useful knowledge for others in the future.

Thanks for persisting! Hopefully this post is more helpful! :smile:

**Comment by MPTMG** [comment]
From the murmur wiki. https://wiki.mumble.info/wiki/Migrating_a_Mumble-Server. On a side note it is probably much easier to just duplicate the settings of the existing server in a new server/server instance. If replacing file mumble.ini it is definitely replacing the data stored for icesecretwrite which is how the web interfaces can authorize to make changes... In this case it might be possible to achieve the direct replacement of the ini file if he copies the icesecretwrite from the original file as it is stored in the ini in plain text?
