### ISSUE TITLE
[Stretch] Cannot login to Adminer

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#954]
Relates to v15 of lamp (not yet publicly released)

Adminer login fails using mysql password.
This issue appears to be related to adminer rather than mysql since commandline mysql login still works.

**Comment by OnGle** [comment]
After further testing I believe it unlikely that issue #955 is related.

**Comment by JedMeister** [comment]
Is this still an issue @OnGle?

**Comment by EDavidF** [comment]
I am having this same issue, but on Ubuntu 16.04. New install. Nginx. "Access denied for user 'root'@'localhost'". Shell/command-line works fine.

**Comment by JedMeister** [comment]
@EDavidF - thanks for the feedback. Although TBH, I'm not sure if your issue is related to ours?! FWIW Ubuntu 16.04 appears to have it's own package of version (4.2.1)[https://packages.ubuntu.com/xenial/adminer] and Debian Stretch has (4.2.5)[https://packages.debian.org/stretch/adminer] (i.e. Ubuntu's version doesn't come from Debian, it appears to be packaged by Ubuntu themselves). 

Having said that, once we've confirmed an issue and if relevant; a fix, I'll post here (or at least a link). If you work out the issue, please share too. Thanks

**Comment by JedMeister** [comment]
This behaviour is because MariaDB by default, now uses a unix socket to authenticate. That means no password is needed to log in to MySQL if logged in as the root user. As normal username/password access is blocked, Adminer can't authenticate root.

It is possible to disable the unix socket and enable a password, but that will break some of the OS MySQL functionality (or so says the [MariaDB doc page](https://mariadb.com/kb/en/library/authentication-plugin-unix-socket/)). To work around that, we'd need to recreate the `debian-sys-maint` user, with the password saved in plain text config file. Obviously the permissions would be set so only root could see it, but still not ideal. 

MySQL has a tool; [mysql_config_editor](https://dev.mysql.com/doc/refman/5.6/en/mysql-config-editor.html) which can encrypt the passwords, but it's not unbreakable. It's also not available in the MariaDB install, so perhaps wouldn't even work with MariaDB? Besides, if an attacker already has root (access to read the file), then they can simply reset the password anyway (restart MySQL with no permission checks)!

I quite like the idea of root using a socket by default. It will be a change and many users may not like it, but it's probably a better way to go.

So the options as I see them are:

1. disable unix socket and revert to previous behaviour (i.e. MySQL root user/password). Would require (re)creation of `debian-sys-maint` and all that entails.
2. create a separate `admin` (or similar) user with root-like privileges and a password login. That would keep the new default behaviour for the root account while still providing 'root' access via Adminer. At least we don't need to store that password anywhere!

I'm leaning towards 2, but I'd love some input.

**Comment by JedMeister** [comment]
I'm now planning to implement option 2.

**Comment by JedMeister** [comment]
This should have been closed ages ago...

**Comment by lisawebcoder** [comment]
hello i cantg login to adminer in wamp server
does anyone know default login for adminer with my mysql selected?

**Comment by JedMeister** [comment]
Hi @lisawebcoder - This (now fixed) issue was related to a past release of [TurnKey Linux](https://www.turnkeylinux.org/) (our library of Debian based software appliances). I'm not at all familiar with this stuff on Windows (I'm a Linux user, both for work and personal usage). So I'm not 100% sure that this is relevant to you. Although I'll share what I know and perhaps it may assist heading you in the right direction?

Prior to hitting this issue, we used the 'root' MySQL user to log in. In our case, it was changes to the way that the default 'root' MySQL user could log in. Prior to Debian Stretch (the basis of our v15.x release), the 'root' user was a normal (albeit powerful) MySQL user account, with a password. In Stretch, that changed and the default 'root' user now uses a Linux socket, so doesn't require a password, but can't be used with Adminer (or any connection other than from the commandline of the local system). I'm not sure how it's done on Windows though (obviously Windows doesn't have Linux sockets, not sure if they have something similar though?).

I don't consider myself an Adminer expert, but I do know a bit about it. There is no "default" login, it uses the existing MySQL users. So you need to use the login credentials of an existing MySQL user that has appropriate permissions (or create a new user with those permissions). For our purposes, we created a special user (with root-like permissions) specifically for use with Adminer.

I hope that helps head you in the right direction...

**Comment by harrychristianx** [comment]
Try 'adminer' as your username and for your password, the one you've set while setting up Turnkey

**Comment by lisawebcoder** [comment]
hello i dont know what this thread is for? i dont recall posting any question here ok thxz--update ok i see the comment i put above ok i will review it ok thxz alot for replies
