### ISSUE TITLE
Mount point does not exist building core appliance

### ISSUE THREAD

**Issue by EngEryx** [turnkeylinux/tracker#960]
I followed this post 

https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/setup.rst

and when I run make I get the following error:

deck /turnkey/fab/bootstraps/jessie build/bootstrap
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/apt build/bootstrap;
fab-chroot build/bootstrap --script /turnkey/fab/common/conf/turnkey.d/apt;
mount: mount point /turnkey/fab/products/lamp/build/bootstrap/proc does not exist
Traceback (most recent call last):
  File "/usr/lib/fab/wrapper.py", line 34, in <module>
    CliWrapper.main()
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 388, in main
    commands.run(name, args)
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 261, in run
    command.module.main()
  File "/usr/lib/fab/pylib/cmd_chroot.py", line 110, in main
    chroot = Chroot(newroot, environ=get_environ(env_conf))
  File "/usr/lib/python2.7/dist-packages/chroot.py", line 69, in __init__
    self.magicmounts = MagicMounts(self.path)
  File "/usr/lib/python2.7/dist-packages/chroot.py", line 28, in __init__
    self.mount()
  File "/usr/lib/python2.7/dist-packages/chroot.py", line 39, in mount
    executil.system("mount -t proc", "proc-chroot", self.paths.proc)
  File "/usr/lib/python2.7/dist-packages/executil.py", line 56, in system
    raise ExecError(command, exitcode)
executil.ExecError: non-zero exitcode (32) for command: mount -t proc 'proc-chroot'  '/turnkey/fab/products/lamp/build/bootstrap/proc'
/usr/share/fab/product.mk:526: recipe for target 'build/stamps/bootstrap' failed
make: *** [build/stamps/bootstrap] Error 1

**Comment by EngEryx** [comment]
Kindly let me know what I need to do.  Thanks in advance

**Comment by JedMeister** [comment]
Hi @EngEryx - this is our issue tracker for lodging bugs and feature requests (please see [CONTRIBUTIONS.md](https://github.com/turnkeylinux/tracker/blob/master/CONTRIBUTING.md#bug-reports-and-feature-requests)). 

Perhaps this is a bug. But as we use TKLDev for development and everything is still working fine for me and no one else has reported issues, my guess is that it's not so much a bug in TKLDev itself. I suspect that it's more likely an issue because we're currently in the process of migrating our build infrastructure to build v15.0 (which will be based on Debian Stretch).

Under normal circumstance, this would be better discussed on our [support forums](https://www.turnkeylinux.org/forum/support). As such I am going to close this as an "issue' for now. However, seeing as you've posted here already, rather than make you repost on the forums, I'll try to assist you here for now anyway...

TBH, I'm not really sure why it isn't working for you. My guess is that there was a previous error and something is locked up. Without knowing more about your TKLDev setup and what you have done previously, my suggestion would be to retry with a `make clean` first. If that still doesn't work, perhaps reboot your TKLDev first and then retry:
```
cd lamp
make clean
make
```

If you do that and you continue to have issues, please give me the output of the following commands:
```
mount
ls -l /turnkey/fab/products/build
```

**Comment by EngEryx** [comment]
Hi @JedMeister  thanks,

I repeated the instructions from the TKLDev and I was able to build. Tested the iso file and all worked well.

Cheers!
