### ISSUE TITLE
Non riconosce WebAdmin da  remoto porte 123XX

### ISSUE THREAD

**Issue by Raaopi** [turnkeylinux/tracker#969]
Non riconosce le porte di admin in remoto e in questo modo non si possono cambiare le impostazioni di Webadmin, come la grandezza del caricamento di file, inoltre sarebbe bene applicare  migliore menu' tipo softaculus per installazioni  veloci di altri wordpress  nello stesso server

**Comment by JedMeister** [comment]
Hi, this is our issue tracker, explicitly for reporting bugs and feature requests. For support, please use our [forums](https://www.turnkeylinux.org/forum).

Also I only speak English, so am not 100% that I understand what you are saying (I used Google translate, but it doesn't totally make sense to me).

It seems like you are having issues trying to connect to the port (i.e. 12321) or something?

It also sounds like you would like to install multiple apps on the one server. We do things quite differently to "installers" provided by other projects. We believe that our install method is superior and  much more robust. But because of the way that we do things, what you request would require us to totally rewrite our whole infrastructure. 

We do intend to support multiple apps on the one host, but we intend to do it via a alternate path and it will still be quite some time away. if you wish to have multiple servers on the one host, we recommend that you use our LXC appliance (then additional appliances as guests), or use the docker builds of our appliances (on a host with docker installed).

See as this appears to be more of a support request than a bug report, I'm going to close it for now. If I've misunderstood and you wish to reword your OP and reopen it, then that's fine. Also even though I'll close it, we can continue to discuss it here.
