### ISSUE TITLE
Broken installation procedure in conf.d/main

### ISSUE THREAD

**Issue by antoneliasson** [turnkeylinux/tracker#979]
turnkey-revision-control-14.2-jessie-amd64

conf.d/main, line 56 onwards:

```
# replace gitweb theme with a nicer one (github inspired)
GITWEB=/usr/share/gitweb
GITWEB_THEME=$SRC/gitweb-theme

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
git clone https://github.com/kogakure/gitweb-theme.git $GITWEB_THEME
unset HTTP_PROXY

FILES="gitweb.css git-logo.png git-favicon.png"
for f in $FILES; do mv $GITWEB/static/$f $GITWEB/static/$f.orig; done
for f in $FILES; do ln -s $GITWEB_THEME/$f $GITWEB/static/$f; done

# patch loggerhead to move apache-credit down
cat >> /usr/share/loggerhead/static/css/global.css<<EOF
#loggerheadCont {
    padding-bottom: 30px;
}
EOF
```

This is bad practice. Files in /usr are owned by the package manager and manual changes to them will be overwritten on package upgrades. TKL's installer encourages package upgrades on first boot, so after the initial configuration the user likely ends up with an appliance without the customizations above.

**Comment by JedMeister** [comment]
Whilst you are correct (re pointing out the bad practice) it's unlikely that it would cause any significant issues. Worst case scenario, the user would get the default theme back again. 

For that to happen though, either there would need to be a security update (first boot prompt and auto updates only apply to security patches, not simply updated packages), or the user would need to manually run an `apt-get upgrade`. Whilst either of those could happen (and FWIW there was a sec update to `gitweb` in Wheezy), like I say, the worst case scenario would be that the user gets back the default theme, and we could direct them how to fix it.

Having said all that, you are absolutely right and for the v15.0 release, we should do it better. TBH, I'm not particularly familiar with `gitweb` so I'm not sure on the bet way to resolve that. If you have any clear ideas, please feel free to share.

Also, out of interest, both Loggerhead (the web UI for Bazar) and WebSVN (the SVN web UI) are both dead (abandonware - last release 2011). We continued to use them because they were packaged in Debian. But now they are gone, we're considering removing Bazar from the revison control appliance. I just did a a quick google and came across [Submin](https://supermind.nl/submin/) which looks like it provides a UI for both SVN and Git, so perhaps we might consider that?

Another thought we've been considering for v15.0 is [Gitea](https://gitea.io/). It's written in Go so is nice and lightweight. It only supports Git, but we could make it a standalone appliance. From my browsing, it appears to be like a simplified, low resource GitLab. Just the stuff you need, with none of the bells and whistles.

**Comment by antoneliasson** [comment]
Personally I only care about git. I doubt anyone is setting up new SVN or bzr hosting these days. I don't know how popular Mercurial still is.

I think focus should be on working with the code first, and publishing it in a web interface second. I quickly abandoned the revision control appliance after installing it and finding out that it was not set up for git access over SSH.

I had not heard of Gitea before. From a quick test it seems to be exactly what I am looking for in a personal code hosting system, assuming that the installation procedure is reasonably simple. A standalone appliance with Gitea would probably suit my needs. I'm not sure what the TKL philosophy is regarding service integration, but I would prefer an instance with as few components as possible so that I can integrate it with my existing database server and Redis server etc, or just settle for a built-in SQLite database with no memory cache.

**Comment by JedMeister** [comment]
> I doubt anyone is setting up new SVN or bzr hosting these days. I don't know how popular Mercurial still is.

I agree, although we do get a few legacy SVN users who use our appliance for their SVN purposes. I think you are right WRT new projects as well as bzr and hg having little to no use these days.

WRT Gitea, we would look to make it a fully working standalone appliance. That will most likely mean it will include a web server (acting as a front end reverse proxy) and perhaps a DB (if required). But I would not expect anything more than that (beyond what is included in [Core](https://www.turnkeylinux.org/core)). I'd be more than happy to assist you (probably in our [forums](https://www.turnkeylinux.org/forum)?) to pare it back to bare minimum and/or assist you to integrate it with your existing servers.

Actually, from what I can gather, it does not require a DB backend (although I could be wrong, I haven't even tried to install it yet). So chances are what we publish may be close enough to your desires to use as is?!
