### ISSUE TITLE
TimeCapsule (Remote Apple Time Machine) -- New Appliance

### ISSUE THREAD

**Issue by ghost** [turnkeylinux/tracker#986]
Apple TimeMachine compatible backup server. Racoon used for remote secure access. First commit done with small list of additional work required (reset a password on first boot, generate a new shared secret for racoon on first boot, and config racoon to listen on correct IP on first boot). I will finish up the additional work soon and update as necessary when we get the new tkldev.

**Comment by MPTMG** [comment]
Code published https://github.com/MPTMG/TKL-TimeCapsule.

Just need to edit readme and add art.

**Comment by JedMeister** [comment]
Nice work mate. You rock! Hopefully we'll have v15.0 Core ready for at least an RC release early next year. There are still 2 major issues that I'd like resolved before we do a release, but it's getting pretty close.

**Comment by MPTMG** [comment]
Netatalk in debian 9 (2.6 something.. current is 3.11) is too old a version for current compatibility with TimeMachine.

When installing things from source is there any objection to just including the file in /usr/local/src as opposed to downloading it as part of the build process?

**Comment by JedMeister** [comment]
I'll try to have a closer look at this one and give more specific and granular feedback (as I did with Syncthing). TBH I'm not sure why I didn't see your previous comment earlier? Anyway...

Re including source code in the overlay. 

**Short answer:** Please download it rather than including it within the overlay. 

**Longer answer and rationale:** As a general rule we don't like to include anything in the overlay, other than relatively simple text files (i.e. no SQL dumps or binary files).

The reason for that is that it's not so easy for any of us (including end users) to confirm that they haven't been tampered with. It's not that we don't trust you, it's that we don't want to have to trust anyone more than we have to (including ourselves). 

The only current exception to that (i.e. including binary files in the overlay) is apt repo gpg key (as per my notes in Syncthing). Currently I manually check those against their source prior to build and we plan to also include automated testing in the future.

**An aside:** I note that they also provide a [Webmin module](https://sourceforge.net/projects/netatalk/files/Webmin/). It hasn't been updated since 2013, but it might be worth having a look to see if that works ok. If so, it might be worth including too?

**Comment by MPTMG** [comment]
BTW this appliance is adapted from this howto https://docs.bytemark.co.uk/article/configuring-time-machine-to-backup-to-your-bytemark-cloud-server/

You will need a mac to test, I have tested the appliance with my mbp and it naturally works, but this will give you the requisite information to understand how one connects from a mac and configures a TM backup.

Hence my comments on putting together some documentation for this one. 

**Screenshot of it working for my latest backup.**
![image](https://user-images.githubusercontent.com/23151593/42632859-95241402-85ac-11e8-8b99-5b8b9cff53d3.png)

**Comment by JedMeister** [comment]
Hmm, missed this one because it wasn't pinned to the v15.0 milestone. Fixed that now though!

I see what you mean about the package in Debian. Even the package in testing and unstable is only 2.2.6, upstream is 3.1.1.

Building from source is not that big a deal, although it would be good if we had a script/document on how users could do that. Your idea of an automated script is a good one, although I wouldn't probably like to have that running by default. At least not overwriting the binary without some implicit approval of the user (just in case something goes wrong). If there were an easy way for user to make it automatic though, then I'm cool with that.

Re a url to always get the latest, try this:

https://sourceforge.net/projects/netatalk/files/latest/download

That defaults to the `bz2` file but that's not really an issue (just install `bzip2`). Alternatively, if you wanted to be really tricky you could just pull the header from the url with curl, then use that to work out the filename and url of the gzip alternative and download that.

> Is there a way we can just rebuild the appliance in a minor release if there is an update to netatalk? 15.1, 15.2, etc. etc.

We could certainly rebuild and in fact, I hope to rebuild appliances a bit more often than we have in thaepast. v15.0 has taken way to long. Ideally I'd like to be doing a few releases a year at least. We'll see how that goes though...

> Is there a way to include detailed instructions in the README for usage (deviate from the simplified norm), such as creating a CIsco VPN connection on OSX and connecting to the default share? It would help out end users significantly.

That should be fine. Or if it's too much for the readme (IIRC there is a limit where it breaks the website when we process it for the appliance pages)), we could just add a docs dir and link to it in the readme. Another idea is that we could even include it in the appliance itself?! If it were written in rst then it's easy to read on commandline and can also be really easily turned into html so we could even potentially host the docs on the appliance?

> I would like to include Zero Tier One, but will hold off for now as I would like to have it be separate and easily integrated into any appliance. Essentially something that can be part of turnkey where it adds the repo, installs, and includes configuration options in the confconsole should an appliance creator choose to include it.

Agreed. IMO it'd make a great [confconsole plugin](https://github.com/turnkeylinux/confconsole/tree/master/plugins.d) ([docs](https://github.com/turnkeylinux/confconsole/blob/master/docs/Plugins.rst)).

Unfortunately I don't have a Mac (or access to one) but I still think that this would be an awesome addition to the library.

**Comment by MPTMG** [comment]
> Agreed. IMO it'd make a great confconsole plugin (docs).

I already took care of the confconsole plugin https://github.com/MPTMG/TKL-ZeroTierOne
Everything necessary is included repo and key, install package, remove package, add network, delete network, and display networks is built into confconsole. If one added https://github.com/MPTMG/TKL-ZeroTierOne to any appliance it would allow for installing an configuring through confconsole. Once again not sure how you guys include it via the Makefile to make it accessible for everyone.

On a side note I already created a branch of this appliance using Zero Tier One instead of raccoon as the configuration is easier for the end user. https://github.com/MPTMG/TKL-TimeCapsule/tree/ZeroTier

I will get started on creating a detailed readme.

For updating I was thinking a confconsole plugin. With the link you provided I could fetch latest code,  backup config, and config/make/make install and copy back the config. Users would have to choose to update via the confconsole hence it would not be running and overwriting the binary without their knowledge. Potential problems: dependency changes between versions, changes to config file settings, etc.... Probably wouldn't run into problems on minor releases of netatalk.

**Comment by JedMeister** [comment]
Great work mate! I haven't had a proper look, but on face value, it looks awesome! You rock!

Ok, well I'll have to have a look at the fork and have a bit of a think.

I need to try to keep focused on getting the rest of the appliances updated and released, but now we're on v15.0, even if they don't make it into the next stage of the release, we can add any/all of them later.

You're doing great work with these new appliances and I don't want it to drag on any longer than it has to.

**[Completely OT]**: Can you please shoot me an email. I have a guy here in Australia who might have some work for you contracting on a big Mumble set up?! He's tried the v14.2 Mumble appliance and is really impressed and is looking for someone who knows a bit about Mumble. I have his details, but don't really want to post them publicly. I thought I had your email, but couldn't find it.

**Comment by JedMeister** [comment]
@MPTMG - sorry to bump this thread. I just realised that I hadn't explicitly mentioned you and wanted to make sure that you got the message (figured you probably had, but wanted to be sure). Please email me (jeremy AT turnkeylinux.org). Even if you're not interested, it'd be handy to have your email.

**Comment by MPTMG** [comment]
Bumping this thread. Waiting on decision on selected VPN integration. Similar to TVHeadend firewall enabled by default appliance access via VPN/Local dilemma.

**Comment by MPTMG** [comment]
https://www.zerotier.com/

FWIW willing to help in anyway necessary when TKL decides how they want to handle the VPN "situation".

Working solution to add ZeroTier to any appliance via confconsole and join, leave, display networks.

https://github.com/MPTMG/TKL-ZeroTierOne

**Comment by JedMeister** [comment]
Unfortunately we missed the boat with this one. MPTMG has closed his account and disappeared and unfortunately, I didn't have a fork of his buildcode...
